<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EditRule NameUser NameException Type_96c83f (1)</name>
   <tag></tag>
   <elementGuidId>5653647b-f480-4136-ab96-aa6faee34300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R240042226928873910_column_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='R240042226928873910_column_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27ef76c1-af8c-4a80-8fc1-9f90e623ffe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R240042226928873910_column_name</value>
      <webElementGuid>0d4fcd49-d159-467b-9d55-ffd4c1bd6cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>53d1156a-7234-4f03-b0ec-0016a0665c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>001b3aee-4358-4c96-8739-436add032967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3937a6ee-66c6-47ee-b83f-3b9951a5a8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>ac979245-a67f-4407-8808-54adcbf9462e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EditRule NameUser NameException TypeExceptions DetailsJustificationStart DateEnd DateApproval StatusApproval ByException VersionFile NameLast Updated DateFile content</value>
      <webElementGuid>7ba88788-221c-49d9-b7c8-e26b87ffeb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R240042226928873910_column_name&quot;)</value>
      <webElementGuid>563e3d24-65fa-46d3-ab38-f8f7525a7685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='R240042226928873910_column_name']</value>
      <webElementGuid>bb62a178-e0c2-47d9-aa0d-e2df7657fe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R240042226928873910_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>21b15b10-258b-456b-a0b1-c2fbca978d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>bd84a130-fce1-4234-bf6b-88af7cc67c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'R240042226928873910_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'EditRule NameUser NameException TypeExceptions DetailsJustificationStart DateEnd DateApproval StatusApproval ByException VersionFile NameLast Updated DateFile content' or . = 'EditRule NameUser NameException TypeExceptions DetailsJustificationStart DateEnd DateApproval StatusApproval ByException VersionFile NameLast Updated DateFile content')]</value>
      <webElementGuid>d37a7333-aaa1-4323-a913-35b1bff214d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
