<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create Payments vs. Enter Customer Receipts Rule</name>
   <tag></tag>
   <elementGuidId>c82af0d6-c8f2-427e-b437-3e7eb287bb37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-IRR-col-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R195180776850763251_col_values_drop']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb6251c8-fde2-4185-ab11-4d2e32430cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>338f03c3-7e69-4d6a-94f9-637626fdf0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-col-value</value>
      <webElementGuid>0e328a35-7aa7-4801-b755-6e140bd34ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-return-value</name>
      <type>Main</type>
      <value>Create Payments vs. Enter Customer Receipts Rule</value>
      <webElementGuid>b1b56fcd-846a-4e7d-ac60-dfec3cebd9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Payments vs. Enter Customer Receipts Rule</value>
      <webElementGuid>117b35f0-6d7c-4fbe-8bb1-6792929b3059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R195180776850763251_col_values_drop&quot;)/a[@class=&quot;a-IRR-col-value&quot;]</value>
      <webElementGuid>82076de2-0411-48cd-ac0a-e945bf2886ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R195180776850763251_col_values_drop']/a</value>
      <webElementGuid>1caa97cf-0c77-412f-af7d-060fa977c7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create Payments vs. Enter Customer Receipts Rule')]</value>
      <webElementGuid>2359615b-dc13-408f-936a-7007388ed094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[93]</value>
      <webElementGuid>d6156dd6-4889-4e35-bf34-7a26e4186e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html/div/a</value>
      <webElementGuid>e22bf38e-33f3-4e9e-8b17-adfe3ad5011b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Create Payments vs. Enter Customer Receipts Rule' or . = 'Create Payments vs. Enter Customer Receipts Rule')]</value>
      <webElementGuid>dd8bbbe7-e910-4041-b2db-df50714805bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
