<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ktln_eam_user1 (1)</name>
   <tag></tag>
   <elementGuidId>9df239f1-5fe6-4e96-945e-d6ed86a2ab20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L29085486908535153</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='L29085486908535153']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1043fd12-f974-47c8-8bcb-4b1c49530396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button t-Button--header t-Button--navBar js-menuButton</value>
      <webElementGuid>e16ee5b8-e882-48fb-b97f-93086a8ce08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e192d2e6-3fce-42e0-a859-3ce1e068ff02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L29085486908535153</value>
      <webElementGuid>95338a2c-1a68-4b19-9798-828c6dfcab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>menu_L29085486908535153</value>
      <webElementGuid>02767222-ff59-405f-97c2-157f70cb003c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>7fd3d2dc-d89e-43e1-b165-2f2e41de83ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      ktln_eam_user1
  </value>
      <webElementGuid>3858381d-b554-4344-8b12-ba3e630a4b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L29085486908535153&quot;)</value>
      <webElementGuid>0a09ce6d-9b7d-4bf7-9809-3d592aa2684c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='L29085486908535153']</value>
      <webElementGuid>d9dbb11b-cba0-47ea-869d-002ba1bb60b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='29085486908535151']/li[2]/button</value>
      <webElementGuid>458f8c5b-d1bc-4686-9274-b0b8a4f7c329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>a3d8acbf-b172-4822-858b-bfaa6324fc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'L29085486908535153' and (text() = '
      ktln_eam_user1
  ' or . = '
      ktln_eam_user1
  ')]</value>
      <webElementGuid>aa4d11ce-4485-4b94-a7d0-fdecfdf961cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
