<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_a-Menu-statusCol</name>
   <tag></tag>
   <elementGuidId>82d63f77-7896-48ad-9584-9c453c6ce961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R195180776850763251_actions_menu_2 > div.a-Menu-inner > span.a-Menu-labelContainer > span.a-Menu-statusCol</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='R195180776850763251_actions_menu_2']/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>279aa568-af9c-425d-b11f-e4afe011289e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-statusCol</value>
      <webElementGuid>ee23a3d1-ca8d-41be-aafd-dc3f43bc8576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R195180776850763251_actions_menu_2&quot;)/div[@class=&quot;a-Menu-inner&quot;]/span[@class=&quot;a-Menu-labelContainer&quot;]/span[@class=&quot;a-Menu-statusCol&quot;]</value>
      <webElementGuid>c2ff86a0-5b1b-4032-90c5-8d448bb852da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='R195180776850763251_actions_menu_2']/div/span/span</value>
      <webElementGuid>c8d0ae09-c77c-46ab-b496-71c7dd2c3e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/span</value>
      <webElementGuid>f72bf6aa-004e-418d-81e0-ab53ed39c734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
