<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go</name>
   <tag></tag>
   <elementGuidId>87207d3d-95e8-4fd6-84ca-5ae59bee5017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R242004504603843036_search_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R242004504603843036_search_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ec5515c-748d-45c2-8748-90683e4999e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R242004504603843036_search_button</value>
      <webElementGuid>f195336e-0174-4225-a67e-54c946578080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--search</value>
      <webElementGuid>74d9cd4d-bf68-4f71-9ad6-c3659612ac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33752f36-274c-4279-9711-3732bfcc6372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>ec63847b-ff50-4191-9580-050198d067d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R242004504603843036_search_button&quot;)</value>
      <webElementGuid>d0a6a572-bcff-44a3-990b-bff5e2e7f24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b9020a0-e442-4201-96f0-00ec072f2c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R242004504603843036_search_button</value>
      <webElementGuid>dde6a97f-3498-47e7-8dd4-ac4a0d1bc05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--search</value>
      <webElementGuid>349a34f8-c2be-4b06-9ae5-60df0fd6c326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00fc2767-3433-4bd5-bfae-bcad476a2047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>7718ad29-e114-4c9f-a209-9032d04ceba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R242004504603843036_search_button&quot;)</value>
      <webElementGuid>482c2472-7f38-4acd-9a66-259f3b51e15c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R242004504603843036_search_button']</value>
      <webElementGuid>f0197a42-e5a1-4010-a734-c28e7b4ecd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R242004504603843036_toolbar_controls']/div/div/div[3]/button</value>
      <webElementGuid>a992b5cd-89d8-43d3-b8a8-a274748d41f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity Report'])[1]/following::button[2]</value>
      <webElementGuid>5fa68e27-dc10-4863-8b96-9ead4e6280fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::button[3]</value>
      <webElementGuid>dcce98c0-90b7-4efe-9219-8b344287264f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[3]/preceding::button[1]</value>
      <webElementGuid>860e0a65-587d-418f-80f2-7097d52ab7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>c79f3eb8-f38f-4be8-b2fc-ab2a07457e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'R242004504603843036_search_button' and @type = 'button' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>b7b6ef2d-a935-42a4-bdc7-669a1d7c49f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
