<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select any one -STP_ObjSet - STP-F_95ab96</name>
   <tag></tag>
   <elementGuidId>80003c8a-4dc1-4d2f-a4da-9bbd9b9f1deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P84_OBJECT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P84_OBJECT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ad42a294-fc23-48d1-8410-7de6b6418195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P84_OBJECT</value>
      <webElementGuid>2e991a18-210c-45f2-9378-1649e1d748f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P84_OBJECT</value>
      <webElementGuid>eaabf540-12b3-4383-85c7-d7b825fa648f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>931e7615-d01d-484e-8e70-d2597306c564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97ac2ebd-4ffd-4828-a5d3-a4ae794ced96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>37d1f822-2b41-4f21-ae43-4a9f9c879ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select any one -
STP_ObjSet - STP-Funds Capture Payment Method</value>
      <webElementGuid>182d04b4-aa53-4bc9-bfef-c05c6deb679a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P84_OBJECT&quot;)</value>
      <webElementGuid>b3bed056-1572-4ea0-8df2-5d55757fc0e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P84_OBJECT']</value>
      <webElementGuid>f88f278e-7b7b-4d8a-bfb1-43746d60fdbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P84_OBJECT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>b1840361-e008-4a5f-9fc6-5f8c1028e72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/select</value>
      <webElementGuid>eade1a42-5dad-44bc-bf07-dcc2312028e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P84_OBJECT' and @name = 'P84_OBJECT' and (text() = '- Select any one -
STP_ObjSet - STP-Funds Capture Payment Method' or . = '- Select any one -
STP_ObjSet - STP-Funds Capture Payment Method')]</value>
      <webElementGuid>b740cc35-a62f-4507-b824-a6244f007351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
