<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Justification of Role Owner (1) (1) (1)</name>
   <tag></tag>
   <elementGuidId>2607ee95-3c9a-4cd7-9dc7-3d8b8625ab00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C97176025254990417 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='C97176025254990417']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd404397-f70b-4e91-b0ec-b3485e72af3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>31fc9ecc-0a96-4307-ace2-fd7ec6106b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>97176025254990417</value>
      <webElementGuid>10d2be4d-895a-45ee-a4f4-3587771ff68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>38e0a3f8-0e28-44ec-8cd5-042562f0e67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Justification of Role Owner</value>
      <webElementGuid>01c0d414-b2b6-4552-b4d3-77c802922aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;291211863100602603&quot;)/tr[1]/th[@id=&quot;C97176025254990417&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>f4a31bf8-d8af-40b1-a389-5e187a2dc67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C97176025254990417']/a</value>
      <webElementGuid>ac33e10f-50fd-47f7-a24c-486a33551175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Justification of Role Owner')]</value>
      <webElementGuid>1a4f8e8d-5881-40b7-9ce3-af1c0ce8cd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[22]/a</value>
      <webElementGuid>e8ddeffc-3c27-46f2-8a69-6c536926577c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Justification of Role Owner' or . = 'Justification of Role Owner')]</value>
      <webElementGuid>8c4b74cc-336c-48df-9e68-df1296e67c37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
