<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verified By (Role Owner) (1) (1) (1) - 152 (1) (1)</name>
   <tag></tag>
   <elementGuidId>7c30394f-063e-465f-9896-a9332fc0d8a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C97176839460990422 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/div/div/div/div[2]/div[2]/div[6]/div[1]/div/div[1]/table/tr/th[21]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8bb95c2-aa57-44e4-9699-83236eb4638d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>256a91d8-2192-4b69-94d1-298affd51f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>97176839460990422</value>
      <webElementGuid>dc066174-5e99-409b-b4f1-edbc1a6a7aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>81bb110d-378c-4cf4-bb8e-93978811de73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verified By (Role Owner)</value>
      <webElementGuid>eb5176be-ac4e-49ea-8259-46b68b740532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;291211863100602603&quot;)/tr[1]/th[@id=&quot;C97176839460990422&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>33fc2f77-07fc-4ec3-afe1-ad6c429c35f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C97176839460990422']/a</value>
      <webElementGuid>25e6410b-54e2-4a8e-aaec-0f9a543831b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verified By (Role Owner)')]</value>
      <webElementGuid>de05a52a-0862-4bd0-9c4e-89897b7ab094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[21]/a</value>
      <webElementGuid>7e1efb47-1ef6-40eb-b4aa-5ddfd797ef27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Verified By (Role Owner)' or . = 'Verified By (Role Owner)')]</value>
      <webElementGuid>e56eb53e-c9d8-492a-aba2-f10610f98540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
