<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputselectUnselectAll (1) (1) (1) - 160 (1)</name>
   <tag></tag>
   <elementGuidId>20711628-6615-423a-9415-13b3d7601585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectUnselectAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/div/div/div/div[2]/div[2]/div[5]/div[1]/div/div[1]/table/tr/th[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b7554e8-7125-4061-8eeb-bf1694887caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>16d28b1d-f013-4b37-88c0-95a7bb1f57ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectUnselectAll</value>
      <webElementGuid>f2f65ae0-f0ac-4bd9-a229-a00ec66dd448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select/Unselect All</value>
      <webElementGuid>b925a445-2039-44a0-b5db-e46d84db12d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;291211863100602603&quot;)/tr[1]/th[@id=&quot;C97174800243990413&quot;]/span[@class=&quot;a-IRR-headerLabel&quot;]/input[@id=&quot;selectUnselectAll&quot;]</value>
      <webElementGuid>c50b7f65-a645-4f12-adff-c9fb4f32ccd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectUnselectAll']</value>
      <webElementGuid>d3cbe7cd-9ee0-4eb3-b694-321453b61ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C97174800243990413']/span/input</value>
      <webElementGuid>6dce5833-f337-4711-b049-65641b7fd035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/span/input</value>
      <webElementGuid>583a2587-f404-43fd-9147-a4860ee398eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectUnselectAll' and @title = 'Select/Unselect All']</value>
      <webElementGuid>24d3aabc-1f27-4482-959b-0caae18d3c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
