<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1 -                1,000 of           _4f81a1</name>
   <tag></tag>
   <elementGuidId>ed05a6e9-e430-4938-a6c3-f5751769e02b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-IRR-pagination-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uacReport_data_panel']/div[2]/ul/li[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>816fd725-cb59-49bd-80ed-35764a7e9f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-pagination-label</value>
      <webElementGuid>294c50c6-7706-40b7-b302-0c1de5e8aea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                   1 -                1,000 of               14,393</value>
      <webElementGuid>6c1029ac-e04c-4530-86cf-5b0e8bc366b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uacReport_data_panel&quot;)/div[@class=&quot;a-IRR-paginationWrap a-IRR-paginationWrap--bottom&quot;]/ul[@class=&quot;a-IRR-pagination&quot;]/li[@class=&quot;a-IRR-pagination-item&quot;]/span[@class=&quot;a-IRR-pagination-label&quot;]</value>
      <webElementGuid>b9b9610d-5b3e-463b-8164-5ad4c0a283f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uacReport_data_panel']/div[2]/ul/li[2]/span</value>
      <webElementGuid>b7dfde30-68be-46e5-b665-e7a269bb2c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>ee382737-ff91-4417-89a8-f9c313120301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '                   1 -                1,000 of               14,393' or . = '                   1 -                1,000 of               14,393')]</value>
      <webElementGuid>90efc881-1199-46ba-a017-7e97e78590e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
