<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select any oneEBizApp_JDBC_EnvKTLN_C_10fa97</name>
   <tag></tag>
   <elementGuidId>5bc3b430-6400-4d36-b124-4b233d519301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P0_ENVIRONMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>102a351b-182a-49c0-b898-a10582a75b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>5ca51f9a-645d-4dea-858b-b037b3d7f2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>63a55424-ad7e-45dc-8291-5bc32d31351e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>6c662830-db9c-483c-85f0-972253e4fd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9845a35-f5b6-4db8-80c0-ede679f2b813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>23bf7294-19b6-4d59-aefb-ebee65ae0695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P0_ENVIRONMENT');</value>
      <webElementGuid>af13bafa-718b-48b2-b617-4e11f6ffb043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
EBizApp_JDBC_Env
KTLN_CloudERP
KTLN_CloudERP_EACM
McD_GRM_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
</value>
      <webElementGuid>ceedb45e-23a5-4079-b6c6-69a7cf7694fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT&quot;)</value>
      <webElementGuid>e1c6c2e9-dfed-42e4-b594-7378000f54c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P0_ENVIRONMENT']</value>
      <webElementGuid>cbd7de5a-2e0e-4f7c-b582-bb6ef868820c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>f45ece68-03ee-43e1-b317-9baef631df40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b10d229d-e678-43ba-a1ee-5927cc541fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P0_ENVIRONMENT' and @name = 'P0_ENVIRONMENT' and (text() = 'Select any one
EBizApp_JDBC_Env
KTLN_CloudERP
KTLN_CloudERP_EACM
McD_GRM_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
' or . = 'Select any one
EBizApp_JDBC_Env
KTLN_CloudERP
KTLN_CloudERP_EACM
McD_GRM_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
')]</value>
      <webElementGuid>9e6ed590-4cae-4066-a549-75ef28fc44f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
