<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P10_OBJECT_NAME</name>
   <tag></tag>
   <elementGuidId>28a9b3ca-294a-4ad3-8fb8-0706fa6d2998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P10_OBJECT_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'P10_OBJECT_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71cb71be-080a-4d6b-b4ae-9bfad770fa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f039a951-1815-4fec-8043-e04c95d0fd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_OBJECT_NAME</value>
      <webElementGuid>432ec03d-4367-40fa-8bf8-4c1c555a6f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P10_OBJECT_NAME</value>
      <webElementGuid>58df6fbe-02a9-4bd6-bc9b-c9316733a18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>b63dfa0f-7991-4c8d-b351-feb6c6ee1f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Roles-NEW_CLOUDERP</value>
      <webElementGuid>573ed444-a7ed-4669-b99c-ea435f7b2dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>511ffa77-fc28-4eff-b15e-62cbf4b24473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>cc507e0d-b939-489d-a7f5-23712a962e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_OBJECT_NAME&quot;)</value>
      <webElementGuid>520c38d1-5cfe-4ecf-88c8-3abf9b8a6f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'P10_OBJECT_NAME']</value>
      <webElementGuid>69674c7d-a657-4920-909d-9cc27f6fe083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P10_OBJECT_NAME']</value>
      <webElementGuid>b0c1dda2-6361-41dd-9d93-858cc288ba7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_OBJECT_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>96ac044e-1ece-42ff-aff6-00a58c686248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>dad53aa9-69c8-4640-8079-e8f0fdbd6574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
