<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_is nullis not nulllikenot likeinnot _365127</name>
   <tag></tag>
   <elementGuidId>dc8e6747-73e0-4c17-b575-443ea60f00d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mngSnap_STRING_OPT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mngSnap_STRING_OPT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2d31866e-dc16-45b1-899f-5d311e942682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mngSnap_STRING_OPT</value>
      <webElementGuid>ca6503a1-c0ed-403f-a9fd-b1cdf4ec2546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select a-IRR-operator</value>
      <webElementGuid>7910e544-9e79-4ac6-a7c3-752b31387749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-type</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>7fae6b9e-5ae4-413f-b9c9-f12c5a985054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>562095e0-3237-465d-a253-76ed298858e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>95929cce-3de7-4357-afcd-1b50316ae44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression</value>
      <webElementGuid>4621342b-ca3c-4291-acd5-af75793b8fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mngSnap_STRING_OPT&quot;)</value>
      <webElementGuid>55d1b679-445b-42bb-982d-c7b88c8fceb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mngSnap_STRING_OPT']</value>
      <webElementGuid>c994cd3d-8870-4385-a070-9684efc6a3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mngSnap_column_filter']/div/div[2]/div/div[2]/select</value>
      <webElementGuid>653b4591-6753-49f0-ae26-15de242bc285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/select</value>
      <webElementGuid>bb68b653-2f35-4f8d-beeb-393369573498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mngSnap_STRING_OPT' and @name = 'p_ignore_10' and (text() = '=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression' or . = '=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression')]</value>
      <webElementGuid>816bec99-9a02-4416-9315-cc9d2b749e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
