<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select any one -STP_FCPM_MAY08_V1__abd34a</name>
   <tag></tag>
   <elementGuidId>b99e1e55-d3ba-4ac8-8313-0565837b5a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P75_RESULT_SET</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'P75_RESULT_SET' and @name = 'P75_RESULT_SET' and (text() = '- Select any one -&#xd;
STP_FCPM_MAY08_V1_20240508093844' or . = '- Select any one -&#xd;
STP_FCPM_MAY08_V1_20240508093844')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3dc161c6-fbc3-435b-8553-a01b03e5e13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P75_RESULT_SET</value>
      <webElementGuid>06b2c023-f135-47a6-8eee-3a2723d18549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P75_RESULT_SET</value>
      <webElementGuid>1d1275a7-fde3-452a-b729-6cfc11e3c1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>38daa6cd-b039-42d5-823f-c4a7087963c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e755a3c-ed69-4b6e-bf8f-70fa5d305076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>304865f8-5d3e-45c8-a0a0-7ab15833fc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select any one -
STP_FCPM_MAY08_V1_20240508093844</value>
      <webElementGuid>95edd409-19bf-45c8-8b69-6741cfe4ca50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P75_RESULT_SET&quot;)</value>
      <webElementGuid>bb9c27b8-ef51-47b4-8892-1dc2ab08b4ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P75_RESULT_SET']</value>
      <webElementGuid>e4ede9e0-3420-4b79-8a71-a122a39fa88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P75_RESULT_SET_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>8e2099bc-c437-4308-9c9e-cbbfce1feb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>3d373b3c-fe01-4162-93cf-76cc6983026c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P75_RESULT_SET' and @name = 'P75_RESULT_SET' and (text() = '- Select any one -&#xd;
STP_FCPM_MAY08_V1_20240508093844' or . = '- Select any one -&#xd;
STP_FCPM_MAY08_V1_20240508093844')]</value>
      <webElementGuid>f80bb89d-fd0f-497f-9035-fd4ae022612e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
