<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Environment_P86_ENVIRONMENT (3)</name>
   <tag></tag>
   <elementGuidId>0f63e1e3-932a-4608-ae9d-8fb410d431c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P86_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P86_ENVIRONMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Environment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6b0dde0c-6d1f-4b5e-af6d-94a1ea5c7781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P86_ENVIRONMENT</value>
      <webElementGuid>54c574e9-b6ce-4299-8ba5-0788d046a3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P86_ENVIRONMENT</value>
      <webElementGuid>de03b08c-42be-454f-8b19-083065d17814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>1e07f7a2-9ddd-4910-885a-5d7031e45dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d66c682-62e2-4b63-a5eb-e7e0cb3b2679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cb98d93d-eac1-470e-87f9-a9ab066839ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P86_ENVIRONMENT');</value>
      <webElementGuid>b450febe-ea16-4961-af39-49101111b746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
McD_GRM_ENV
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
</value>
      <webElementGuid>fb5d4f42-ce6b-4433-bde7-5012c66a3c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P86_ENVIRONMENT&quot;)</value>
      <webElementGuid>97a40af9-447d-4e7d-8fe8-a543bc6eb1ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P86_ENVIRONMENT']</value>
      <webElementGuid>1ed8af9c-23ff-4467-bf1c-e578e8102138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P86_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>e8311198-4637-4918-a63d-4c77d262682a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>8a92e9f8-cd79-47b4-a8f2-a6c960ab0ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>d2231dc8-aa3a-4a5e-a9d5-676c9e3a2d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Name'])[1]/preceding::select[1]</value>
      <webElementGuid>7af30a1c-4b92-4bd2-891e-81a5f9086a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Totals'])[1]/preceding::select[2]</value>
      <webElementGuid>4032034a-298c-4b4a-b243-702ec8a7d3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6f411c76-b846-4874-876e-bf3252f6e283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P86_ENVIRONMENT' and @name = 'P86_ENVIRONMENT' and (text() = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
McD_GRM_ENV
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
' or . = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
McD_GRM_ENV
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
')]</value>
      <webElementGuid>24e66769-fd2b-4dbb-93c7-49e3be3b81fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
