<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Description (1) (1)</name>
   <tag></tag>
   <elementGuidId>10807eea-2457-4696-b78a-ed2e0fd5b630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P4_DESCRIPTION_LABEL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P4_DESCRIPTION_LABEL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b8d8b69a-229d-4a0d-b8f5-09d4e050855d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P4_DESCRIPTION</value>
      <webElementGuid>b503ebaa-ff90-4fa6-b12d-46ce770b39e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P4_DESCRIPTION_LABEL</value>
      <webElementGuid>bf82da3b-dfe4-417d-8b48-6dc3f5e050e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>3397c206-9453-4592-bc01-23658d8ee9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>f444c39f-6c97-48d9-921f-130bb686cbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P4_DESCRIPTION_LABEL&quot;)</value>
      <webElementGuid>ad425641-3cc3-4ce5-b5fb-6c49afa45be2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P4_DESCRIPTION_LABEL']</value>
      <webElementGuid>023ac608-6faf-4f86-acec-f7cde83b4a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P4_DESCRIPTION_CONTAINER']/div/label</value>
      <webElementGuid>9137d6d9-45ba-4bfa-bcbe-5d18f18eb172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label</value>
      <webElementGuid>33a38d58-118d-4e0e-add2-8c41e2f4100a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P4_DESCRIPTION_LABEL' and (text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>f0e78725-abd2-4361-84d5-2c70b8218e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
