<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_anandk1 (3)</name>
   <tag></tag>
   <elementGuidId>59ed6639-8a11-4a5f-abd9-d8f544b0d7a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = '
      anandk1
  ' or . = '
      anandk1
  ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#L14205299837764170</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; anandk1 &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ced4066-95e0-4778-a4a3-6b80be5a9041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button t-Button--header t-Button--navBar js-menuButton</value>
      <webElementGuid>73ea3cfa-76d6-486a-8c95-b9f77ff7770e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85942fc6-56f8-4477-85ea-80bbddff4b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L14205299837764170</value>
      <webElementGuid>1c71058a-16e1-4b26-93a8-342b0feee555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>menu_L14205299837764170</value>
      <webElementGuid>27cdcb9a-03d5-4fb5-aeee-25cae4b7e693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>bdcce3bf-4a5b-41d2-9da7-a9b47f739e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      anandk1
  </value>
      <webElementGuid>26d407c0-7cf5-46ca-b6dc-90c6facfa823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L14205299837764170&quot;)</value>
      <webElementGuid>e176f9bd-fafd-47d1-984d-f1cd3f66386b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
      anandk1
  ' or . = '
      anandk1
  ')]</value>
      <webElementGuid>585a7cd0-de49-4459-a74a-f78b2e5fdb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='L14205299837764170']</value>
      <webElementGuid>4d05f973-d47b-43cf-80e9-47857f2e9668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='14205299837764168']/li[2]/button</value>
      <webElementGuid>459d48fb-93be-4e28-8f7f-9c1f2b3dd5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[1]/following::button[1]</value>
      <webElementGuid>b82d786b-35fd-4cea-bd51-7dd21f2ebd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::button[1]</value>
      <webElementGuid>3c685e97-ac42-4abb-8f9e-1aebe1965c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>ad3d8fe2-44c5-4bd1-9719-450825a04995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
