<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_My Inbox_R163105974055422926_search_field (1)</name>
   <tag></tag>
   <elementGuidId>2bf77a6c-7118-4002-897e-60f55c162e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R163105974055422926_search_field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@title = 'Search Report' and @type = 'search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=searchbox[name=&quot;Search Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>037af748-418b-4772-9915-f9b775ec8ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-search-field</value>
      <webElementGuid>bbe6bdb4-5f72-4d6c-a8de-807df3e2a165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R163105974055422926_search_field</value>
      <webElementGuid>e1310e98-5909-4ece-8948-2d772d27fdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search Report</value>
      <webElementGuid>5b2ddea0-c07b-4286-adc0-b018dcb006aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7d3c470d-0fa3-4732-b432-7c12b08c4a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>aa6a6bf0-dd29-40e8-8794-881c6c831b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>6243f8d9-ec21-44ee-9f3b-cac30947bfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R163105974055422926_search_field&quot;)</value>
      <webElementGuid>632ad0f8-ebc7-4b91-983b-e2b6951f7a1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Search Report' and @type = 'search']</value>
      <webElementGuid>57bcd78a-c166-4da9-9aec-fca8c4a7e1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='R163105974055422926_search_field']</value>
      <webElementGuid>d9b391c1-67fd-4d4f-b7c4-52b85022fa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R163105974055422926_toolbar_controls']/div/div/div[2]/input</value>
      <webElementGuid>87d65a48-0ff4-4c2f-b9da-ccada3f4c0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>c40e3ec3-d33a-47aa-9edc-e4854e74790a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
