<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1</name>
   <tag></tag>
   <elementGuidId>70bf3aab-ed77-4ae4-bd17-11ee3fc3cd08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.oj-enabled.oj-hover.oj-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='oj-dp-6-0-5-0-0']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5aeb75a-621b-413c-8e17-1213ff4817e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4d5374d-ac6f-412f-b12b-230e161709f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-enabled oj-hover oj-focus</value>
      <webElementGuid>00e06d2b-43bb-46f2-a5b3-910461e23f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c84f304b-59d1-47d1-9104-85ef97f90c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>acd55d2c-d580-4978-8311-56bc78251f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6d641220-6b79-40ed-8a00-d756d5c191d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oj-dp-6-0-5-0-0&quot;)/a[@class=&quot;oj-enabled oj-hover oj-focus&quot;]</value>
      <webElementGuid>3de74601-4db5-45a8-a1ea-44b4836e0ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='oj-dp-6-0-5-0-0']/a</value>
      <webElementGuid>0ee98ae6-903a-43ef-9d8e-4c5ba4ebd784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1')]</value>
      <webElementGuid>f7d81416-4c6e-4750-815b-bb0f11400a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>ebe5b543-6471-4435-8e35-c8a9ff9737ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>6c10594c-4ed4-4f45-a785-36b9f04c53ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '1' or . = '1')]</value>
      <webElementGuid>ee302c24-ac7c-4179-9411-c093d2891503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
