<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_559_ObjectSet</name>
   <tag></tag>
   <elementGuidId>291bdb61-9152-4606-a0ab-e2c468c042c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.u-tL > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='214651878341441645_orig']/tbody/tr[2]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;559_ObjectSet&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b520afb-6c04-4b6c-939b-9aa1b7104ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1700:10:16236359163265:::10:P10_OBJECT_SET_ID:5774</value>
      <webElementGuid>59645706-43f7-4cce-8562-c31d8a260414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>559_ObjectSet</value>
      <webElementGuid>ff92e34a-ec55-43e2-96e1-ec001a5edf39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;214651878341441645_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>a6d7c91d-660a-4833-ae4c-10d8d0abe520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='214651878341441645_orig']/tbody/tr[2]/td/a</value>
      <webElementGuid>a561609a-d8ba-46ee-bdab-8d45e9f83f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'559_ObjectSet')]</value>
      <webElementGuid>d568bdfe-1a12-44ed-bdb5-203c995ad821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obj Set App Type'])[1]/following::a[10]</value>
      <webElementGuid>1c514eef-8f4a-4ae0-8461-fbd28a21ca08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated By'])[1]/following::a[11]</value>
      <webElementGuid>92799f37-4b35-459b-a453-7d778f0f6102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATALON_ADMIN'])[1]/preceding::a[1]</value>
      <webElementGuid>12dbae21-d15d-4732-a948-c39256df6c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN'])[1]/preceding::a[1]</value>
      <webElementGuid>10973ea5-0ef1-460d-9053-d03d2fcd7a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1700:10:16236359163265:::10:P10_OBJECT_SET_ID:5774')]</value>
      <webElementGuid>f0a1f6d0-1049-46b9-b5e9-4a86be2c6bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>6f4efaf6-a841-464d-9870-d6ce432c7ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1700:10:16236359163265:::10:P10_OBJECT_SET_ID:5774' and (text() = '559_ObjectSet' or . = '559_ObjectSet')]</value>
      <webElementGuid>ff936f92-0b28-46a4-97d3-abf65409224b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
