<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_-_apex-edit-page_5</name>
   <tag></tag>
   <elementGuidId>b18b764c-3021-4def-ad89-880e06127548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(8) > td.u-tR > a > img.apex-edit-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='242004625601843036']/tbody/tr[8]/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;SAPActivitySet4a SAPActivitySet4 A31008 06-NOV-25 KATADMIN 06-NOV-25 KATADMIN 06-NOV-25 -&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>62a9e5ea-e19e-459a-82ec-6b8ad0a8a6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/i/app_ui/img/icons/apex-edit-page.png</value>
      <webElementGuid>d79df429-0e62-473e-a599-2869eb475aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-edit-page</value>
      <webElementGuid>79583fd9-889b-4eb6-b4fb-88ec65a5cd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;242004625601843036&quot;)/tbody[1]/tr[8]/td[@class=&quot;u-tR&quot;]/a[1]/img[@class=&quot;apex-edit-page&quot;]</value>
      <webElementGuid>be27cce5-23cd-4ee2-a13c-37b371ca4aa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='242004625601843036']/tbody/tr[8]/td/a/img</value>
      <webElementGuid>ab309621-8275-4238-ae3d-34fc0c0a2f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a/img</value>
      <webElementGuid>8783b09d-3271-493c-aa33-a28d1f33a3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/i/app_ui/img/icons/apex-edit-page.png']</value>
      <webElementGuid>ffb21cc0-fe32-4d0c-8933-917d04d3dc1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
