<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dashboard_a-TreeView-toggle (1)</name>
   <tag></tag>
   <elementGuidId>1de5b99b-21a9-4346-99d5-bf2b1ab57902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_11 > span.a-TreeView-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_11']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=/^Analytics$/ >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2e57733-6eb1-4e2e-81b9-50b8d2bcd79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>1554a477-eab0-4853-bba0-bf364826ce7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_11&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>de983fce-bf02-45ce-ab36-cb6fb3e2f3c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_11']/span</value>
      <webElementGuid>11f9c94b-caa5-4b2b-8316-15af776203cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/span</value>
      <webElementGuid>68ceca94-7da3-428b-9f22-c140207171c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
