<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Analytics_a-TreeView-toggle (2)</name>
   <tag></tag>
   <elementGuidId>e18d8aec-d4aa-49dc-8c7e-be005d96ca36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_18 > span.a-TreeView-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_18']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=/^Violation Report$/ >> span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9b8d61b-c2d0-4d12-9bc1-ec4ed2ebd903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>b50ea03e-427c-4561-8372-286d7b6feac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_18&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>f6e0d3bb-e360-4924-b305-f24d9e010269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_18']/span</value>
      <webElementGuid>b8617582-a768-4cff-816b-88c8d3c63ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/span</value>
      <webElementGuid>d40a232d-0c16-491d-9f63-56e41733d8b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
