<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_STP_FCPM_MAY08_V1_20240508093844-1</name>
   <tag></tag>
   <elementGuidId>ae74cc42-0fc3-4166-beff-f3cd35f8651a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R176258973591708826_col_values_drop']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-IRR-col-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8fd4d48-1fbd-4535-9192-560aba9efd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4dfd2054-3f37-41a0-b4af-713a1aeaf755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-col-value</value>
      <webElementGuid>8fbca2fd-1033-414f-9a7b-c04d55138be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-return-value</name>
      <type>Main</type>
      <value>STP_FCPM_MAY08_V1_20240508093844-1</value>
      <webElementGuid>3b08ca0f-5158-4191-9428-c9e543b21fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STP_FCPM_MAY08_V1_20240508093844-1</value>
      <webElementGuid>26d0f509-77e4-491f-8d78-e8ea1779662c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R176258973591708826_col_values_drop&quot;)/a[@class=&quot;a-IRR-col-value&quot;]</value>
      <webElementGuid>e58a8289-2f65-482d-8c0f-e09dff703797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R176258973591708826_col_values_drop']/a</value>
      <webElementGuid>baaa1e62-2929-4181-aab6-51f06b74c42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'STP_FCPM_MAY08_V1_20240508093844-1')]</value>
      <webElementGuid>92311717-43b1-45cf-90f6-d2d5eb17889b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[113]</value>
      <webElementGuid>f40d53e9-6553-485a-9468-3fd8bb551f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html/div/a</value>
      <webElementGuid>0b84c079-68f8-407c-9ca3-ee054f656b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'STP_FCPM_MAY08_V1_20240508093844-1' or . = 'STP_FCPM_MAY08_V1_20240508093844-1')]</value>
      <webElementGuid>4cbbd090-b68f-48ee-b563-d4a1ff49e534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
