<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Last Update Date_apex-edit-pencil (1)</name>
   <tag></tag>
   <elementGuidId>19063f56-045a-4daf-86ab-d03a2fbe9d32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='145986447318658187_orig']/tbody/tr[2]/td/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.apex-edit-pencil</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Admin We Amajul - Alexis Majul Katalon_Admin - Katalon Admin User Katalon_Admin - Katalon Admin User Amajul - Alexis Majul KATALON_ADMIN 30-OCT-25 KATALON_ADMIN 30-OCT-25&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd47f97e-76ec-4fc8-b7a9-aa68cbcbee92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/i/app_ui/img/icons/apex-edit-pencil.png</value>
      <webElementGuid>25f230a5-67d8-4c98-b26f-7138228211a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-edit-pencil</value>
      <webElementGuid>d1378c61-aac1-4d54-a89e-101fa3e512fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;145986447318658187_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]/img[@class=&quot;apex-edit-pencil&quot;]</value>
      <webElementGuid>0e58e2f0-bcad-400e-903a-890f191f57fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='145986447318658187_orig']/tbody/tr[2]/td/a/img</value>
      <webElementGuid>9962a16b-e2f9-4953-92d6-88f039f5ae19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>9fa6ffe6-5f95-4c08-bfc1-eb82a5b2b873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/i/app_ui/img/icons/apex-edit-pencil.png']</value>
      <webElementGuid>3da8cea5-cf40-4baa-b8fa-dbe3eb3b865d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
