<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>e2599de5-d826-4fb3-b37f-25fe510a9d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P8_NOTE_CONTAINER']/div[2]/div/span/b/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Violation check in progress, the Submit Access button will be enabled upon compl&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2d4690d8-ee50-4193-a002-d0693a742bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Violation check in progress, the Submit Access button will be enabled upon completion and click on Refresh button.</value>
      <webElementGuid>31f377f6-225a-4880-9cab-a788b15db079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_NOTE_CONTAINER&quot;)/div[@class=&quot;t-Form-inputContainer col col-10&quot;]/div[@class=&quot;t-Form-itemWrapper&quot;]/span[@class=&quot;t-Form-itemText t-Form-itemText--pre&quot;]/b[1]/p[1]</value>
      <webElementGuid>4e63ae36-b855-4e57-8a64-485b258c0127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P8_NOTE_CONTAINER']/div[2]/div/span/b/p</value>
      <webElementGuid>a7507942-d93c-4a1a-a37e-47008fd53005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::p[1]</value>
      <webElementGuid>a08262cb-5be9-46e2-9843-0af6966db38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 4 of 4 - Violations Review'])[1]/following::p[1]</value>
      <webElementGuid>4ac342d0-4ee2-4134-892a-6a270afe6dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::p[1]</value>
      <webElementGuid>a3ab295b-2b9c-49dd-89f8-56f410c95207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::p[1]</value>
      <webElementGuid>299fb63c-c30b-4a15-ab9c-a034974a0dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Violation check in progress, the Submit Access button will be enabled upon completion and click on Refresh button.']/parent::*</value>
      <webElementGuid>f971ffb5-a987-42b8-beac-5bb85f31be7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9ea6ac15-0e89-4616-aee0-912a2bf217b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Violation check in progress, the Submit Access button will be enabled upon completion and click on Refresh button.' or . = 'Violation check in progress, the Submit Access button will be enabled upon completion and click on Refresh button.')]</value>
      <webElementGuid>4a54e776-b63a-4581-9ed6-abf9d1045f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
