<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_katalon_admin</name>
   <tag></tag>
   <elementGuidId>0db8cafb-9156-43df-a207-0a769dac630a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L14205299837764170</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='L14205299837764170']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0647ee62-9319-4047-9dd6-224da61c799a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button t-Button--header t-Button--navBar js-menuButton</value>
      <webElementGuid>0ed871a1-0d6e-4992-94e0-60e2ef525947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ced94e91-daba-40cc-b931-e59ad204ede8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L14205299837764170</value>
      <webElementGuid>f0cd05ae-49ae-46ee-b237-57b4bbbabb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>menu_L14205299837764170</value>
      <webElementGuid>c7da9de7-b24f-4fa1-93d7-874d14fd4059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>822fb1ae-e433-4c42-bc36-c675df449659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      katalon_admin
  </value>
      <webElementGuid>81623dc1-3d29-41fa-a5f0-5b1f77512e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L14205299837764170&quot;)</value>
      <webElementGuid>492ac7da-8dbc-49a4-ac2a-01e267fb3035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='L14205299837764170']</value>
      <webElementGuid>dec49562-22d5-43bb-801e-7dce0657c009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='14205299837764168']/li[2]/button</value>
      <webElementGuid>53399a00-ec4c-4e7f-b3de-9625545183db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>f7fd1ae3-924c-4f2d-8faa-1d72ae72f071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'L14205299837764170' and (text() = '
      katalon_admin
  ' or . = '
      katalon_admin
  ')]</value>
      <webElementGuid>fd1ac828-b9d9-4f16-a7a7-695ab9e7545d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
