<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Name</name>
   <tag></tag>
   <elementGuidId>4532b45a-a02f-43e7-b3d6-954200a81fe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P18_ENVIRONMENT_NAME_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P18_ENVIRONMENT_NAME_LABEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6e2e5377-edc9-4219-ac6e-bc659b689100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P18_ENVIRONMENT_NAME</value>
      <webElementGuid>45f29fef-1966-467a-97fe-4eaabd1fc691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P18_ENVIRONMENT_NAME_LABEL</value>
      <webElementGuid>6377b86e-e80d-4610-83f9-366f95d42430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>97e88db3-4ce4-4f0e-a6d4-6f35b52b9386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>c2769391-164d-49ce-9676-dc6c9e1105da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P18_ENVIRONMENT_NAME_LABEL&quot;)</value>
      <webElementGuid>0d973ab8-ae18-46dd-88ff-84087a314acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P18_ENVIRONMENT_NAME_LABEL']</value>
      <webElementGuid>165c750d-9ce3-4b02-9299-63ceb1e97288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P18_ENVIRONMENT_NAME_CONTAINER']/div/label</value>
      <webElementGuid>649701f9-df5b-413d-b410-8353b19669b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::label[1]</value>
      <webElementGuid>8f985dd6-80a2-4408-8e22-69c53df95b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::label[1]</value>
      <webElementGuid>b7155f01-e443-4577-8239-682e191284e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[1]/preceding::label[1]</value>
      <webElementGuid>ee555c9b-5633-430e-b3c1-3cc15b82c5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/preceding::label[2]</value>
      <webElementGuid>e158722e-1165-4c21-8c18-19de1b3ac327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name']/parent::*</value>
      <webElementGuid>b95f1875-d202-490f-82ec-892109b3dc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>a1cbc211-787b-4a58-84d7-d7b18123a068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P18_ENVIRONMENT_NAME_LABEL' and (text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>3c679c7e-ede5-49db-9888-f8c70a30e4ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
