<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Attribute_KTLNAttributes-DTP701Entry_9d1214</name>
   <tag></tag>
   <elementGuidId>2cbedeee-342f-46d2-a345-fdd47b85d9ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;f04&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='f04']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5101ace7-3c70-45e6-bca5-078998dca9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f04</value>
      <webElementGuid>b96244c1-992c-4b52-87ab-987176756775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>objectIdReport</value>
      <webElementGuid>3db86b6a-4355-47be-bb78-0cd5ac27ef61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seqid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>66d5e775-bdec-44ac-90e7-304046ef0e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attrnum</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>52030264-9a2d-4b2c-9b61-96da94e376d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>%Attribute_KTLNAttributes-DTP701EntryAttribute_KTLNEntryPrivileges_KTLNEntryRoles_KTLNTESTUserEntryAttribute_KTLNUserEntry_KTLNUsers_KTLN</value>
      <webElementGuid>9b8251ec-1419-44b1-af3f-540b02e16465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_secObjReport&quot;)/div[@class=&quot;t-Report-wrap&quot;]/div[@class=&quot;t-Report-tableWrap&quot;]/table[@class=&quot;t-Report-report&quot;]/tbody[1]/tr[1]/td[@class=&quot;t-Report-cell&quot;]/select[@class=&quot;objectIdReport&quot;]</value>
      <webElementGuid>517ec165-1a11-4d9a-bf54-a4de7356d11f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='f04']</value>
      <webElementGuid>e145beee-bbe0-4e2b-af8b-b23147e03e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_secObjReport']/div/div/table/tbody/tr/td[3]/select</value>
      <webElementGuid>0850e94d-566f-49c9-a8c3-6c435316634d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::select[1]</value>
      <webElementGuid>5e784a9e-396d-4a7a-97a9-56af8ba38030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated By'])[1]/following::select[1]</value>
      <webElementGuid>e4d47d0f-c16a-4bf9-a025-0398f11f1b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USERS'])[1]/preceding::select[1]</value>
      <webElementGuid>87656e5b-2b24-4769-b7c8-e9937bfa733d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::select[1]</value>
      <webElementGuid>5a63da4b-ee87-44ee-a8f3-3e99ca5e8b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/table/tbody/tr/td[3]/select</value>
      <webElementGuid>8324595d-d46d-4e6a-8d08-730f096f9b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'f04' and (text() = '%Attribute_KTLNAttributes-DTP701EntryAttribute_KTLNEntryPrivileges_KTLNEntryRoles_KTLNTESTUserEntryAttribute_KTLNUserEntry_KTLNUsers_KTLN' or . = '%Attribute_KTLNAttributes-DTP701EntryAttribute_KTLNEntryPrivileges_KTLNEntryRoles_KTLNTESTUserEntryAttribute_KTLNUserEntry_KTLNUsers_KTLN')]</value>
      <webElementGuid>910eebb7-6b74-4410-af9e-ca09472b6edb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
