<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Local File Data Type</name>
   <tag></tag>
   <elementGuidId>cdbe54ed-f078-474a-9ba6-b6b2603a58d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P10_FILE_TYPE_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Local File Data Type' or . = 'Local File Data Type')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f8ce96e0-1f6d-451c-9955-0b8697d5fa0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P10_FILE_TYPE</value>
      <webElementGuid>cb593861-aeed-4ee7-bd03-0f8b35f160f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_FILE_TYPE_LABEL</value>
      <webElementGuid>71b7dcd4-4541-4641-98a7-96ef8a67a0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>9034f7d5-45f1-48ae-a25c-8bc61871fc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Local File Data Type</value>
      <webElementGuid>17afea6a-ad00-4568-ae11-446eb1aac3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_FILE_TYPE_LABEL&quot;)</value>
      <webElementGuid>470554d5-533b-4d19-ac77-57b5f905b5f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Local File Data Type' or . = 'Local File Data Type')]</value>
      <webElementGuid>78df567d-f157-4fb0-bc70-731132dcaacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P10_FILE_TYPE_LABEL']</value>
      <webElementGuid>4075f0dc-ed6a-4a1d-b203-e5fd087d3875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_FILE_TYPE_CONTAINER']/div/label</value>
      <webElementGuid>6ea02567-8573-4e68-a75c-0b456ca3db7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Existing Object'])[1]/following::label[1]</value>
      <webElementGuid>77d60aa6-8eb8-4781-ac40-24882f345b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local File'])[1]/following::label[2]</value>
      <webElementGuid>e2ea8347-2055-41bb-be48-33e5986ed71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XML'])[1]/preceding::label[1]</value>
      <webElementGuid>615fc443-5bc5-439f-90e1-2c611701f9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[1]/preceding::label[2]</value>
      <webElementGuid>849ecf34-7ec5-40ff-9f0e-fc2467242311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Local File Data Type']/parent::*</value>
      <webElementGuid>57bcc020-8de9-4702-ab13-a354c73d4d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/label</value>
      <webElementGuid>4b42fc38-ea68-4f3e-8052-0d972c00239a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
