<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonP35_RULE_TAGS_MOVE</name>
   <tag></tag>
   <elementGuidId>68564d0e-7119-411b-a878-95b26a73a11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'P35_RULE_TAGS_MOVE' and @type = 'button' and @title = 'Move']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[1]/div[2]/div[2]/div[2]/div[2]/div[1]/div/div/div[2]/div[2]/div/div[4]/div/div/div[2]/div/div/table/tbody/tr/td[2]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P35_RULE_TAGS_MOVE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af5e9072-9219-400a-9a96-367befb79f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P35_RULE_TAGS_MOVE</value>
      <webElementGuid>92f9a246-f59b-43fc-be7d-bd271d6e5a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--noLabel a-Button--withIcon a-Button--small a-Button--noUI a-Button--shuttle</value>
      <webElementGuid>53ce3fb3-cf3c-4fb3-9e46-8447b9c9506f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6887d57-62ef-404a-a969-8cc99eedef1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>15740e9e-4ccf-454b-85be-7ae0fe4bc758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>4569285d-abcb-4547-a97a-6d363b2b7a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P35_RULE_TAGS_MOVE&quot;)</value>
      <webElementGuid>ca8622c6-12a5-408c-8120-bbf5f1d27022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P35_RULE_TAGS_MOVE']</value>
      <webElementGuid>8b52d0f8-a5f2-4772-98aa-1b847a9ca2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P35_RULE_TAGS']/table/tbody/tr/td[2]/button[3]</value>
      <webElementGuid>47843f8c-c1d7-4a55-809e-09cbd0a13a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>d4ad85c0-66a3-416e-8db1-63d6729393a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'P35_RULE_TAGS_MOVE' and @type = 'button' and @title = 'Move']</value>
      <webElementGuid>ddc9fc09-df0f-4e92-8f22-b95f4994ab94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
