<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select any oneCERP_1CloudERPEBizApp__fcbf94</name>
   <tag></tag>
   <elementGuidId>1edc4ae4-3d78-4dee-ba86-2cfebb337c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P0_ENVIRONMENT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c5e32958-f991-4a23-ae6e-e387ca73d981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>2306ba46-b26b-4975-bbce-058b7c209293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>dcca0b34-54c8-4bc4-953a-7ac4693b25d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>fd548c68-2220-48b0-92e2-2e8e45e9c444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5add573-c9f0-4b51-a7a9-fe2df227f8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2174924f-453e-4baf-8926-4541d3667923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P0_ENVIRONMENT');</value>
      <webElementGuid>e580b53c-cd18-46a9-a752-c037b5eb8c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
CERP_1
CloudERP
EBizApp_JDBC_Env
KTLN_CloudERP
McD_GRM_ENV
SFP304T
SailPoint_ENV2
SailPoint_Env
TririgaDB_Env
</value>
      <webElementGuid>8ffe5866-7102-4415-987b-bc7e71433b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT&quot;)</value>
      <webElementGuid>43cf6a17-9a93-48bd-a014-6f53691c9e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P0_ENVIRONMENT']</value>
      <webElementGuid>fba61dda-d64e-4b6c-95fd-e57556bedd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>8c2f9e15-462f-49a1-9e5a-c25f521b3b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e162fd54-73d7-4436-91b5-1f258b463b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P0_ENVIRONMENT' and @name = 'P0_ENVIRONMENT' and (text() = 'Select any one
CERP_1
CloudERP
EBizApp_JDBC_Env
KTLN_CloudERP
McD_GRM_ENV
SFP304T
SailPoint_ENV2
SailPoint_Env
TririgaDB_Env
' or . = 'Select any one
CERP_1
CloudERP
EBizApp_JDBC_Env
KTLN_CloudERP
McD_GRM_ENV
SFP304T
SailPoint_ENV2
SailPoint_Env
TririgaDB_Env
')]</value>
      <webElementGuid>ff15e0de-cc86-4f8b-9324-648666677a8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
