<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter</name>
   <tag></tag>
   <elementGuidId>40178811-a13d-4559-92cb-fbfda1723730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R137674426230792379_actions_menu_2i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R137674426230792379_actions_menu_2i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6530104f-6786-4b55-a416-fc154eb32bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00650454-3b57-4303-98e9-4bc3b71ee347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R137674426230792379_actions_menu_2i</value>
      <webElementGuid>ac2e378c-cd0e-496b-ad1c-c749cea2b535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>411f25f0-78ec-4ea3-88cc-a90c0aa253f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>f3639408-4829-4caf-b173-93a92d498f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>066ab5e1-4148-419c-8e1e-571a0926df2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R137674426230792379_actions_menu_2i&quot;)</value>
      <webElementGuid>96ebfafe-6bc6-492d-8776-2e712b2a4f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R137674426230792379_actions_menu_2i']</value>
      <webElementGuid>23d0a7b4-63e6-4d25-b7cf-07195b40ec4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='R137674426230792379_actions_menu_2']/div/span/button</value>
      <webElementGuid>8a220e5c-6577-4f79-8208-5a23fb0131e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/button</value>
      <webElementGuid>46cd147e-9380-404d-8d2c-c5b289b154ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'R137674426230792379_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>f2c1ca2e-fe53-4eec-bafa-2135d5c20a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
