<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actions_1</name>
   <tag></tag>
   <elementGuidId>fc107813-985d-4534-9314-189795e5ca91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R409135957861231789_ig_toolbar_actions_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R409135957861231789_ig_toolbar_actions_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c7834ce-d6ce-4236-a7af-337e72ddcc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b72adf7b-d74c-4a99-bf24-39424d1b38db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Toolbar-item</value>
      <webElementGuid>38425ee5-c6ac-47d3-8939-9cde2ebfe5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R409135957861231789_ig_toolbar_actions_button</value>
      <webElementGuid>ed1cc207-386f-4b20-ab24-d4d84fb52132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>R409135957861231789_ig_toolbar_actions_button_menu</value>
      <webElementGuid>289c351a-17fe-4268-8296-c8ba63db52e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18c99b41-9e47-4963-b96c-e7a5f2f6f75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>48891d45-e4b5-4691-a13f-326228499b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>625fd173-3394-40bd-9192-4cddc77a7338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R409135957861231789_ig_toolbar_actions_button&quot;)</value>
      <webElementGuid>b5d9bbd8-c819-45c0-88a7-444a31a30fa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R409135957861231789_ig_toolbar_actions_button']</value>
      <webElementGuid>db0f344a-a5e2-4d19-8c7d-e62395a81679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R409135957861231789_ig_toolbar']/div/div[4]/button</value>
      <webElementGuid>69b42255-bfb2-41b5-b71a-eb800539d907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[3]/div/div/div[4]/button</value>
      <webElementGuid>23a4868e-e501-4f6a-a084-1086353fcd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'R409135957861231789_ig_toolbar_actions_button' and (text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>e99a863f-6ce2-421e-8105-7b6d9bd8d998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
