<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Role GroupDescriptionRolePrimary own_473961</name>
   <tag></tag>
   <elementGuidId>61f77a5b-3fb9-490a-bd20-2e60134538e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R570861162460345007_column_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='R570861162460345007_column_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>51fd1416-a0cc-4973-bc3b-18fa6dae69f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R570861162460345007_column_name</value>
      <webElementGuid>eae58ce1-6f33-410d-bb22-c89faf530da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>0d72fa09-6917-415a-bed3-a7fe7eff2a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>961d8bb0-cbf6-4d00-b8a6-daf1673973b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>150c66fd-f4e0-4e64-b920-b8d147c58fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>588fc244-180f-460a-8e98-63c7ba9b3418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role GroupDescriptionRolePrimary ownerSecondary ownerCreated byCreation dateLast update dateLast updated by</value>
      <webElementGuid>22c29770-c513-4f29-8704-bd933104ebab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R570861162460345007_column_name&quot;)</value>
      <webElementGuid>7230f0b1-ea6f-4b0c-8614-e5f408955577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='R570861162460345007_column_name']</value>
      <webElementGuid>85c9d29d-b391-4512-b00b-b7b7f666d7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R570861162460345007_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>cecab4f0-263c-41fa-b45c-3abf73c6d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/select</value>
      <webElementGuid>61c23501-1020-4b3b-af1e-336c382d626d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'R570861162460345007_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'Role GroupDescriptionRolePrimary ownerSecondary ownerCreated byCreation dateLast update dateLast updated by' or . = 'Role GroupDescriptionRolePrimary ownerSecondary ownerCreated byCreation dateLast update dateLast updated by')]</value>
      <webElementGuid>6fff6518-97bf-48b5-82fe-85759d9ebc22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
