<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_RoleGroup_AR</name>
   <tag></tag>
   <elementGuidId>2405b711-93b3-4f16-9980-fe4f8be87fce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'RoleGroup_AR' or . = 'RoleGroup_AR')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.t-Report-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'RoleGroup_AR' or . = 'RoleGroup_AR')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>258c9ecb-4b1b-40b6-b383-e7efae0849e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Report-cell</value>
      <webElementGuid>bea422c3-1392-495d-83cc-8d10cdf68d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>APPLICATION_NAME</value>
      <webElementGuid>fa684bdc-4389-43fa-8e1c-89f363562c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RoleGroup_AR</value>
      <webElementGuid>bc013221-99af-4ae9-8613-a8a63b944934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_R407297060702584727&quot;)/div[@class=&quot;t-Report-wrap&quot;]/div[@class=&quot;t-Report-tableWrap&quot;]/table[@class=&quot;t-Report-report&quot;]/tbody[1]/tr[3]/td[@class=&quot;t-Report-cell&quot;]</value>
      <webElementGuid>4b9d999b-c1dd-4a11-a63e-91949e6cb624</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_R407297060702584727']/div/div/table/tbody/tr[3]/td</value>
      <webElementGuid>4c61047c-5ca2-43fe-b5d2-960f2494ae4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td</value>
      <webElementGuid>754ceb6b-2586-47db-a021-110efd32006e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'RoleGroup_AR' or . = 'RoleGroup_AR')]</value>
      <webElementGuid>04728f0a-d533-4d4b-8f2e-56855dbc1ea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
