<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Attribute_KTLNAttributes-DTP701EntryAttribute_KTLNEntryHierarchy_KTLNEntryPrivileges_KTLNEntryRoles_KTLNUserEntryAttribute_KTLNUserEntry_KTLNUsers_KTLN_USERENTRYATTRIBUTE</name>
   <tag></tag>
   <elementGuidId>0729e384-4fe7-44e2-bad3-df64af342773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='User Entry Attribute'])[1]/following::select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0e09185f-e085-4fae-b7b4-8b1ae300c6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f04</value>
      <webElementGuid>5c65df6b-b86c-4b50-b1d6-452e3f854fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>objectIdReport</value>
      <webElementGuid>03e080a6-32a0-4463-938c-259ee355a742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seqid</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2c347792-0c90-4d10-9c47-eba50e1adad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attrnum</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7ac7a597-0433-4437-ba43-f02628967ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>%Attribute_KTLNAttributes-DTP701EntryAttribute_KTLNEntryHierarchy_KTLNEntryPrivileges_KTLNEntryRoles_KTLNUserEntryAttribute_KTLNUserEntry_KTLNUsers_KTLN</value>
      <webElementGuid>26edd627-251c-472a-bd2c-39130df3764d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_secObjReport&quot;)/div[@class=&quot;t-Report-wrap&quot;]/div[@class=&quot;t-Report-tableWrap&quot;]/table[@class=&quot;t-Report-report&quot;]/tbody[1]/tr[10]/td[@class=&quot;t-Report-cell&quot;]/select[@class=&quot;objectIdReport&quot;]</value>
      <webElementGuid>53122f7f-2c67-4bd3-bd1d-be09a010bd1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@name='f04'])[10]</value>
      <webElementGuid>fe11fc0f-0a0a-4932-9c6b-523cb7fc33cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_secObjReport']/div/div/table/tbody/tr[10]/td[3]/select</value>
      <webElementGuid>a05a0b8d-d1b6-451d-a948-9a912a2ccf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Entry Attribute'])[1]/following::select[1]</value>
      <webElementGuid>da1eb557-7d87-43a5-bcf5-65d55d6774d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATALON_ADMIN'])[18]/following::select[1]</value>
      <webElementGuid>f9b964f3-3f52-4d3c-b900-e3ab9628b29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER_ENTRY_ATTRIBUTE'])[1]/preceding::select[1]</value>
      <webElementGuid>8e0901ad-d74c-4b22-83d9-ac85d0609591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATALON_ADMIN'])[19]/preceding::select[1]</value>
      <webElementGuid>ed92d5bd-d964-452c-8a31-c7a95572ef11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[3]/select</value>
      <webElementGuid>198edefc-4fd3-4d6e-839a-bb6f7b4387ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'f04' and (text() = '%Attribute_KTLNAttributes-DTP701EntryAttribute_KTLNEntryHierarchy_KTLNEntryPrivileges_KTLNEntryRoles_KTLNUserEntryAttribute_KTLNUserEntry_KTLNUsers_KTLN' or . = '%Attribute_KTLNAttributes-DTP701EntryAttribute_KTLNEntryHierarchy_KTLNEntryPrivileges_KTLNEntryRoles_KTLNUserEntryAttribute_KTLNUserEntry_KTLNUsers_KTLN')]</value>
      <webElementGuid>9efb4d2f-cbf8-4091-93dc-0d3c9144f993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
