<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Environment</name>
   <tag></tag>
   <elementGuidId>724c3e51-3190-431a-b142-f251f120da63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P0_ENVIRONMENT_LABEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>424157fb-ad89-4444-9a83-8f88b0db05d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>e7a0073d-2490-4b3d-96e6-fb8676124dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT_LABEL</value>
      <webElementGuid>fdd9b24a-0141-4eac-9ea9-c316c4d66242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>bfbd647a-bf07-478a-a649-fc6f525e0d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Environment</value>
      <webElementGuid>ddec42d4-7f11-4a27-b8b4-46b1de74578a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT_LABEL&quot;)</value>
      <webElementGuid>dd9b0edd-5d64-4784-aabd-97f0936bcd45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P0_ENVIRONMENT_LABEL']</value>
      <webElementGuid>22c88bb5-1ee2-4513-b92b-772f457d3bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div/label</value>
      <webElementGuid>2fe33473-35a5-400f-8648-5247597ae53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::label[1]</value>
      <webElementGuid>68dafa77-ea5a-4e50-98d0-e58570402c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Listing and Access'])[1]/following::label[1]</value>
      <webElementGuid>ef5352e4-253d-46e2-b1d9-82acb5296687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Listing'])[3]/preceding::label[1]</value>
      <webElementGuid>9eb542fc-06ea-43c3-ad71-bc9852fdd93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::label[1]</value>
      <webElementGuid>ec70f928-bfbf-4c95-b435-19cab3aad38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Environment']/parent::*</value>
      <webElementGuid>3cef558c-8d45-43b2-af8e-eff4c89f39f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>b3751563-d1c9-4b8b-91fd-973bd3f19b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P0_ENVIRONMENT_LABEL' and (text() = 'Environment' or . = 'Environment')]</value>
      <webElementGuid>6e6f9b5d-bfdb-4cb3-9fb4-c6ad6fa5f75c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
