<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select an Environment -Coupa_Env1E_696603 (1)</name>
   <tag></tag>
   <elementGuidId>61519465-ab18-4e76-8e22-59621bcc4c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P100_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P100_ENVIRONMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Environment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4b8607d-359c-4328-a57a-f0307a78594d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P100_ENVIRONMENT</value>
      <webElementGuid>845a0723-12d0-4e90-bd22-8cee08ced149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P100_ENVIRONMENT</value>
      <webElementGuid>3954b300-854d-4607-b846-07357c49b027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>c8e2806a-2b15-4e6d-8c37-473cb3d445d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>abfc1aaf-da38-4bb1-9c37-f38d80fdfee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2a20ddc9-ada3-4192-8178-dd2d770db60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P100_ENVIRONMENT');</value>
      <webElementGuid>7299de3c-d5a3-45af-8779-2fe1fd249514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select an Environment -
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
Kyriba_Env1
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SailPoint_ENV2
SailPoint_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment3_Hybris
Test_Environment4_CloudERP
Tririga_Env
Tririga_OS
WorkDayEnv_3
WorkDay_Env
Y_Endur
Z1639_NEv1
Z_1639_BUG_eNv
Z_Coupav2
Z_EBS_TestEnv.
Z_KAT_Automated1560
ZtestCoupa2
</value>
      <webElementGuid>ce2210ef-4b6d-44bc-b889-47fcd7a68bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P100_ENVIRONMENT&quot;)</value>
      <webElementGuid>1353d6fa-782a-4284-90e2-c1731a91cc5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P100_ENVIRONMENT']</value>
      <webElementGuid>fb22c454-f993-4723-b1a1-97c6c8cbb442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P100_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>427ae162-138f-451c-b0d8-f9c31e369dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>432a59c1-0c4c-49e9-bb5a-02c11f8ac4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>9b81f36a-270b-47bb-99d0-e29f67d4dccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objects'])[1]/preceding::select[1]</value>
      <webElementGuid>d6ddc097-298e-4df3-86de-cc9e54fe8192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Objects ADM'])[1]/preceding::select[1]</value>
      <webElementGuid>efded899-65fb-4117-99a2-a3408e57ffa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3bcdc3bc-c6fe-44e2-aef8-d32a96988b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P100_ENVIRONMENT' and @name = 'P100_ENVIRONMENT' and (text() = '- Select an Environment -
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
Kyriba_Env1
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SailPoint_ENV2
SailPoint_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment3_Hybris
Test_Environment4_CloudERP
Tririga_Env
Tririga_OS
WorkDayEnv_3
WorkDay_Env
Y_Endur
Z1639_NEv1
Z_1639_BUG_eNv
Z_Coupav2
Z_EBS_TestEnv.
Z_KAT_Automated1560
ZtestCoupa2
' or . = '- Select an Environment -
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
Kyriba_Env1
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SailPoint_ENV2
SailPoint_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment3_Hybris
Test_Environment4_CloudERP
Tririga_Env
Tririga_OS
WorkDayEnv_3
WorkDay_Env
Y_Endur
Z1639_NEv1
Z_1639_BUG_eNv
Z_Coupav2
Z_EBS_TestEnv.
Z_KAT_Automated1560
ZtestCoupa2
')]</value>
      <webElementGuid>4d2bb8ae-0825-423e-93a3-78c40249a373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
