<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EBizApp_JDBC_Env</name>
   <tag></tag>
   <elementGuidId>7e984cc8-3a74-4ba8-a5bc-2d1ef8addaf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.popup-lov-highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupLov_2_P0_ENVIRONMENT_dlg']/div[3]/div/div[3]/ul/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;EBizApp_JDBC_Env&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31749cf7-1fbe-4cf8-bf87-c0340d386fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-lov-highlight</value>
      <webElementGuid>f60042ec-8db8-4628-b393-d42b0aef2ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EBizApp_JDBC_Env</value>
      <webElementGuid>7cd67975-f2b8-4725-8e1d-b60b0ec1a633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupLov_2_P0_ENVIRONMENT_dlg&quot;)/div[@class=&quot;a-PopupLOV-results a-TMV js-no-select&quot;]/div[@class=&quot;a-TMV-body&quot;]/div[@class=&quot;a-TMV-w-scroll&quot;]/ul[@class=&quot;a-IconList&quot;]/li[@class=&quot;a-IconList-item&quot;]/span[@class=&quot;popup-lov-highlight&quot;]</value>
      <webElementGuid>5fd2eb75-ce83-45b1-a640-1bf446b20007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupLov_2_P0_ENVIRONMENT_dlg']/div[3]/div/div[3]/ul/li/span</value>
      <webElementGuid>44404e33-e93b-4dba-a817-0c23d01392f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presented in 1 rows'])[1]/following::span[1]</value>
      <webElementGuid>8d33449a-883f-4665-ad05-faebec86bf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/following::span[4]</value>
      <webElementGuid>59713ff2-c60f-45f4-8544-b539a65ee73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/preceding::span[1]</value>
      <webElementGuid>142e073d-1e7e-454d-a344-aedf69bcdf40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EBizApp_JDBC_Env']/parent::*</value>
      <webElementGuid>a4f1140e-36b7-4eda-bc7e-0da75fa60948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/span</value>
      <webElementGuid>b76f68cf-b36a-4738-a649-a5bb02856138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'EBizApp_JDBC_Env' or . = 'EBizApp_JDBC_Env')]</value>
      <webElementGuid>2c5457f0-f2d7-4c91-a82a-7ae19cfd15a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
