<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AND_t-Report-cell_11 (3)</name>
   <tag></tag>
   <elementGuidId>7312b5e5-a87a-4ef0-8797-e7263743933b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report_R248231011536003638']/div/div/table/tbody/tr[6]/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(6) > td:nth-child(7)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>499529ab-95a7-4a74-97bf-a2c999798661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Report-cell</value>
      <webElementGuid>e513a200-6460-4fa5-8c75-5ed625ee78ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>66a1c6b5-5c8f-49c5-90eb-cbbfc8c1d9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>ACTIVITY_GROUP_CODE</value>
      <webElementGuid>942f1dcd-13dc-49b6-b457-a027392554fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Set1 Activity</value>
      <webElementGuid>2eb16deb-eb7e-44f1-8b47-41d8d640ef19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_R248231011536003638&quot;)/div[@class=&quot;t-Report-wrap&quot;]/div[@class=&quot;t-Report-tableWrap&quot;]/table[@class=&quot;t-Report-report&quot;]/tbody[1]/tr[6]/td[@class=&quot;t-Report-cell&quot;]</value>
      <webElementGuid>8b9458da-fa0e-4cd5-b3d9-2ddfde30e95b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_R248231011536003638']/div/div/table/tbody/tr[6]/td[7]</value>
      <webElementGuid>3f33db77-1608-4bca-aa7f-5fb69f01d7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AND'])[6]/following::td[2]</value>
      <webElementGuid>781fd2a7-962c-48e7-98c3-77f703e24097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorization Object'])[1]/following::td[3]</value>
      <webElementGuid>e8a3501b-e13a-40fd-93cf-07cd2587c5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN'])[11]/preceding::td[2]</value>
      <webElementGuid>3d84940c-d698-43c1-9a54-5f48c681cd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN'])[12]/preceding::td[4]</value>
      <webElementGuid>f6f666c0-646b-4c53-a12a-3d41113cb8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[7]</value>
      <webElementGuid>666d95c4-a5d1-4fd7-9f2c-167780bbf88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Set1 Activity' or . = 'Set1 Activity')]</value>
      <webElementGuid>aa73f7e0-96a8-4673-b29d-a4aa402d06be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
