<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actions</name>
   <tag></tag>
   <elementGuidId>452afc67-64c3-48dc-8460-7c61c4944bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R119140564844328612_actions_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R119140564844328612_actions_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>952b6d81-3416-4623-b656-5f2adba55828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R119140564844328612_actions_button</value>
      <webElementGuid>a4e29d22-6e17-4a55-aa46-0b44dc5cb979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--actions js-menuButton</value>
      <webElementGuid>ff40a94a-5918-4aaa-bfb2-de9d84fc0f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2899fbb4-b15f-44a1-ae75-9d58488f47df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>R119140564844328612_actions_menu</value>
      <webElementGuid>33b1d0f9-877e-4d42-b6ca-da88dfcd10ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>48fbc5c8-7244-43e1-9984-11bd38dbcde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>83fd450c-e4f3-4d8a-b0e9-457007f8bac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R119140564844328612_actions_button&quot;)</value>
      <webElementGuid>82364d34-ab4b-42ad-84fc-91be5a53849f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R119140564844328612_actions_button']</value>
      <webElementGuid>5b8878b6-e3b9-4a16-b694-b8360cf94c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R119140564844328612_toolbar_controls']/div[3]/div/button</value>
      <webElementGuid>21ad7353-0cd8-4479-9360-2128ad33d8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>172821ce-7da2-4260-91c4-e128ca5301d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'R119140564844328612_actions_button' and @type = 'button' and (text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>37483d88-172b-4fff-9169-48620643fa99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
