<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Product Type (Value Required)</name>
   <tag></tag>
   <elementGuidId>ae763823-569a-4d4b-ab87-036e57e51735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Product Type (Value Required)' or . = 'Product Type (Value Required)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P10_OBJ_APP_TYPE_LABEL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bbc89aed-858d-4238-8d1b-65818cfe6eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P10_OBJ_APP_TYPE</value>
      <webElementGuid>97ed746b-554a-4d4f-812f-484fe4e88f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_OBJ_APP_TYPE_LABEL</value>
      <webElementGuid>66c875f5-da69-4678-ad5c-271ee923c57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>88bb563e-b17a-4556-92db-67dd7e92c7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Type (Value Required)</value>
      <webElementGuid>582c08f5-ab0d-43cd-9378-6060e80ac08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_OBJ_APP_TYPE_LABEL&quot;)</value>
      <webElementGuid>64892911-abb9-4748-8e36-a932380fd0c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Product Type (Value Required)' or . = 'Product Type (Value Required)')]</value>
      <webElementGuid>38fa2196-a7a0-4ead-929f-037513c33ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P10_OBJ_APP_TYPE_LABEL']</value>
      <webElementGuid>610860ec-9e41-43cb-9f83-ca6ddb641b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_OBJ_APP_TYPE_CONTAINER']/div/label</value>
      <webElementGuid>ed6f19d1-28a3-4ced-9f1d-595ce9db846b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object Description'])[1]/following::label[1]</value>
      <webElementGuid>853b85f5-7b63-4ad1-b7b2-717f5e015bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[1]/following::label[2]</value>
      <webElementGuid>c357b419-3a94-4bc5-baee-a01072e2c6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MonitorPaaS'])[2]/preceding::label[1]</value>
      <webElementGuid>bf6c72eb-237c-4bd7-8599-d708ce6e6981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Type']/parent::*</value>
      <webElementGuid>20f6b5ca-9905-438c-b075-3e8c9624c235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/label</value>
      <webElementGuid>ead78440-d064-4ba5-a9cd-1451b32ca82c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
