<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage Rules - 678</name>
   <tag></tag>
   <elementGuidId>281e3423-0d36-4e4f-8125-86eec1bec208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-TreeView-label.is-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Manage Rules')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f336493-5f75-4b8f-aef9-b49a424b8107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5515f313-a5ba-4b4b-b5f1-d03004bb064a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>b4f860bb-5dbe-4e34-84ac-97df3b9fc330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-label is-focused</value>
      <webElementGuid>e16bb175-0d59-4e94-be6d-843f3b37dab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1180:7:12794209323807:::7::</value>
      <webElementGuid>fb77376c-dff7-4ba7-8574-fbae82e28e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>fa20d3f4-ab62-46ed-bfdb-6511df97b056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>20f9c313-4d13-480a-930e-da355a7b82a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Rules</value>
      <webElementGuid>7c90069f-c12d-46ef-9217-0878f79b569e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_11&quot;)/div[@class=&quot;a-TreeView-content is-hover&quot;]/a[@class=&quot;a-TreeView-label is-focused&quot;]</value>
      <webElementGuid>30a663e9-25a0-4a0f-ae15-d024ce7d6514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_11']/div[2]/a</value>
      <webElementGuid>d0e5a3ec-bd80-4c43-a9e3-3287fb57dc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage Rules')]</value>
      <webElementGuid>051df87f-cc26-491f-89d1-710f5166b57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Define Scope'])[1]/following::a[1]</value>
      <webElementGuid>61e27958-204e-4dfd-8086-492a89ec9346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analytics'])[1]/following::a[1]</value>
      <webElementGuid>b0a1db05-f606-4904-be28-a78a1a4a23c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Rules'])[1]/preceding::a[1]</value>
      <webElementGuid>c629c809-9ba0-4370-922f-2be523bcfc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage ERP Snapshot'])[1]/preceding::a[2]</value>
      <webElementGuid>f68d9334-f4a7-4534-9f08-672a43ef3f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Rules']/parent::*</value>
      <webElementGuid>922118cf-a121-48e3-9a2d-dcd4676a1a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:7:12794209323807:::7::')]</value>
      <webElementGuid>a8b1d614-7460-47ae-9654-54404943a0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/div[2]/a</value>
      <webElementGuid>7e719a65-a38c-444b-95c1-f38fb4bdb981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:7:12794209323807:::7::' and (text() = 'Manage Rules' or . = 'Manage Rules')]</value>
      <webElementGuid>5dd7a410-0768-4121-aad6-491c54fb6f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:7:24998125860512:::7::')]</value>
      <webElementGuid>24162765-6ee6-47c0-91df-82fbec06da6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:7:24998125860512:::7::' and (text() = 'Manage Rules' or . = 'Manage Rules')]</value>
      <webElementGuid>a5d749dd-1937-4dce-97f4-7018ff61c9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:7:3277736877816:::7::')]</value>
      <webElementGuid>1ca17703-65d1-43c9-9483-7ffa10b0771f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:7:3277736877816:::7::' and (text() = 'Manage Rules' or . = 'Manage Rules')]</value>
      <webElementGuid>7e09a8f8-3ae7-478f-982b-b71f83c569cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:7:27563729009059:::7::')]</value>
      <webElementGuid>2c0c60eb-b304-4705-99ac-aa1a0add8b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:7:27563729009059:::7::' and (text() = 'Manage Rules' or . = 'Manage Rules')]</value>
      <webElementGuid>92e48aa6-676c-49da-88f8-4d2002718949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
