<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go</name>
   <tag></tag>
   <elementGuidId>fb2d3478-21b6-49cf-95c6-a2977dff793b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R240042226928873910_search_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R240042226928873910_search_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a6bb77f-e379-4509-b925-c926aa9440e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R240042226928873910_search_button</value>
      <webElementGuid>aaa03726-8563-4712-a946-2f2e5e905ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--search</value>
      <webElementGuid>aa336729-4423-4f0d-8d05-4952e6649c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b096a4dc-fc94-4e25-80a4-cab0c469f296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>1e3bd760-a92b-4767-bbba-e517b774b469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R240042226928873910_search_button&quot;)</value>
      <webElementGuid>24e7aa80-ed12-4ddb-8e48-e9ae1b200136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R240042226928873910_search_button']</value>
      <webElementGuid>30b6e9ef-46a1-4317-ac25-0b45fd91250d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R240042226928873910_toolbar_controls']/div/div/div[3]/button</value>
      <webElementGuid>e36afddc-06e1-45ad-a1a5-737b34feb381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>d11995a2-14cf-4b5e-8d41-cf1d001c19a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'R240042226928873910_search_button' and @type = 'button' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>1a6704ad-d40b-4503-98eb-8fcf06bc0a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
