<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Activity_1_apex-edit-page</name>
   <tag></tag>
   <elementGuidId>9c92f326-f07c-4781-a76c-804d9d721d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='242004625601843036']/tbody/tr[2]/td/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.apex-edit-page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8bdedf70-bd25-4989-9b79-054c748b1649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/i/app_ui/img/icons/apex-edit-page.png</value>
      <webElementGuid>8fd06dfd-cd1b-41b7-82e1-205d95252a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-edit-page</value>
      <webElementGuid>485eeb21-580e-489f-9b67-28b89614987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;242004625601843036&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tR&quot;]/a[1]/img[@class=&quot;apex-edit-page&quot;]</value>
      <webElementGuid>e27f23f5-501f-4012-936e-1c729664c66a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='242004625601843036']/tbody/tr[2]/td/a/img</value>
      <webElementGuid>a930e470-39ea-4e88-ba29-277f06478b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>b2056046-7617-4652-96a7-53106e860fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/i/app_ui/img/icons/apex-edit-page.png']</value>
      <webElementGuid>27457816-76c7-4af5-8c15-9b1cc0a36b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
