<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm Changes (1) - Copy</name>
   <tag></tag>
   <elementGuidId>d68790f3-e4cb-415f-8732-29294c38024f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B328275908856222745</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B328275908856222745']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f7df1a9-0299-4b31-90cc-0b75c7388283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'CONFIRM',validate:true});</value>
      <webElementGuid>f5efb46f-5404-42ec-a233-f4122affafee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button reportBtn</value>
      <webElementGuid>b310b044-0211-487d-b460-a5763676dc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d127e2af-01c8-4968-b4eb-64dadcadd2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B328275908856222745</value>
      <webElementGuid>dcf1e802-ce95-48f7-ae60-4ad9c120a130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Changes</value>
      <webElementGuid>c20efff3-3cc8-4ed4-88b3-0e0c4f72f6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B328275908856222745&quot;)</value>
      <webElementGuid>212f4002-90c5-460c-82c1-b2de86294111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B328275908856222745']</value>
      <webElementGuid>b08a8635-e36e-434f-a8a5-67c4f4ef5031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainer']/div/div[2]/button[4]</value>
      <webElementGuid>968a0e83-9e50-4af7-9c31-5115078859fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>f85f8a94-603c-45ce-ac3d-edc256379b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B328275908856222745' and (text() = 'Confirm Changes' or . = 'Confirm Changes')]</value>
      <webElementGuid>5f290492-58cd-45e8-884e-7c7b4357a128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
