<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Not VerifiedVerifiedTerminate Access 100</name>
   <tag></tag>
   <elementGuidId>def09aa8-9fbb-43a8-ab32-a38a357c69e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C484081257635932120</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='C484081257635932120']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72382023-1820-4477-b43e-a5e72e1f84f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C484081257635932120</value>
      <webElementGuid>35e3310c-2837-4855-a5b9-afd5defa9a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>484081257635932120</value>
      <webElementGuid>ccf0be4a-bc09-4d1d-b9ac-c608e2ad914e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>5945c069-de8c-406b-9407-f22ec2f32087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3f9df8c-0ba9-4a90-a575-06e10c3e598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e13ca28c-d55e-4ac7-86e5-8a1fd33e6ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a17d1a40-69c4-41c8-a640-2c05591f4a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C484081257635932120_HDR</value>
      <webElementGuid>e55fd4e9-714d-4276-9308-493aaec65fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Verified
Verified
Terminate Access
</value>
      <webElementGuid>8df10c5d-dcdd-4594-86d3-6d0823119f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C484081257635932120&quot;)</value>
      <webElementGuid>d1133370-a67e-41dc-bcea-b27f151fe0ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='C484081257635932120']</value>
      <webElementGuid>bedff4aa-0095-451d-85b5-9317fac3b3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='uacReport_ig_grid_vc_cur']/div/select</value>
      <webElementGuid>4e5e24e8-4045-4487-b1a2-9cfefe6207e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/select</value>
      <webElementGuid>22af6463-9686-47e9-b76c-7b59d371708d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'C484081257635932120' and @name = '484081257635932120' and (text() = 'Not Verified
Verified
Terminate Access
' or . = 'Not Verified
Verified
Terminate Access
')]</value>
      <webElementGuid>f6d5362b-662d-4e81-8a8c-8835474a58ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
