<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_katalon_admin - 561</name>
   <tag></tag>
   <elementGuidId>d5ad03af-8b15-40ab-8bed-23ce53ef9065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'L14205299837764170' and (text() = '
      katalon_admin
  ' or . = '
      katalon_admin
  ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/header/div[1]/div[3]/ul/li[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#L14205299837764170</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16ea9e42-2c31-4b8f-a45e-c7c691cf9a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button t-Button--header t-Button--navBar js-menuButton</value>
      <webElementGuid>49035b91-e8da-4ee5-a045-a4b30472246f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63cf68e2-7655-405c-a4a7-89be01f2c767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L14205299837764170</value>
      <webElementGuid>0adad7b8-1d6a-454a-9775-41030cca20e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>menu_L14205299837764170</value>
      <webElementGuid>1b682adb-4f1e-4bbd-87db-5655b08cc176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>b8385b91-26f2-4129-9f8c-3e58e826a5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      katalon_admin
  </value>
      <webElementGuid>506815b5-9bca-4055-890d-223079a09d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L14205299837764170&quot;)</value>
      <webElementGuid>3273a589-8574-4d22-b365-f11e56e74dcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='L14205299837764170']</value>
      <webElementGuid>127bb5b4-1039-4ce5-bb64-275d7b8f4114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='14205299837764168']/li[2]/button</value>
      <webElementGuid>b6351fcd-8166-4f9c-b94b-deda84ebfbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>935aec9e-8d75-46e1-bdf5-6d609f471eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'L14205299837764170' and (text() = '
      katalon_admin
  ' or . = '
      katalon_admin
  ')]</value>
      <webElementGuid>0edb1e4f-5177-4df4-b00e-b7095609a267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
