<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_p_ignore_10</name>
   <tag></tag>
   <elementGuidId>fe031b59-c8aa-4b1d-88e6-b89b5e01ebc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='R163105974055422926_expression']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R163105974055422926_expression</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eecefa73-d418-4dae-8311-7f8e32fead56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-text</value>
      <webElementGuid>b3774030-fe50-4842-b5d7-d55b84ae0d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R163105974055422926_expression</value>
      <webElementGuid>8c736a83-dda1-43df-b402-a31fe714dacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8845b8bb-e3d0-4c38-8693-8b0fb92c0574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>15ece0d5-451f-495c-a681-ad2da687147a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>381f9656-4130-4c76-af26-806a1efc07aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R163105974055422926_expression_label</value>
      <webElementGuid>1cc71e4b-a8e7-4a0f-9843-9e4167fcee32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R163105974055422926_expression&quot;)</value>
      <webElementGuid>603ae325-2c26-4dec-be5b-b7d0fd6ee2b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='R163105974055422926_expression']</value>
      <webElementGuid>c130915b-551d-4fa0-ae05-6941183d5462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R163105974055422926_expression_container']/div/div[2]/span/input</value>
      <webElementGuid>12cf2eba-24ce-4aeb-a8d0-4787fdc11721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>ea3f3ac4-0cf3-4934-97ed-b4460529c5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'R163105974055422926_expression' and @type = 'text' and @name = 'p_ignore_10']</value>
      <webElementGuid>4e8f2965-cd94-4ef8-84ed-8125f73f2fb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
