<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Attributes-NEW_CLOUDERP</name>
   <tag></tag>
   <elementGuidId>32bdb4d2-c9dc-490d-b08f-dfb09cd6786e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Attributes-NEW_CLOUDERP')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b54df663-8cbb-424a-9984-63f0a3d45fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1120:10:13016931321593:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:365231,7908,7908,365231&amp;cs=3SPadVmgnW_cEP02bi05NckIUEnRuvzvpTKCTr7pl_73W-Io1leCpeNXuZN5Ujdz8fr0OqNzlST2c7F0gWnO2tQ</value>
      <webElementGuid>d7b6cfbb-3019-4baa-b2e8-83ef332bd11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attributes-NEW_CLOUDERP</value>
      <webElementGuid>b20cb92c-d54a-4fdf-808a-f0bd2e2a3547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;122864437533293003_orig&quot;)/tbody[1]/tr[3]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>f129d227-a4e5-4e9b-b9f5-c5047137bf81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1120:10:13016931321593:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:365231,7908,7908,365231&amp;cs=3SPadVmgnW_cEP02bi05NckIUEnRuvzvpTKCTr7pl_73W-Io1leCpeNXuZN5Ujdz8fr0OqNzlST2c7F0gWnO2tQ' and (text() = 'Attributes-NEW_CLOUDERP' or . = 'Attributes-NEW_CLOUDERP')]</value>
      <webElementGuid>1e3ec4e0-fd43-45c8-8b04-65cac0d31a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='122864437533293003_orig']/tbody/tr[3]/td/a</value>
      <webElementGuid>264e6d84-abcc-416f-b1e9-29c4a03937d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Attributes-NEW_CLOUDERP')]</value>
      <webElementGuid>55269445-b476-4031-85f9-37795cd1c4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/following::a[1]</value>
      <webElementGuid>46c84e6a-18c2-4052-ba25-d3ec0359fe07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/following::a[1]</value>
      <webElementGuid>bfe41be1-35aa-4ff4-8602-4132d016a4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/preceding::a[1]</value>
      <webElementGuid>fd1bc5d1-e774-48f9-b10a-84f0b3c453dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSOD_ATTRIBUTE_ALL'])[1]/preceding::a[1]</value>
      <webElementGuid>0204904b-7a3c-4192-85f7-aac16cdbb8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attributes-NEW_CLOUDERP']/parent::*</value>
      <webElementGuid>07e19d8d-280a-45db-bb02-a883000c4567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1120:10:13016931321593:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:365231,7908,7908,365231&amp;cs=3SPadVmgnW_cEP02bi05NckIUEnRuvzvpTKCTr7pl_73W-Io1leCpeNXuZN5Ujdz8fr0OqNzlST2c7F0gWnO2tQ')]</value>
      <webElementGuid>a1f5c162-02e0-44b5-b105-82883bb2f009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>595b8416-09c7-46b8-85fd-bf4d5efb6e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
