<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_P10_DESCRIPTION</name>
   <tag></tag>
   <elementGuidId>9669df3f-d551-48db-b068-12d306dc0add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P10_DESCRIPTION</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name = 'P10_DESCRIPTION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8a0dcb07-af98-4ec2-ba2d-c36f9434b169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P10_DESCRIPTION</value>
      <webElementGuid>84eb9195-2da7-48a7-88db-decae739e699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6e3c71eb-6afb-4ec2-9aac-219350e526d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>cd8dad7e-7062-46e1-b7ea-3d18022d8b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_DESCRIPTION</value>
      <webElementGuid>36ad0f79-a162-4fbe-bd3a-627601738cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea</value>
      <webElementGuid>ee4987e0-542f-4815-979c-53cc4212e49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67a3d042-fc00-46fb-b5ef-4aed990cfca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_DESCRIPTION&quot;)</value>
      <webElementGuid>9f1ca60c-d4db-4de9-abdd-85cb7ba6ecb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'P10_DESCRIPTION']</value>
      <webElementGuid>cb2caa93-9db4-446c-ad5c-cd78a03f3435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='P10_DESCRIPTION']</value>
      <webElementGuid>4c830994-d8aa-4ec6-9d8e-fcde0f1bb470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_DESCRIPTION_CONTAINER']/div[2]/div/div/textarea</value>
      <webElementGuid>2e51b3df-d357-4322-a0a3-0aedd182ba3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f55c9059-8020-4bad-a404-f0528460de8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
