<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CE_MANAGE_BANK_STATEMENT_CODE_PRIV</name>
   <tag></tag>
   <elementGuidId>b5795691-93a8-4761-90f7-deb7bea69eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='154256958746258637']/tbody/tr[2]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>11069afd-799f-40e1-b72b-a3fcbcf8fa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-tL</value>
      <webElementGuid>f4a9ea71-8e5f-465d-a098-922275594be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>C159174373189710822</value>
      <webElementGuid>0bf75cc4-f048-46cd-ae44-2faacb5918db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CE_MANAGE_BANK_STATEMENT_CODE_PRIV</value>
      <webElementGuid>8e8b758b-232d-495e-bb95-02aeb84f4955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;154256958746258637&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]</value>
      <webElementGuid>e0d85f78-c021-4d96-98c9-84562173fb1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='154256958746258637']/tbody/tr[2]/td[4]</value>
      <webElementGuid>5e2372e5-dbc8-4088-854f-41c179bc55ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>a809963b-f94d-421d-a352-d1b45035bc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CE_MANAGE_BANK_STATEMENT_CODE_PRIV' or . = 'CE_MANAGE_BANK_STATEMENT_CODE_PRIV')]</value>
      <webElementGuid>2d16ecb0-c802-4a3e-a3ea-46eb21c64156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
