<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NZ - ERP Cloud - Asset Inquiry</name>
   <tag></tag>
   <elementGuidId>abaf93ec-f2c2-4d0a-9d86-a36965e04540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='R323722309891809671_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R323722309891809671_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3e2d81c5-5dae-49c7-9185-909fd5d11d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>11c846e9-1c32-480e-8f6c-d1749363b9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82be94bf-df6d-4cfb-9846-c32a816007c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-readonly is-focused</value>
      <webElementGuid>f5d3d846-5d38-4d18-98d2-159e6e61900b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R323722309891809671_ig_grid_vc_ctx C325068056747960505_HDR R323722309891809671_ig_grid_vc_cur</value>
      <webElementGuid>8b617494-49d3-4e74-a377-a85612384ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R323722309891809671_ig_grid_vc_cur</value>
      <webElementGuid>ddc9bb0e-f52f-4afb-a8a0-b404bd6bd88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NZ - ERP Cloud - Asset Inquiry</value>
      <webElementGuid>6fae0565-a20e-4439-abeb-1eb0f716e349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R323722309891809671_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>2bf93d15-6856-4846-8c6a-ab257c191d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R323722309891809671_ig_grid_vc_cur']</value>
      <webElementGuid>e41a4717-b09e-4ae6-a480-91fe7e6b09ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R323722309891809671_ig_grid_vc']/div[3]/div[4]/table/tbody/tr[17]/td[2]</value>
      <webElementGuid>6a900ef3-865e-4e1d-88f7-d070555e61fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU - ERP Cloud - Intercompany Approval (Approval Required)'])[2]/following::td[2]</value>
      <webElementGuid>a6fff4dc-c68e-462b-9471-87d6f9a043e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1 Ktln Eacm-User'])[20]/following::td[3]</value>
      <webElementGuid>9b6d469e-5d6e-46fd-8ca8-71b528263598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATALON_ADMIN'])[21]/preceding::td[1]</value>
      <webElementGuid>3390c3c5-01dc-4457-964b-f1efcd27cddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1 Ktln Eacm-User'])[21]/preceding::td[2]</value>
      <webElementGuid>807ae231-a82c-4d03-9364-491c083b48d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NZ - ERP Cloud - Asset Inquiry']/parent::*</value>
      <webElementGuid>1bd1ef80-2b88-4d40-a5ab-83922e017cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]</value>
      <webElementGuid>ab73918b-53f5-4777-b3ff-12d1870c397f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'R323722309891809671_ig_grid_vc_cur' and (text() = 'NZ - ERP Cloud - Asset Inquiry' or . = 'NZ - ERP Cloud - Asset Inquiry')]</value>
      <webElementGuid>b2737f4a-c928-4182-ac21-666e34880d6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
