<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expression_p_ignore_10</name>
   <tag></tag>
   <elementGuidId>dfee6540-ddce-477d-860c-8da5a7ac8dd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mngSnap_expression']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mngSnap_expression</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e0efbf4-4a79-4490-b13c-fcc521b72f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-text</value>
      <webElementGuid>73f2d003-7d4c-4f60-a555-cd6fb8fe8c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mngSnap_expression</value>
      <webElementGuid>8039d140-2aa8-4cbc-ada8-e538f8f47947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>023554bb-a442-4964-a829-453e3883cab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>8a04afb0-baf9-45ab-826d-176aba9d04e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>fd2da78a-7734-45ff-943d-b381c57e0491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mngSnap_expression_label</value>
      <webElementGuid>f7537c1e-be25-447b-bb29-d83d1edad19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mngSnap_expression&quot;)</value>
      <webElementGuid>57b66274-42d4-4eaf-a1bd-cd2973326465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mngSnap_expression']</value>
      <webElementGuid>b8668b49-ba44-49be-a4d8-7e12042017bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mngSnap_expression_container']/div/div[2]/span/input</value>
      <webElementGuid>04412a79-e67c-4ec4-950d-9c7fc30e55b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>1883bf87-f285-4230-9816-eedddbe4d403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mngSnap_expression' and @type = 'text' and @name = 'p_ignore_10']</value>
      <webElementGuid>222c232d-71ea-449f-9c8d-6b162bcd1e70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
