<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Status_a-IRR-headerLink</name>
   <tag></tag>
   <elementGuidId>9ea115dc-1c8d-4114-a735-910cdbbe1b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='C163420831693329750']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#C163420831693329750 > a.a-IRR-headerLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\31 63420201166329744&quot;] >> internal:text=&quot;Start Date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>431380a7-2e0b-450b-91ae-7affbe9dc281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>6af28698-9c22-465b-a4a8-b89ef44d9807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>163420831693329750</value>
      <webElementGuid>6908d3c4-fbc3-4cd4-bd04-fe8b5da9736c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7fbe88ae-6cda-4e90-89f0-bf740a42e236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Date</value>
      <webElementGuid>0744cd54-5fd4-4c37-b6f9-0b5b77952204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;163420201166329744&quot;)/tr[1]/th[@id=&quot;C163420831693329750&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>8d4a0da2-6939-42d9-8cbf-3d4b14700b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C163420831693329750']/a</value>
      <webElementGuid>2bafa105-ef97-47c8-aafe-b161ba16e689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start Date')]</value>
      <webElementGuid>908253f5-c315-433b-b9bc-6047c3bb4e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>e20fe99e-b54c-4938-986e-c6c37516b56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date Action'])[1]/following::a[2]</value>
      <webElementGuid>2f241770-5964-42c4-8dde-3ef396c4b662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/preceding::a[1]</value>
      <webElementGuid>b647b8c9-ba34-4241-baee-a434ec00c0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Date'])[1]/preceding::a[2]</value>
      <webElementGuid>812cc997-ea90-4608-b71b-7251e3e82313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Date']/parent::*</value>
      <webElementGuid>7ece8df8-9429-4c76-b986-f2093675d162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/a</value>
      <webElementGuid>a3d813e3-bac9-4be5-b8c7-82827b164936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Start Date' or . = 'Start Date')]</value>
      <webElementGuid>79468ca4-d853-4b60-a8b6-c7169e056bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
