<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actions (1) (1)</name>
   <tag></tag>
   <elementGuidId>dec267da-7034-4286-bbcc-47272b9d9e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='scopeRoles_actions_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#scopeRoles_actions_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e6f91b5-d739-42e8-9755-696485c7b146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scopeRoles_actions_button</value>
      <webElementGuid>f7462333-00d0-413d-a1f2-e2a371576d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--actions js-menuButton</value>
      <webElementGuid>169998c8-678c-4696-b232-e31c13865941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8389a870-bf28-4622-bac4-f1b76a9a2628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>scopeRoles_actions_menu</value>
      <webElementGuid>29985ba7-88fd-4c15-85e7-9a8011ea4ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>de403a81-0c85-4bb6-ac4c-518b5c44f814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>55fde2f7-3270-4bf0-9194-5d5a1d5cf8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scopeRoles_actions_button&quot;)</value>
      <webElementGuid>964e59b3-cd2a-4514-99c1-b6e49ba01b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='scopeRoles_actions_button']</value>
      <webElementGuid>48bc81eb-371e-4a30-b84f-0a5dbc65d2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scopeRoles_toolbar_controls']/div[3]/div/button</value>
      <webElementGuid>3ec7767d-6022-40b7-b18d-91f60074890e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>0630c066-5218-4247-a6b3-7a032b335b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'scopeRoles_actions_button' and @type = 'button' and (text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>e4405f03-0cd5-4d73-9dea-b67ef76f9337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
