<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select any oneEBizApp_JDBC_EnvKTLN_C_10fa97</name>
   <tag></tag>
   <elementGuidId>7608574d-9e45-4b7f-af53-0c941dcfefc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P0_ENVIRONMENT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41bbd75a-17ec-4e7b-8819-04684a1688a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>96022724-ed76-4509-b2ec-9388fad70bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>a7e59a82-255e-44f3-b9a4-47b43c3a09da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>975b5ba5-b3c0-4d3a-b191-57be3a79491b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa77dde1-b57e-4120-9325-29369a95917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7f7a4548-a10e-43c5-b41e-4763602b533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P0_ENVIRONMENT');</value>
      <webElementGuid>a727344e-0c55-4448-a52d-fa7027c9317d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
EBizApp_JDBC_Env
KTLN_CloudERP
KTLN_CloudERP_EACM
McD_GRM_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
</value>
      <webElementGuid>f2a038d0-e62c-49b5-9717-ab99c49650d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT&quot;)</value>
      <webElementGuid>f26423de-79cb-4593-84c6-c8972657e10f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P0_ENVIRONMENT']</value>
      <webElementGuid>22e203b8-db62-4a45-9544-6ab1defdd71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>dcdf0751-ce7c-43af-b310-45dc71a24baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dd2ab23b-314d-47f9-b534-22f3bc8edde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P0_ENVIRONMENT' and @name = 'P0_ENVIRONMENT' and (text() = 'Select any one
EBizApp_JDBC_Env
KTLN_CloudERP
KTLN_CloudERP_EACM
McD_GRM_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
' or . = 'Select any one
EBizApp_JDBC_Env
KTLN_CloudERP
KTLN_CloudERP_EACM
McD_GRM_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
')]</value>
      <webElementGuid>ff657f63-c5e3-4c42-a0a9-11a724ef9848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
