<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_P35_REQUEST_DESCRIPTION</name>
   <tag></tag>
   <elementGuidId>a07b2996-7c44-4290-b69d-03c2583f504e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P35_REQUEST_DESCRIPTION</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P35_REQUEST_DESCRIPTION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26a2899e-3fc1-486c-b2ec-93723910ff0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19ba82df-f35c-4c67-b036-01cb6319b282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P35_REQUEST_DESCRIPTION</value>
      <webElementGuid>7d98b7d8-9007-437c-9b25-cc7249ad5717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P35_REQUEST_DESCRIPTION</value>
      <webElementGuid>60863918-d442-443d-af6a-b2fe88d31a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>739470ba-cab6-416e-97e2-438208d49b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>09404222-a12e-4363-bafd-c98b13993cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>a2e93bc5-ee7d-4ca7-8e9a-8ea071a06132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>4812e3e0-177e-47d5-ae2c-938430c2a16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P35_REQUEST_DESCRIPTION&quot;)</value>
      <webElementGuid>aa172e6e-77f6-499c-a79b-d721f1299ff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P35_REQUEST_DESCRIPTION']</value>
      <webElementGuid>a53d7493-c271-4123-9c9d-7a27ecd0d789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P35_REQUEST_DESCRIPTION_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>f2f0d171-9219-4fab-95f7-b1ac20df97c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>30522d2b-76cb-4f59-9b83-280c2900866a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P35_REQUEST_DESCRIPTION' and @name = 'P35_REQUEST_DESCRIPTION']</value>
      <webElementGuid>6c06d4dd-7849-4bfa-8b2a-b25ca5aa50da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
