<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ANANDK</name>
   <tag></tag>
   <elementGuidId>e1995866-a2e4-49bc-b923-8c2be938d4bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.popup-lov-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1c659908-fac4-4936-9456-35b3ef1acb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-lov-highlight</value>
      <webElementGuid>d355cc81-64b8-4c45-a1ab-94501d005cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ANANDK</value>
      <webElementGuid>d1120c55-3fa0-442d-850a-31d023c7f7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agv_1_cur&quot;)/span[@class=&quot;popup-lov-highlight&quot;]</value>
      <webElementGuid>264b6986-7c55-448d-b9b3-d095c6db77ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='agv_1_cur']/span</value>
      <webElementGuid>2e0aaf3c-eee2-428f-8911-56c1cccfeace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>e057f1ba-e4e2-4f97-ae18-cb14244515da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ANANDK' or . = 'ANANDK')]</value>
      <webElementGuid>ac43a172-fbfd-4ef3-8a85-c43e18445512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
