<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Request Deactivate User_B162775359869928197</name>
   <tag></tag>
   <elementGuidId>af81a6b0-1862-48e8-ad33-6d6389607ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B162775359869928197</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B162775359869928197']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Request New Access&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0428ae0-025d-4b52-9667-d83a89e3ed29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'SUBMIT',validate:true});</value>
      <webElementGuid>4816f89c-1630-4a60-af29-c60f8e466f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button </value>
      <webElementGuid>a4a6af75-760c-4626-9114-80f4408bd23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55e6fbf8-1cfc-46ea-a4bc-2f154d437ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B162775359869928197</value>
      <webElementGuid>a42abf6a-1f9a-4cab-afdb-119472969c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request New Access</value>
      <webElementGuid>6c5c7b1a-f8b1-4275-9627-68cc65c73113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B162775359869928197&quot;)</value>
      <webElementGuid>7d773812-e428-4238-b268-54742c1e386e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B162775359869928197']</value>
      <webElementGuid>d8824ab1-ced9-4191-b260-d75b8d609f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R250713476385354904']/div/div[2]/button[2]</value>
      <webElementGuid>9884eb77-eb54-4d40-ab95-b6c6ca0042ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Deactivate User'])[1]/following::button[1]</value>
      <webElementGuid>c0318089-7117-4756-983d-3c4cd0e1bce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 1 of 4 - User Information Review'])[1]/following::button[2]</value>
      <webElementGuid>e7e05f30-a11e-4be8-98d6-c528ad871e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Settings'])[1]/preceding::button[1]</value>
      <webElementGuid>8eff5fa2-a450-4b7c-82a1-6cc074194b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>2a261db6-8e6c-4437-8c77-57ecc547f14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B162775359869928197' and (text() = 'Request New Access' or . = 'Request New Access')]</value>
      <webElementGuid>e08ec881-e438-4012-9c29-3b734f4a10c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
