<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select an Environment -EBizApp_JDB_73a228</name>
   <tag></tag>
   <elementGuidId>ed511f2c-4f5f-4ade-8213-4a737c471a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P100_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P100_ENVIRONMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f9d36bd1-e207-4bee-b0d6-6f447b88a218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P100_ENVIRONMENT</value>
      <webElementGuid>34e8e894-1f43-49dc-afb7-e9864fad765f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P100_ENVIRONMENT</value>
      <webElementGuid>67164b24-ef0d-459a-abfe-e115c7f7ae79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>cfec2137-8509-4ca1-af36-d3493b6be29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a299ce3c-555c-47f7-9735-ef9098cd02ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87a51eb4-16bc-4add-b83e-350632ebf5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P100_ENVIRONMENT');</value>
      <webElementGuid>c2273b8c-c4fa-4cfd-a940-88cd460e761d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
</value>
      <webElementGuid>3a18153c-5f35-4f49-aac8-7d48c897524a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P100_ENVIRONMENT&quot;)</value>
      <webElementGuid>15f34c6f-dba3-405a-8329-1e6e3d1a8c4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'P100_ENVIRONMENT' and (text() = '- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
' or . = '- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
')]</value>
      <webElementGuid>04621ea6-0798-413c-8d3d-b8cdb043927e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P100_ENVIRONMENT']</value>
      <webElementGuid>af07b69e-8c76-40ef-a5b5-1e869fa07145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P100_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>b88d855d-9ac1-4ab1-8a88-aeced3984330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>268205a6-d682-444b-a532-207893867ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>99900f2b-b1d8-4d8f-96a1-f4cfd999d13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Type Version'])[1]/preceding::select[1]</value>
      <webElementGuid>2caa03bd-ba9f-4c8d-a462-8f740a766f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oracle Cloud ERP 20x'])[1]/preceding::select[1]</value>
      <webElementGuid>1c6585a0-68f7-4d1d-bbd8-dd5cc0f8c36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e7b8a3fb-cd69-4b36-8d2d-fc6c8fa2e5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
