<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Role Group  Role_P5_ENTRY_REQUEST_MOVE</name>
   <tag></tag>
   <elementGuidId>dfeaabed-c7b0-476e-b6f7-3790dbb9026c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P5_ENTRY_REQUEST_MOVE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P5_ENTRY_REQUEST_MOVE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eef3580b-93b8-4918-9c1a-d439e4094dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P5_ENTRY_REQUEST_MOVE</value>
      <webElementGuid>ee5ea864-0101-4210-b4df-22323066bda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--noLabel a-Button--withIcon a-Button--small a-Button--noUI a-Button--shuttle</value>
      <webElementGuid>de5dfc98-eb5a-4134-bce4-384c2ca7016a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>363bb93a-7ac9-40f2-9a1f-ac6dc1364ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>efa0739f-2ad6-466e-b531-9bbe1822638e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>f4a9d030-27ee-4c87-a101-cf95eb54a504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P5_ENTRY_REQUEST_MOVE&quot;)</value>
      <webElementGuid>e56567f3-f428-4a8a-89dd-e7f42766eb5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P5_ENTRY_REQUEST_MOVE']</value>
      <webElementGuid>9c469f0d-3789-4183-8707-2d2d118de12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P5_ENTRY_REQUEST']/table/tbody/tr/td[2]/button[3]</value>
      <webElementGuid>697920dc-c6e0-4c63-aa33-873fe2311298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>d544a5d9-dd43-415b-beb7-26c7313852ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'P5_ENTRY_REQUEST_MOVE' and @type = 'button' and @title = 'Move']</value>
      <webElementGuid>76b6e390-e358-4910-b73b-34b0f4da646d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
