<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entry Hierarchy</name>
   <tag></tag>
   <elementGuidId>cef77ae7-5ec4-4909-9c05-a5bf0d79c3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C145576213828330209 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='C145576213828330209']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b5e0dbd-660a-41b5-9720-4f5972dfdfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>cbfb7125-8c3c-4b22-a541-363acb40ea7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>145576213828330209</value>
      <webElementGuid>1c93d76d-2a08-40fd-901f-9c5da0a6e901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f9886716-4d15-4368-a785-3d79f22d3773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entry Hierarchy</value>
      <webElementGuid>ffec3e9f-87b1-4b0e-8a41-28307616437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;145575447502330201&quot;)/tr[1]/th[@id=&quot;C145576213828330209&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>88727f21-7c16-4cd2-bb34-0d98aa91e39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C145576213828330209']/a</value>
      <webElementGuid>915c02c4-40f9-4d6e-8a46-7498444886f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entry Hierarchy')]</value>
      <webElementGuid>43faa4a3-77f5-4973-a5c4-cc82adb067b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/a</value>
      <webElementGuid>cd8b6010-69bc-47f8-a44f-c2c14460c166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Entry Hierarchy' or . = 'Entry Hierarchy')]</value>
      <webElementGuid>e0a602aa-92ab-4d9e-ad99-1e2ef5b80f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
