<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_u_affected_environment</name>
   <tag></tag>
   <elementGuidId>bbdc938f-d44d-49bb-8b14-521f9576bf7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oItemsApiIg_ig_grid_vc_cur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'u_affected_environment' or . = 'u_affected_environment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>214cde72-f0b4-47e8-a242-68af0bacbaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>29d703ac-a475-4fc9-bdef-8dd8b2db6947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48b49f48-01c5-41d9-b6a2-8b0c8789433d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-focused</value>
      <webElementGuid>8a63cfa0-5d6a-4c8d-af7a-f880adfb1715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>oItemsApiIg_ig_grid_vc_ctx oItemsApiIg_ig_grid_vc_cur</value>
      <webElementGuid>e99d16fb-f193-4abe-b222-5151ca8f8e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oItemsApiIg_ig_grid_vc_cur</value>
      <webElementGuid>1704fa35-e6d8-41c6-92ae-71e910220a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>u_affected_environment</value>
      <webElementGuid>23393424-d05f-479b-b94a-f8f2c6c73643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oItemsApiIg_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>fb0fba66-76d8-48ad-b101-8e3d706becb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'u_affected_environment' or . = 'u_affected_environment')]</value>
      <webElementGuid>f254a0f6-adb5-4ef0-a88e-4b989422912a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='oItemsApiIg_ig_grid_vc_cur']</value>
      <webElementGuid>30b53331-5ba8-47ee-99cd-3de224391004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oItemsApiIg_ig_grid_vc']/div[2]/div[4]/table/tbody/tr[8]/td[5]</value>
      <webElementGuid>5d05b381-5e85-4c79-ad88-52cd4809a97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSOD.FSOD_UAC_USER_ROLES (TABLE)'])[8]/following::td[2]</value>
      <webElementGuid>2be8c224-1794-4758-9ac6-75df46820545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[14]/following::td[5]</value>
      <webElementGuid>443ce115-d38f-4123-9f8e-d1e9d2cfe2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[15]/preceding::td[2]</value>
      <webElementGuid>0ce42f4c-e006-4c9e-a285-a18b2624ccfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[16]/preceding::td[4]</value>
      <webElementGuid>83017a96-f831-4950-9f95-7af35608b6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='u_affected_environment']/parent::*</value>
      <webElementGuid>6f411485-7e29-4536-b1e5-7cb633d7516c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[5]</value>
      <webElementGuid>459b0421-00c6-42cc-9e49-1974ea4c2ae0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
