<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter (1) (1)</name>
   <tag></tag>
   <elementGuidId>95070322-3d05-4a02-8eaa-3ea1b6c2c5a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_actions_menu_2i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search_actions_menu_2i']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f016a64f-2382-444b-a749-f2666a6fe7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f918bcb-2800-4463-bd4d-da2e00986818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_actions_menu_2i</value>
      <webElementGuid>6f2132c7-001b-462b-92c6-a3caf2ad2cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>7753d2e1-3bee-43ab-bbff-66b923c16ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>d0ece04e-4a3e-4440-8678-ce3b6aa23686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>edf5f46a-b51e-44da-852f-2cb22424551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_actions_menu_2i&quot;)</value>
      <webElementGuid>c488e880-32ae-47dd-9c2a-fbd40cba13fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search_actions_menu_2i']</value>
      <webElementGuid>474a63e5-eb16-42da-8f8c-5fc47f0041a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='search_actions_menu_2']/div/span/button</value>
      <webElementGuid>b6266347-9cfa-48bd-ad69-9e432841f828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/button</value>
      <webElementGuid>f2b9445b-fb9b-4d22-ba21-74e9ab91b469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'search_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>cd040b0a-4cf3-4bf0-802b-c130af834480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
