<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Violation Level_f01</name>
   <tag></tag>
   <elementGuidId>775fb0b2-1763-4d77-8cde-2335128e378d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;f01&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='f01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;NOHRMGR : Per Olaf Berg Responsibility Chef SFTP_Rule1 SET 2 SFTP_2 Function FND_FNDCPDIA_VIEW Concurrent Requests: View Responsibility : Chef->Menu : CLR_TOP_MENU->Menu : FND_OTHER 4.0->Menu : Requests Menu - Other Responsibilities->Function : Concurrent Requests: View OPEN - - Open - - OPEN - - - - - OPEN - - - HCM INTRA&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6fb7b79-25fa-4d64-91f4-2fc37acc578a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>37656435-9d77-4900-98c3-6637e8b7500b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f01</value>
      <webElementGuid>01ab8809-0203-4596-ae25-21a33b3d9a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>54610123</value>
      <webElementGuid>56278ea2-e07d-4bed-b477-033a0a220e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;291211863100602603_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/input[1]</value>
      <webElementGuid>6625ee83-90ed-4d71-9b5a-540241f2da99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='f01']</value>
      <webElementGuid>e90f4311-5fc8-4746-a144-3d6f682f2041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='291211863100602603_orig']/tbody/tr[2]/td/input</value>
      <webElementGuid>7055767c-b252-43a8-bba0-7c062a6282c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>6bd373bd-8dc4-449f-a9ef-b95b6487452c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'f01']</value>
      <webElementGuid>ca0d7bce-6ea1-466f-a869-f6c63bb3af99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
