<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a (2)</name>
   <tag></tag>
   <elementGuidId>1730e077-8772-4899-8a13-23202354721f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.u-tL > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='247793320273899118']/tbody/tr[2]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SAP Rule#1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f987c6b-8ddc-44d5-b00c-461d96be6183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1180:9:27007780911219::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:26357,26256,7</value>
      <webElementGuid>fbe82418-e716-4ea1-b237-c399c2c67a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAP Rule#1</value>
      <webElementGuid>4347c7b9-8197-4475-bf9d-6f9681c91fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;247793320273899118&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>56c5dff8-b76b-4fb1-a13c-337981adbaa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='247793320273899118']/tbody/tr[2]/td/a</value>
      <webElementGuid>2410122b-008a-43ab-b55e-29621a9e6b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SAP Rule#1')]</value>
      <webElementGuid>a4a750d4-bc23-4ef8-90ee-2ab6c9ace40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAP Rule#1'])[1]/following::a[17]</value>
      <webElementGuid>0c9f0ecf-f59d-4ab0-a9af-694a82e76e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAP Rule#1'])[3]/preceding::a[1]</value>
      <webElementGuid>8c9b98d7-6d31-4f17-aba7-6b6b7fe238a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOW'])[1]/preceding::a[1]</value>
      <webElementGuid>172af605-5f36-4318-8bf7-6d419d8e149c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:9:27007780911219::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:26357,26256,7')]</value>
      <webElementGuid>246348c8-dcc3-4a48-94d9-5c499829d493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>f214c57c-ab19-415a-85f1-4fd126ccf26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:9:27007780911219::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:26357,26256,7' and (text() = 'SAP Rule#1' or . = 'SAP Rule#1')]</value>
      <webElementGuid>d8c30d3e-bb30-45e4-9776-6bca9f8ae41d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
