<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Coupa_Rule1a</name>
   <tag></tag>
   <elementGuidId>8d4fc941-49fd-498b-8f8a-72f76e3e6c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = 'f?p=1180:9:282701339417::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:25124,25124,7' and (text() = 'Coupa_Rule#1a' or . = 'Coupa_Rule#1a')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.u-tL > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Coupa_Rule#1a&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24c848d8-3710-4f73-8944-6e536140c263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1180:9:282701339417::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:25124,25124,7</value>
      <webElementGuid>96f72127-3786-4692-b8a8-ee1406d8ea59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coupa_Rule#1a</value>
      <webElementGuid>db38524b-426a-4aa8-8aee-0180017263e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;247793320273899118&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>3bca9237-164d-4a40-86d4-744f53db0172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:9:282701339417::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:25124,25124,7' and (text() = 'Coupa_Rule#1a' or . = 'Coupa_Rule#1a')]</value>
      <webElementGuid>186ded55-afb3-448c-89d6-fff597ea1471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='247793320273899118']/tbody/tr[2]/td/a</value>
      <webElementGuid>3412ebd4-9325-433b-8643-d31e03cc34b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Coupa_Rule#1a')]</value>
      <webElementGuid>06c28353-69bc-41ef-aef8-5a8925dd1f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Status'])[1]/following::a[18]</value>
      <webElementGuid>ec22ce26-018f-4641-9308-4d989510d4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupa_Rule#1a'])[2]/preceding::a[1]</value>
      <webElementGuid>f54ec186-5c89-4749-b847-1682c13c1cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIGH'])[1]/preceding::a[1]</value>
      <webElementGuid>e5eb653c-001b-4873-b5a7-5b369874ce9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Coupa_Rule#1a']/parent::*</value>
      <webElementGuid>be5f250b-de10-4d47-8204-749e6ba65c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:9:282701339417::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:25124,25124,7')]</value>
      <webElementGuid>e749c299-b170-480c-8609-5d0d8f82ac9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>c1acdf71-66eb-4b34-8338-e7b8dc608285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
