<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Import Rules_R247793226539899118_sea_c93c8e (6)</name>
   <tag></tag>
   <elementGuidId>a046bc5a-4c50-48ca-90ff-15b093771bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R247793226539899118_search_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R247793226539899118_search_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Go&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3508f02a-12e4-4b64-978c-afad0864eb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R247793226539899118_search_button</value>
      <webElementGuid>d970ab3d-3402-4218-9313-42abd09b4cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--search</value>
      <webElementGuid>369e1a09-7dfb-4831-bc12-72ea322f5caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7baf9ef1-53f4-41c6-861e-01ed111a48c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>5fb6e47a-5c35-4d93-bdc3-e2dc8bf33125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R247793226539899118_search_button&quot;)</value>
      <webElementGuid>faa5ece7-c630-4e36-a432-1bead6de90f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R247793226539899118_search_button']</value>
      <webElementGuid>feabc7b8-9014-4226-beff-21c1c6acb452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R247793226539899118_toolbar_controls']/div/div/div[3]/button</value>
      <webElementGuid>23f2d9b5-c464-455e-96fa-25e9ba9067b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Rules'])[1]/following::button[2]</value>
      <webElementGuid>7bd8480d-8306-4437-baf8-ec92efc8ae99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Rule'])[1]/following::button[3]</value>
      <webElementGuid>059374dc-be50-48e3-b481-f646654a5c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[2]/preceding::button[1]</value>
      <webElementGuid>c0e5fb1e-99c4-4381-be59-08afb3731c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>8dabfbce-b9a0-4790-b139-6a8a1574387c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'R247793226539899118_search_button' and @type = 'button' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>24ffb2fb-18a4-4556-aa32-70f912e9cb6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
