<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Environment_P0_ENVIRONMENT</name>
   <tag></tag>
   <elementGuidId>727f8d70-daeb-4672-b7ab-caa449fd2e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P0_ENVIRONMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Environment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>54110a5f-658a-4235-b741-05eda6767e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>22232be9-71d5-481e-9ae5-d80658eb0906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>9b9d5ee6-6ab5-41d6-a7da-ad1ed8043c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>6494679a-601e-4052-b697-c44ef007bbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3638a651-f3f6-4607-87f3-0690c39fc44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>badf1db8-6549-49b8-bb79-633e1135364f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P0_ENVIRONMENT');</value>
      <webElementGuid>9d05bc56-efdd-4db6-b0c3-418d50225648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
McD_GRM_ENV
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
</value>
      <webElementGuid>cdd9e953-875d-4472-b3d8-446a5b74bc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT&quot;)</value>
      <webElementGuid>de42ed65-1343-4e94-8b5b-54bfde1b9d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P0_ENVIRONMENT']</value>
      <webElementGuid>71ce799b-99e4-411e-b818-02ace4315376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>bf6673a5-d7ca-4d87-989e-16188a8ba65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>1cf32015-7000-43d5-b0c9-84e1be4265e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>dadee2f0-cb83-4fed-a3f1-7e89320a8477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Rules'])[4]/preceding::select[1]</value>
      <webElementGuid>01e4b895-f8a4-4d93-938f-6b3b74b5102a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[1]</value>
      <webElementGuid>b37f5578-d499-486c-9b49-1a4ebace7dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9a2e9f56-631d-438e-b850-e2e97446c52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P0_ENVIRONMENT' and @name = 'P0_ENVIRONMENT' and (text() = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
McD_GRM_ENV
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
' or . = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
McD_GRM_ENV
NEW_CLOUDERP
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
')]</value>
      <webElementGuid>3405af36-887b-49f6-aca6-ad7241b57d9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
