<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonP35_RULE_TAGS_MOVE</name>
   <tag></tag>
   <elementGuidId>03078170-49b6-4d28-af7c-f346c3b82a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P35_RULE_TAGS_MOVE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P35_RULE_TAGS_MOVE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a7beab5-5994-4898-9a49-ba7bb56d81ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P35_RULE_TAGS_MOVE</value>
      <webElementGuid>1ed8b4c7-755f-4a11-b1b0-af9758fd3293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--noLabel a-Button--withIcon a-Button--small a-Button--noUI a-Button--shuttle</value>
      <webElementGuid>2a7d723e-6802-452a-aff4-b089903af776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9eee5b54-2c57-474f-8f88-17a0df985c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>1740b7f4-cc28-468e-b1ff-a982c5851a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>74c86a24-504f-4037-9777-655a5fd0ada3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P35_RULE_TAGS_MOVE&quot;)</value>
      <webElementGuid>bb79048b-72cd-4c03-ac9c-5292ee5b7058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P35_RULE_TAGS_MOVE']</value>
      <webElementGuid>a79c9f53-3d60-4095-95ae-a3a50a5bc764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P35_RULE_TAGS']/table/tbody/tr/td[2]/button[3]</value>
      <webElementGuid>6b83cc50-13ae-419a-9234-9ce61f86f11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>0361a768-22fa-4c7e-833f-f54f1e58029e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'P35_RULE_TAGS_MOVE' and @type = 'button' and @title = 'Move']</value>
      <webElementGuid>dbfb56cf-d40f-4cf4-8696-e3b272f83789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
