<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Role Group</name>
   <tag></tag>
   <elementGuidId>c9dea05d-6074-44e3-875f-4560f4391d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C179035684660773312 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[(text() = 'Role Group' or . = 'Role Group')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>45398fcf-3f1a-495c-bce5-34b3263bac78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>d1b51cb3-12c8-4983-877d-f86546390fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>179035684660773312</value>
      <webElementGuid>0420c60e-5f76-42b2-b413-4df4c0482ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>d288a373-1127-4e83-aace-7fa33a2cc106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role Group</value>
      <webElementGuid>a2bc9714-d610-4eb9-8a71-f0f465f443a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;158228896595590718&quot;)/tr[1]/th[@id=&quot;C179035684660773312&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>9b09c4bb-e484-45af-904e-682857073f6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Role Group' or . = 'Role Group')]</value>
      <webElementGuid>a0d41e72-ad02-49ff-99d3-61ccb8cee7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Role Group')]</value>
      <webElementGuid>80af6188-a2a6-4161-8506-284afebad95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Justification'])[2]/following::a[1]</value>
      <webElementGuid>1c39a51e-f8c2-49b3-bbcb-2dfd5787d23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scope'])[1]/following::a[2]</value>
      <webElementGuid>d1560e76-ecc2-47bc-85cc-4de5f14909a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORA_AP_ACCOUNTS_PAYABLE_SUPERVISOR_JOB'])[1]/preceding::a[11]</value>
      <webElementGuid>9b9c2510-cb2a-4807-a700-aa5d9b207bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts Payable Supervisor[ORA_AP_ACCOUNTS_PAYABLE_SUPERVISOR_JOB]'])[1]/preceding::a[11]</value>
      <webElementGuid>b7f6ac63-ec0a-43bb-8a1f-a0c9162eb9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Role Group']/parent::*</value>
      <webElementGuid>3cf00746-b87e-42ed-8024-3cd4ed37698e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[11]/a</value>
      <webElementGuid>748f4204-ccc4-4c93-8b26-b7605b0a65c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C179035684660773312']/a</value>
      <webElementGuid>95e005f0-e1ec-471d-bbe8-b06517ea38ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
