<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EditTag NameTag DescriptionTag Code</name>
   <tag></tag>
   <elementGuidId>66beac21-9bc7-4497-adda-3d890855219c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='R189436115360253186_column_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R189436115360253186_column_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2a4178af-f73d-47d6-b2b6-96dc12fb5d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R189436115360253186_column_name</value>
      <webElementGuid>382d08ec-51d6-4e5a-8a22-23e97a550a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>ea7d32f8-c182-45f3-840a-f39e175a9d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>c2e35335-95ea-412e-aebc-2ae4ed217714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>70c3c580-3ea1-4bbc-8d62-fb7dd09740d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>070ba170-d995-486a-974e-eb2d9e359e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EditTag NameTag DescriptionTag Code</value>
      <webElementGuid>ee99ec67-2b5e-48cc-9b43-60d8d2175fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R189436115360253186_column_name&quot;)</value>
      <webElementGuid>5048cd52-015f-4059-85d8-30cbfd76f47f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='R189436115360253186_column_name']</value>
      <webElementGuid>2b47a959-d078-4d39-b0e7-d1f38f0dadf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R189436115360253186_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>07d4a793-712c-49f4-9fda-21b6249d3d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5d2e63bf-e370-4766-8b04-778cbe4c878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'R189436115360253186_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'EditTag NameTag DescriptionTag Code' or . = 'EditTag NameTag DescriptionTag Code')]</value>
      <webElementGuid>d9e92e30-5119-4706-9c04-cf4910338865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
