<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_User Name</name>
   <tag></tag>
   <elementGuidId>49658ccf-5f07-4480-9e8b-f07925c36cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='C154513240193312332_HDR']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#C154513240193312332_HDR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>429eeede-1a4c-4262-99ad-282c4d13bb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-headerLabel</value>
      <webElementGuid>7ca365a4-df22-49a7-bd54-a5dacb402f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C154513240193312332_HDR</value>
      <webElementGuid>404b0821-1f60-4c49-a764-3693b6259a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>7c064d3c-9a93-499c-bdc4-d638db73444b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C154513240193312332_HDR&quot;)</value>
      <webElementGuid>61466ff9-7e0a-45c0-88dc-4929ce2a2a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='C154513240193312332_HDR']</value>
      <webElementGuid>5812008d-a12f-4c25-9a97-226b0db97c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='R259422667645149962_ig_grid_vc_cur']/span</value>
      <webElementGuid>2b113c6f-b35a-4b93-b86f-f41d18103d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interactive Grid. Report: Primary Report, View: Grid.'])[1]/following::span[3]</value>
      <webElementGuid>9dd05520-ec81-44ca-b885-4000326ef0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Settings'])[1]/following::span[3]</value>
      <webElementGuid>38169731-372c-488c-9c38-93d7c4552459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sorted Ascending 1'])[1]/preceding::span[2]</value>
      <webElementGuid>bba752d2-2028-498a-8ff5-a580bdad9770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Name'])[1]/preceding::span[7]</value>
      <webElementGuid>ca4f7fe5-5257-46df-a42c-25efa50b4d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Name']/parent::*</value>
      <webElementGuid>5c839750-16e4-41bf-a903-0f206247af8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/span</value>
      <webElementGuid>daeacb5d-73fb-45ac-9c89-5f04925fa066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'C154513240193312332_HDR' and (text() = 'User Name' or . = 'User Name')]</value>
      <webElementGuid>75bb8f82-36f7-4a56-a696-7347e586ee59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
