<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Scope Status</name>
   <tag></tag>
   <elementGuidId>0e042ac0-1e5c-4999-8acc-59323f3372cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C179333232113063106 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[(text() = 'Scope Status' or . = 'Scope Status')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a80ee159-58f3-4fb5-bde0-0af235087091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>ec14fdd6-d7d5-4202-8fd2-8e49c77dd589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>179333232113063106</value>
      <webElementGuid>143afa36-5af7-42a8-80fa-95664e1f257a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ac877290-b2c5-424c-9c74-2257e0b7c8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scope Status</value>
      <webElementGuid>f4cf0fb4-bcb5-43e1-8744-ca55a44559c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;179332100530063086&quot;)/tr[1]/th[@id=&quot;C179333232113063106&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>004c779a-c087-416b-9d7a-5b0b47751f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Scope Status' or . = 'Scope Status')]</value>
      <webElementGuid>47cf39a3-503b-4c09-81dd-912ac947dfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C179333232113063106']/a</value>
      <webElementGuid>095a929c-d72b-4750-8b5b-32a9343d4b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Scope Status')]</value>
      <webElementGuid>4cb9cca5-5ccb-454c-ad72-7b2fbe37f9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attribute'])[1]/following::a[1]</value>
      <webElementGuid>2ccfa521-28ce-4318-9fe8-d7cfd9a72e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attribute Type'])[1]/following::a[2]</value>
      <webElementGuid>ec7757fa-ef67-41bd-80ea-0ba2d9226777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descope Justification'])[1]/preceding::a[1]</value>
      <webElementGuid>2c805d0c-e048-4073-88ce-c4310c44f088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By'])[1]/preceding::a[2]</value>
      <webElementGuid>77e99fa7-bca3-419d-a78a-1c3b0e9fdbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Scope Status']/parent::*</value>
      <webElementGuid>fbf25350-afad-455b-99b7-8a8dc8832c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/a</value>
      <webElementGuid>1a9c1f90-d285-468c-827a-b4b864598b54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
