<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>d62ac94d-cdbb-4980-8147-c9876aa5c6e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B175954672084228777</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B175954672084228777']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcb8c07b-11a0-4da2-a7f1-72588347f989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'NEXT',validate:true});</value>
      <webElementGuid>c503496d-9280-43b6-974c-118abba580a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button </value>
      <webElementGuid>f5ab2ac7-ba9d-4dfa-86b8-1cd326b1c8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cea8d95d-7d07-4241-9ed1-7f026a81ddf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B175954672084228777</value>
      <webElementGuid>6d2fb827-f301-41da-829b-a61d613495ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next ></value>
      <webElementGuid>58877d64-5f58-47b7-8d35-0073da982a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B175954672084228777&quot;)</value>
      <webElementGuid>0b0b6374-53b3-4fe8-9185-f0a34e1daf3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B175954672084228777']</value>
      <webElementGuid>463398ae-3d1e-4842-bead-f0d5254bbbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R175731513904722215']/div/div[2]/button[2]</value>
      <webElementGuid>cef32ebd-b192-4ec2-a447-e71a98ad2e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>774d18c5-4caf-4053-970d-892c50aa7953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B175954672084228777' and (text() = 'Next >' or . = 'Next >')]</value>
      <webElementGuid>11c6d317-3a64-413e-993e-960d7bd01b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
