<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Role GroupRole NameRole DescriptionP_7357ab</name>
   <tag></tag>
   <elementGuidId>95e08795-3f29-4d13-8877-e12081e9e7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R334944232597190400_column_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'R334944232597190400_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'Role GroupRole NameRole DescriptionPrimary OwnerSecondary OwnerAttribute TypeAttribute Value' or . = 'Role GroupRole NameRole DescriptionPrimary OwnerSecondary OwnerAttribute TypeAttribute Value')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>78a926e0-9df4-47df-a321-9d21c2472555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R334944232597190400_column_name</value>
      <webElementGuid>51e23987-5ecd-4d88-83af-7b622883c5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>86d6ec20-298d-4d1a-a429-ab4dd31cb9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>43c2d9d1-edc7-4a76-887a-07e222eb083a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a1543063-b9e6-42f7-a20a-6bba0de615f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>03eafeae-3fbb-4cf8-bf21-11348d1a250f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role GroupRole NameRole DescriptionPrimary OwnerSecondary OwnerAttribute TypeAttribute Value</value>
      <webElementGuid>fff4fa51-2f0a-42df-94d9-4045a0793ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R334944232597190400_column_name&quot;)</value>
      <webElementGuid>b0470e4e-8b8e-4d06-8e79-7e986bb96a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'R334944232597190400_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'Role GroupRole NameRole DescriptionPrimary OwnerSecondary OwnerAttribute TypeAttribute Value' or . = 'Role GroupRole NameRole DescriptionPrimary OwnerSecondary OwnerAttribute TypeAttribute Value')]</value>
      <webElementGuid>d8313e57-af09-4e34-9c4a-b98640a51e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='R334944232597190400_column_name']</value>
      <webElementGuid>bf876dd1-046e-4fa0-8fa4-db61174ab51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column'])[2]/following::select[1]</value>
      <webElementGuid>1f633cf6-029f-4b46-a736-bc280cffe4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row'])[1]/following::select[1]</value>
      <webElementGuid>5a72ad9a-947e-484a-b4d6-e0005b842471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator'])[1]/preceding::select[1]</value>
      <webElementGuid>4762ecd5-9857-423d-a0e4-9c9b55552db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator'])[2]/preceding::select[2]</value>
      <webElementGuid>87bfca30-d4c8-42af-9130-de1e643720f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>d2070805-d579-4864-8684-1377576903bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R334944232597190400_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>318c6a0e-aa61-4144-9ade-cc4c1379ad0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
