<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EBiz_User_JDBC</name>
   <tag></tag>
   <elementGuidId>7f4f842b-2e60-42fa-b71b-574ca5484189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.u-tL > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'EBiz_User_JDBC')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;EBiz_User_JDBC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e289bed2-8d6c-4b2a-8d36-73d1ba253bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1120:10:16510122368938:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:353601,5888,5888,353601&amp;cs=3nJVqZuJLPoQAjfppiJt5JkRrjTBTNXIAd-Fdf2nf_bOoS7snVnQXol-tGrwlOoqrZxbcoYs71FwOWth5PuIelA</value>
      <webElementGuid>34a29f53-b45b-44e4-bf19-4482a829bb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EBiz_User_JDBC</value>
      <webElementGuid>487f9bcf-8896-42ac-9b85-b89786816b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;122864437533293003_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>ededcbfc-62cb-46c6-b7e4-5c40bbfd847a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1120:10:16510122368938:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:353601,5888,5888,353601&amp;cs=3nJVqZuJLPoQAjfppiJt5JkRrjTBTNXIAd-Fdf2nf_bOoS7snVnQXol-tGrwlOoqrZxbcoYs71FwOWth5PuIelA' and (text() = 'EBiz_User_JDBC' or . = 'EBiz_User_JDBC')]</value>
      <webElementGuid>7e12f14e-f0a6-44bc-90dc-2dd766bcf296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='122864437533293003_orig']/tbody/tr[2]/td/a</value>
      <webElementGuid>c42e2280-3be2-48e0-ac36-831398dd1580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EBiz_User_JDBC')]</value>
      <webElementGuid>4e7b2d0d-0e12-4489-b06b-5f1e68db272e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alter Audit SQL'])[1]/following::a[8]</value>
      <webElementGuid>2be7bcce-faef-4839-be2c-6b037af4e67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Audit SQL'])[1]/following::a[9]</value>
      <webElementGuid>247157bb-9f2e-4d56-a8eb-ffd01876c908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EBizApp_JDBC_ObjSet'])[1]/preceding::a[1]</value>
      <webElementGuid>c57577de-1016-4a37-b03f-a4936d3dab93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXSP_USER_EBSAPPL_V'])[1]/preceding::a[1]</value>
      <webElementGuid>a0f11f24-72c1-4ed6-97c9-50d93034d80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1120:10:16510122368938:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:353601,5888,5888,353601&amp;cs=3nJVqZuJLPoQAjfppiJt5JkRrjTBTNXIAd-Fdf2nf_bOoS7snVnQXol-tGrwlOoqrZxbcoYs71FwOWth5PuIelA')]</value>
      <webElementGuid>43941a5a-4eec-4f51-a071-489e0ec6e0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>88e72f47-922a-4a97-9d26-c922537e44fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
