<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EBiz_User_Entry_Attribute_JDBC</name>
   <tag></tag>
   <elementGuidId>eebacc73-a01b-4182-93b4-5dd2e9bdf254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.u-tL > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'EBiz_User_Entry_Attribute_JDBC')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;EBiz_User_Entry_Attribute_JDBC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>111da352-5180-4551-8453-a48b4bd7780a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1120:10:16713337903154:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:353711,5888,5888,353711&amp;cs=3pxVbhbGKOn01r-5lxewenAjqnHBtJO0NtpHANAa1EPy-pdYuiBPTfGHs1gNhm5x5J7bCSI1Fpio27zJIlJyaSw</value>
      <webElementGuid>03f18a11-1e96-4ce5-aea2-145e2526fe1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EBiz_User_Entry_Attribute_JDBC</value>
      <webElementGuid>f19b2820-cce3-4685-90b2-73b8ecbd6d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;122864437533293003_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>b67c01b0-2304-49af-aa18-e82e1b0eba7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1120:10:16713337903154:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:353711,5888,5888,353711&amp;cs=3pxVbhbGKOn01r-5lxewenAjqnHBtJO0NtpHANAa1EPy-pdYuiBPTfGHs1gNhm5x5J7bCSI1Fpio27zJIlJyaSw' and (text() = 'EBiz_User_Entry_Attribute_JDBC' or . = 'EBiz_User_Entry_Attribute_JDBC')]</value>
      <webElementGuid>8ba0d5e7-0658-417a-ab8c-eb1e994143c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='122864437533293003_orig']/tbody/tr[2]/td/a</value>
      <webElementGuid>bd2ab033-e2e5-4fa2-82eb-3f1a2abb580e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EBiz_User_Entry_Attribute_JDBC')]</value>
      <webElementGuid>2da23fde-89b6-428f-8762-9f28975960c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alter Audit SQL'])[1]/following::a[8]</value>
      <webElementGuid>7f0017ab-4137-4dd8-9121-2c7a2ed8f00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Audit SQL'])[1]/following::a[9]</value>
      <webElementGuid>4d755f49-30d0-4119-974a-2ae0ed0858e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EBizApp_JDBC_ObjSet'])[1]/preceding::a[1]</value>
      <webElementGuid>dd81e5d3-757a-4f60-946c-4acfa38327c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXSP_USERENTRYATTR_EBSAPPL_V1'])[1]/preceding::a[1]</value>
      <webElementGuid>cf8356f2-f2ff-440f-940c-8a5ce62c2cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EBiz_User_Entry_Attribute_JDBC']/parent::*</value>
      <webElementGuid>d9a4cc60-a3b0-4b31-a5b8-9fff55868f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1120:10:16713337903154:::RP,10:P100_OBJECTS,P100_ENVIRONMENT,FW_GROUP_ID,P10_OBJECT_ID:353711,5888,5888,353711&amp;cs=3pxVbhbGKOn01r-5lxewenAjqnHBtJO0NtpHANAa1EPy-pdYuiBPTfGHs1gNhm5x5J7bCSI1Fpio27zJIlJyaSw')]</value>
      <webElementGuid>563058b7-998f-4b03-a0d4-59a3bb863035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>dfee04d6-d2d6-427d-8929-8924b2727f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
