<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_KATALON_ADMIN</name>
   <tag></tag>
   <elementGuidId>3500f08d-13a3-48ee-b145-d40799e3fa93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'KATALON_ADMIN' or . = 'KATALON_ADMIN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7f127cf1-465b-4402-85ee-9acf85e55b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-tC</value>
      <webElementGuid>a79c6829-e475-4e70-ba5e-81baa38c04e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>C159502074751191948</value>
      <webElementGuid>90ab86b6-a7fe-4515-a0a3-d8bd31999062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KATALON_ADMIN</value>
      <webElementGuid>e0f48e60-f56d-4aad-9826-573d5ec6fdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;325069098919960516_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tC&quot;]</value>
      <webElementGuid>f6d6b254-7469-45c2-9f96-43f455c87d09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'KATALON_ADMIN' or . = 'KATALON_ADMIN')]</value>
      <webElementGuid>5db7db8d-7345-453d-9d43-04f22de1c945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='325069098919960516_orig']/tbody/tr[2]/td[7]</value>
      <webElementGuid>24daecab-9801-4162-8a74-76cdcec2fbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MCD NZ Business Unit'])[1]/following::td[1]</value>
      <webElementGuid>ad1dbea4-8418-4880-8fa3-24bc40b7a372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUSINESS UNIT'])[1]/following::td[2]</value>
      <webElementGuid>0ccdde58-f22e-4a1a-9316-8e5014e9e52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MARIAB1'])[1]/preceding::td[1]</value>
      <webElementGuid>841b6a0e-3136-4e80-8e01-fd0fe4c49509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[1]/preceding::td[2]</value>
      <webElementGuid>56c55f87-7646-4d31-953b-986faebc0f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KATALON_ADMIN']/parent::*</value>
      <webElementGuid>2574b01f-eaa3-4b26-b428-f0e54f570c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>81032734-98ab-4e80-aa4e-597b110a9ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
