<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KTLN_CloudERP (1) (4)</name>
   <tag></tag>
   <elementGuidId>0ed4c558-6667-4c41-9a71-96021ad8e054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R165933950441227138_sort_widget_rows']/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e449269f-c5cc-4094-b8e8-acf17631d193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7a6669c1-3357-4eb6-bc33-2d721ae11e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-return-value</name>
      <type>Main</type>
      <value>KTLN_CloudERP</value>
      <webElementGuid>75fc1625-3101-40ef-b83e-a91bb7de2814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-sortWidget-row</value>
      <webElementGuid>a9ec9be6-b2c4-4be7-a4eb-98b95908682c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KTLN_CloudERP</value>
      <webElementGuid>099b460c-2938-4101-b559-7141503ba05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R165933950441227138_sort_widget_rows&quot;)/a[@class=&quot;a-IRR-sortWidget-row&quot;]</value>
      <webElementGuid>2444e692-fc85-40fc-95c6-9b9882e3b7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/deba2/RuleCreation_Import/Page_Activity Entries/iframe (2)</value>
      <webElementGuid>d1414566-4375-4e9e-9c8e-422ceb71efd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R165933950441227138_sort_widget_rows']/a[3]</value>
      <webElementGuid>f0cdb83c-8109-4b9d-be17-12256af1482f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KTLN_CloudERP')]</value>
      <webElementGuid>df38f8b7-e47b-48ca-a016-a51806c46270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>bd8e3011-c0a3-4dae-b9ec-ed60293b9de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>cdd5d83b-dbc5-4654-a533-d7db072572fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'KTLN_CloudERP' or . = 'KTLN_CloudERP')]</value>
      <webElementGuid>d089c954-6b36-4c75-ad00-01dbcd7f016b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
