<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>2bc8ba6e-adb0-4773-8683-b07d1a42cdd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Entry Details&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_2']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cc8188f5-4e77-44ec-b95f-f6af8ed12990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>f?p=1180:206:33671175534202::::P206_ENTRY_NAME,P206_ENTRY_TYPE_ID:AP_HOLD_INVOICE_FROM_APPROVAL_TASK_FLOW_PRIV,121&amp;cs=1D127EC59C8B8B5EFD5E4D0B8E7135913&amp;p_dialog_cs=6GcqV2tjFX_lQi3ALePJdwpNYEab_mdOFQETMxutYtpwtdT5YoUB_zuI7o3swXZ0Haipn1OG12YDiAtBM27BUA</value>
      <webElementGuid>a56f7642-f124-4789-bf53-c4d6c3ba96be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Entry Details</value>
      <webElementGuid>dde498c9-32d8-401d-ae88-09e4b4deb339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>43650a89-89fc-4621-945a-6f41571db351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>34dacd96-0053-47ba-aa03-b58c2570ecbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>63f23bd0-3563-446a-9efc-62f66486794e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_2&quot;)/iframe[1]</value>
      <webElementGuid>07a7d489-2684-4f5f-965f-7fcd3047da91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_2']/iframe</value>
      <webElementGuid>3fe1a2df-998f-4c2d-8183-a56c973b78f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c6022712-a5d7-457b-a581-b1e093aadd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'f?p=1180:206:33671175534202::::P206_ENTRY_NAME,P206_ENTRY_TYPE_ID:AP_HOLD_INVOICE_FROM_APPROVAL_TASK_FLOW_PRIV,121&amp;cs=1D127EC59C8B8B5EFD5E4D0B8E7135913&amp;p_dialog_cs=6GcqV2tjFX_lQi3ALePJdwpNYEab_mdOFQETMxutYtpwtdT5YoUB_zuI7o3swXZ0Haipn1OG12YDiAtBM27BUA' and @title = 'Entry Details']</value>
      <webElementGuid>1d5e1452-88eb-4045-a460-688cfdce4a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
