<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Key</name>
   <tag></tag>
   <elementGuidId>c227f0cd-fa74-4348-a9ab-1e9e48c55f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C146571352911766611_HDR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Key' or . = 'Key')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>377da407-d1cc-4735-bbf5-56f14c66e9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-headerLabel</value>
      <webElementGuid>b4b4ef86-8126-48e6-99d6-ad40cc722807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C146571352911766611_HDR</value>
      <webElementGuid>803f6a32-1a97-4533-9805-6ba0753d357d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Key</value>
      <webElementGuid>280324ee-53de-4b08-980d-47a003395473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C146571352911766611_HDR&quot;)</value>
      <webElementGuid>36bef346-9297-4b1d-b47a-6ddc19f5ce61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Key' or . = 'Key')]</value>
      <webElementGuid>b866a9c4-a869-488e-9a17-b59e953e25e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='C146571352911766611_HDR']</value>
      <webElementGuid>7c747132-cb61-4ff5-9d35-893d2708c157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='oItemsSodIg_ig_grid_vc_cur']/span</value>
      <webElementGuid>9e898ba5-75ca-4495-a449-9791ce65482a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datatype'])[1]/following::span[1]</value>
      <webElementGuid>e8a42100-3c3f-47f4-bb99-d7e5a4696972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column Name'])[1]/following::span[2]</value>
      <webElementGuid>c17736cb-cb29-411e-8dd4-d46cd91aeb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Translation Function'])[1]/preceding::span[3]</value>
      <webElementGuid>7c144303-053f-406e-a685-4dd3ec9ffdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found'])[1]/preceding::span[6]</value>
      <webElementGuid>f42f1b2c-70dc-4a8f-abd0-0219c34f450c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Key']/parent::*</value>
      <webElementGuid>cb71769a-8e5e-46eb-9c0a-2bd7d0f4b270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[9]/span</value>
      <webElementGuid>028bc21d-abfa-482c-a1e1-b047fc5af377</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
