<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_katalon_admin - 121</name>
   <tag></tag>
   <elementGuidId>9eb3f69a-f742-4732-a3fe-048a61db9e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L14205299837764170</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/header/div[1]/div[3]/ul/li[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'L14205299837764170' and (text() = '
      katalon_admin
  ' or . = '
      katalon_admin
  ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bb5a0ff-be57-49a4-9669-ad844e08f021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button t-Button--header t-Button--navBar js-menuButton</value>
      <webElementGuid>14e07925-c7ee-440f-8f8e-0872439b19f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77090fcb-ac82-4251-a17d-b74a5221067a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L14205299837764170</value>
      <webElementGuid>43878f7f-fe25-4eb7-a4e7-e3d6b941ffd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>menu_L14205299837764170</value>
      <webElementGuid>d12554aa-8708-4313-a955-1445b42efd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>b3d3d816-0fab-467a-b85b-45a65ce36597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      katalon_admin
  </value>
      <webElementGuid>68ded5e7-d579-4b05-bac4-70bcb2d66e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L14205299837764170&quot;)</value>
      <webElementGuid>d6afacd1-b7f6-4a0d-8099-58a1f3466f4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='L14205299837764170']</value>
      <webElementGuid>6203a330-38b6-44fa-ac3a-0165caad69b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='14205299837764168']/li[2]/button</value>
      <webElementGuid>be75f655-9045-4f13-9fcd-8d988b9d6614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>87e6984a-9bf1-4cc5-9164-854f5eb60dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'L14205299837764170' and (text() = '
      katalon_admin
  ' or . = '
      katalon_admin
  ')]</value>
      <webElementGuid>4b0a11a2-e71a-4c75-b4fa-e3a6db69d1dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
