<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Roles Manager_a-TreeView-toggle</name>
   <tag></tag>
   <elementGuidId>f573a6cf-aa3d-48b8-bf03-5acc523de463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_8']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_8 > span.a-TreeView-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>197a96b9-f4e2-44bf-b8c8-48fa4f669637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>7eb73d17-e147-4799-81c5-dad219be4b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_8&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>fc12d42b-ec09-4cab-81d1-f1b2afe7a35e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_8']/span</value>
      <webElementGuid>c1951e88-db78-4720-9de6-f12c1b6bace5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/span</value>
      <webElementGuid>56f6c6b1-d9f8-42f9-9ea4-0365c43e4104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
