<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Refresh</name>
   <tag></tag>
   <elementGuidId>ea9d6fcd-2379-40ff-afc3-897c5b7a0564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B162772706518928170</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and @id = 'B162772706518928170' and (text() = 'Refresh' or . = 'Refresh')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10a0e1d5-0eed-46aa-95db-6bc67a8405b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'REFRESH',validate:true});</value>
      <webElementGuid>bdf14e1c-b036-4a22-b370-cb190f49b6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button </value>
      <webElementGuid>5c162370-c13a-4953-94ff-cbdeafa3e56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff6f475d-d7a7-4850-98ca-b4ff824a41c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B162772706518928170</value>
      <webElementGuid>0b74cac1-6da6-4e05-b361-6734382bb41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>a061155d-81c4-4792-9c21-ef5d7a6814ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B162772706518928170&quot;)</value>
      <webElementGuid>6955fb79-4adb-4833-9029-9f744ceda6b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B162772706518928170' and (text() = 'Refresh' or . = 'Refresh')]</value>
      <webElementGuid>084c59ab-c9d0-4897-9d12-3ce9b8160243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B162772706518928170']</value>
      <webElementGuid>e83f6fb2-a5cd-4a4a-91f8-0baf02589f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 4 of 4 - Violations Review'])[1]/following::button[1]</value>
      <webElementGuid>bb1c7abb-054e-48f6-b1e0-e109bfd4188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_CloudERP'])[1]/following::button[1]</value>
      <webElementGuid>c984b782-d275-4f61-8150-0769cd32d045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::button[2]</value>
      <webElementGuid>e235d852-f65f-480d-b423-d07299951078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>63da25fa-8fb6-4f1e-80d0-32fe38c131b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R162772252661928166']/div/div[2]/button</value>
      <webElementGuid>ff248dcf-6576-4e89-8326-7b43c2570bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
