<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_ToggleEditAccess Group equals Identity_Group1</name>
   <tag></tag>
   <elementGuidId>bb6f5381-b5cb-4c34-9c87-209e72470908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.a-IG-controls</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[(text() = 'ToggleEditAccess Group equals Identity_Group1' or . = 'ToggleEditAccess Group equals Identity_Group1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>9aedecb1-acd0-4a20-a84e-5c4ea312513c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IG-controls</value>
      <webElementGuid>afc2ef4e-bcbb-49e5-baa4-fe5680a9128f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToggleEditAccess Group equals Identity_Group1</value>
      <webElementGuid>2f6a3429-0813-406e-b7cb-8876c00280fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a_Collapsible1_uacReport_ig_report_settings_content&quot;)/ul[@class=&quot;a-IG-controls&quot;]</value>
      <webElementGuid>431b33fb-75b5-415c-b203-8bdc6713dbc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'ToggleEditAccess Group equals Identity_Group1' or . = 'ToggleEditAccess Group equals Identity_Group1')]</value>
      <webElementGuid>9490e111-e31c-4c5c-bf85-06b0b2e32c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Settings'])[1]/following::ul[1]</value>
      <webElementGuid>41ce4de2-4d55-451b-a2d0-25a6e8b7db20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::ul[1]</value>
      <webElementGuid>db1a2781-c75b-43b6-b35b-2dde9dd86380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul</value>
      <webElementGuid>b77a86e0-4abc-40a5-a621-83970c571e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a_Collapsible1_uacReport_ig_report_settings_content']/ul</value>
      <webElementGuid>a319d629-3cc8-4376-b487-d23729820c9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
