<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Entries_eRep_search_button</name>
   <tag></tag>
   <elementGuidId>534bf7f0-ad25-4d6e-8c25-e72b13114e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='eRep_search_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eRep_search_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Go&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43527b2f-3cb5-4890-80fc-22b22383f82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eRep_search_button</value>
      <webElementGuid>8e87991a-5536-4d52-905b-955d23697a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--search</value>
      <webElementGuid>339cd13a-86d5-40ac-9822-17e83ab68ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3776d59c-b0aa-40dc-8111-2e7c15b1af6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>808706dc-578b-498a-8b36-ea55cc81e2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eRep_search_button&quot;)</value>
      <webElementGuid>bd3e529a-e4e2-4546-baa4-47fc3b8e3f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='eRep_search_button']</value>
      <webElementGuid>ca096f62-3827-4b7a-bdb6-e2354065fd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eRep_toolbar_controls']/div/div/div[3]/button</value>
      <webElementGuid>bffc8ef4-a543-40b6-b2a5-80279b5b5713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entries'])[2]/following::button[2]</value>
      <webElementGuid>d0e52ee5-bc8d-4015-a394-6651fd3d7865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GRANTFLAG_NO'])[2]/following::button[2]</value>
      <webElementGuid>b868cfde-30e1-4542-9591-8c1d651904dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[3]/preceding::button[1]</value>
      <webElementGuid>11bd0839-d00c-4576-a8fd-c59e9b548941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div/div/div[3]/button</value>
      <webElementGuid>20fbbf14-3522-4196-8307-1c179d66493e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'eRep_search_button' and @type = 'button' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>91052fbe-ec7d-4b8a-8769-2cf5af2a58f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
