<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Report Settings_control_588075250577576698</name>
   <tag></tag>
   <elementGuidId>a9ef76cf-0d3a-4d6b-aa60-eb27bdc15b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @checked = 'checked']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#control_588075250577576698</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox[name=&quot; Toggle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf9c995c-a907-4483-a84c-5726654bae5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-controlsCheckbox</value>
      <webElementGuid>d6f39503-17d2-49ef-a4e8-81b22a9eef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-setting</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>82143557-238a-4bd5-9794-f0263f52c178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filter-id</name>
      <type>Main</type>
      <value>588075250577576698</value>
      <webElementGuid>f06878cf-5fea-4aab-9f2a-6e620a476999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ecf468bc-0b8a-4192-8383-eca9f1b0a7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>control_588075250577576698</value>
      <webElementGuid>515a4c25-87d6-42b3-a289-dd81cce01392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>c03e544a-2538-486a-a4c9-3b5bad7e5110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;control_588075250577576698&quot;)</value>
      <webElementGuid>b10ac38b-b4ed-4a49-93bd-2234dfbdfd8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @checked = 'checked']</value>
      <webElementGuid>064b4a7c-a196-49f0-b328-e537ea9106d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='control_588075250577576698']</value>
      <webElementGuid>2519a5b9-2f49-456b-8c26-42ce8e2a4bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a_Collapsible3_eRep_control_panel_content']/ul/li/span/input</value>
      <webElementGuid>3c787347-6e98-47ef-835e-9ad1b1827e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/ul/li/span/input</value>
      <webElementGuid>fc053653-f920-4164-88ff-02a30153510c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
