<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attribute Detail_attributeCheck (1)</name>
   <tag></tag>
   <elementGuidId>48a23894-c83c-4a6c-bfdd-9853c8721707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attributeCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attributeCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#attributeCheck</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4238196-5b90-47dc-a1b9-7ad45b137ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attributeCheck</value>
      <webElementGuid>53f709b8-624a-49cf-9c80-cdcf12314a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>75ca90a6-5e12-4689-a78e-5e1eb12be7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Not Excluded</value>
      <webElementGuid>acd43184-327d-4bda-a867-a58dccc905c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attribute_id</name>
      <type>Main</type>
      <value>3895111</value>
      <webElementGuid>63e6a6d2-e971-4731-90c0-a54abc74de35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attributeCheck&quot;)</value>
      <webElementGuid>0f72b9eb-01b4-4757-84e8-0c0453092392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attributeCheck']</value>
      <webElementGuid>9a42ed95-3d65-4a76-823b-907b333ed5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='144255460593984823_orig']/tbody/tr[2]/td/input</value>
      <webElementGuid>d1a6a8f4-528d-4118-b1d8-49c213584a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>1c2f6b32-c6eb-4cf5-bc5e-bc07818c577c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'attributeCheck' and @type = 'checkbox']</value>
      <webElementGuid>b335083b-7cf2-4f48-8805-19c436f0d316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
