<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_concat(Row text contains , , EBizApp_af7ab9</name>
   <tag></tag>
   <elementGuidId>c8c7b1f3-c642-48ef-b372-61c9acfd168f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.a-Button.a-IRR-button.a-Button--noUI.a-IRR-button--remove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Remove Filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ca90a2d-6d40-4abf-bc36-62cf41c0c6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-Button--noUI a-IRR-button--remove</value>
      <webElementGuid>f59e127e-6351-496c-82d1-ab3cd045483f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove Filter</value>
      <webElementGuid>9218820a-93a6-4a88-bdc5-eaf0a5cf9990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove Filter</value>
      <webElementGuid>2817e661-472c-48ea-8d7a-046160fcaf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28a6b6b7-f753-47d1-b56f-fcba59de6343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-setting</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>736507e2-ca8f-4d49-a694-e08ad026c7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filter-id</name>
      <type>Main</type>
      <value>678286895197466131</value>
      <webElementGuid>bc37329b-92a1-4bdc-903b-5796e0192ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a_Collapsible1_R137674426230792379_control_panel_content&quot;)/ul[@class=&quot;a-IRR-controls&quot;]/li[@class=&quot;a-IRR-controls-item a-IRR-controls-item--search&quot;]/span[@class=&quot;a-IRR-controls-cell a-IRR-controls-cell--remove&quot;]/button[@class=&quot;a-Button a-IRR-button a-Button--noUI a-IRR-button--remove&quot;]</value>
      <webElementGuid>4c3655a6-ebdb-4042-a95b-67feed6e8a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Remove Filter' and @type = 'button']</value>
      <webElementGuid>7a73ec51-4cb6-4a0d-95d3-72021145666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>667b2953-f59d-41bc-843f-7a5c23705572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a_Collapsible1_R137674426230792379_control_panel_content']/ul/li/span[4]/button</value>
      <webElementGuid>839668d7-a51d-42a2-9d34-e9ef284451f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle'])[1]/following::button[1]</value>
      <webElementGuid>318a5a54-1037-4c48-be91-9c927cfffd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EBizApp_JDBC_ObjSet'])[1]/preceding::button[1]</value>
      <webElementGuid>cec35287-a5a1-4267-aaf5-e9ae4ef5f4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object Set'])[1]/preceding::button[1]</value>
      <webElementGuid>fcbbce47-36a6-4f88-a7ff-4366e9fc05e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/button</value>
      <webElementGuid>118a764d-e7c6-42e7-a57b-c4733552f07e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
