<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AU - ERP Cloud - Tax Analyst (2)</name>
   <tag></tag>
   <elementGuidId>e97e4828-505e-4f06-b1f6-ff5fb6b89437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='R326052387980911517_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R326052387980911517_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3c72b10a-dfa9-4779-a240-fd1393339cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>3ed49eb7-1b5b-40c0-9a5d-92a917a8191c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5224f46e-bc46-43e2-8d9a-8bbfeedf6a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tC is-focused</value>
      <webElementGuid>76dee9d5-8a88-4522-9808-aea0fb245654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R326052387980911517_ig_grid_vc_ctx C326053435412911527_HDR R326052387980911517_ig_grid_vc_cur</value>
      <webElementGuid>190d9e55-8b99-4b91-8306-71b9d617f4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R326052387980911517_ig_grid_vc_cur</value>
      <webElementGuid>b7299ba8-40fd-4ea4-8544-f6dbfb0d5edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AU - ERP Cloud - Tax Analyst</value>
      <webElementGuid>ae6eb38e-ae61-499b-ab16-921dee2d19fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R326052387980911517_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>2cfa4a21-6358-4540-8159-b5575a4f5eac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R326052387980911517_ig_grid_vc_cur']</value>
      <webElementGuid>53e55c82-7ceb-42f0-b7f0-5e57a55e4a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R326052387980911517_ig_grid_vc']/div[3]/div[4]/table/tbody/tr[10]/td</value>
      <webElementGuid>b0345f71-af66-4d81-aaef-12787dcde170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[3]/following::td[1]</value>
      <webElementGuid>fecd3034-16de-45c6-a09c-ac26e668aedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NZ - ERP Cloud - Asset Accounting Manager (Approval Required)'])[2]/following::td[2]</value>
      <webElementGuid>ffd91e55-3855-4d0c-9d74-fbe1fcb5586a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU - ERP Cloud - Tax Analyst'])[2]/preceding::td[1]</value>
      <webElementGuid>0bc5564a-f24b-4a4e-ab92-d95b634cfb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[4]/preceding::td[2]</value>
      <webElementGuid>e453875d-d23c-4653-8d29-0615d2dcea1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AU - ERP Cloud - Tax Analyst']/parent::*</value>
      <webElementGuid>e0798083-1895-47ad-bd84-dbfa7a06a0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td</value>
      <webElementGuid>7a9f8edb-b1a8-42f7-9a8d-8c7bd43d2988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'R326052387980911517_ig_grid_vc_cur' and (text() = 'AU - ERP Cloud - Tax Analyst' or . = 'AU - ERP Cloud - Tax Analyst')]</value>
      <webElementGuid>f7ee008f-3691-4afa-bc4c-450c386860b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
