<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AU - ERP Cloud - Support Project Data Sp_a69d2b</name>
   <tag></tag>
   <elementGuidId>d4b8728f-1b6f-4f37-abaa-1531d970e34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report_scopeRoles']/div/div/table/tbody/tr[10]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bf5c918d-5140-414a-8f80-492dcfa7ab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Report-cell</value>
      <webElementGuid>5e86b0b9-dd32-4ac3-9416-e17c2de5f44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>ROLE_NAME</value>
      <webElementGuid>3166c11b-7e6c-42cb-ab78-e90753447c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AU - ERP Cloud - Support Project Data Specialist (Approval Required)</value>
      <webElementGuid>b4b0646e-b6db-4ead-b3a4-201b084af325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_scopeRoles&quot;)/div[@class=&quot;t-Report-wrap&quot;]/div[@class=&quot;t-Report-tableWrap&quot;]/table[@class=&quot;t-Report-report&quot;]/tbody[1]/tr[10]/td[@class=&quot;t-Report-cell&quot;]</value>
      <webElementGuid>2274233f-09df-40f7-ba0d-8f99e61da0f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_scopeRoles']/div/div/table/tbody/tr[10]/td[2]</value>
      <webElementGuid>52c8a3f7-0fc4-4c0a-8bf5-94e077325791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1'])[18]/following::td[2]</value>
      <webElementGuid>a3bf538c-7688-4a89-bdd1-159bf1e1e4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1'])[17]/following::td[4]</value>
      <webElementGuid>2df9d604-757b-4b0e-b6fe-e7eda8b702e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU - ERP Cloud - Support Project Data Specialist (Approval Required)'])[2]/preceding::td[1]</value>
      <webElementGuid>9bab49f9-d193-4b40-b06c-ca309da49402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1'])[19]/preceding::td[4]</value>
      <webElementGuid>de971977-c2dd-4628-a7ff-1bf84132075b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AU - ERP Cloud - Support Project Data Specialist (Approval Required)']/parent::*</value>
      <webElementGuid>022419e1-0c2f-4ac7-a00b-c9bd766f6036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]</value>
      <webElementGuid>b837aff6-fb28-4fcd-8ce7-3a4392ddc84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AU - ERP Cloud - Support Project Data Specialist (Approval Required)' or . = 'AU - ERP Cloud - Support Project Data Specialist (Approval Required)')]</value>
      <webElementGuid>1ae71abd-94c1-4e99-971b-dc95b9600b6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
