<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log Time_LOG_REPORT_toolbar_controls</name>
   <tag></tag>
   <elementGuidId>048bcbf9-145c-4a84-a4e2-a34d8022c66c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LOG_REPORT_toolbar_controls</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LOG_REPORT_toolbar_controls']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search bar of Log&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97a368f8-0a84-4855-822f-84de5bb490ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d494af29-0efe-4c04-814f-ff7454c1a1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search bar of Log</value>
      <webElementGuid>c4b3e42b-c09e-4ab8-855b-339c4cb258d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LOG_REPORT_toolbar_controls</value>
      <webElementGuid>cc5875f4-08d7-416a-ab89-d398389faf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-controls</value>
      <webElementGuid>f4a5b44a-c96b-4eb5-93c4-0a3ae9ee2e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go1. Primary Report2. Group by Application and ProgramActions</value>
      <webElementGuid>67c107ea-8a31-4c9d-bc9c-2dca500b77a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LOG_REPORT_toolbar_controls&quot;)</value>
      <webElementGuid>c906cf83-22bc-4f22-a20e-f84fb145fc0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='LOG_REPORT_toolbar_controls']</value>
      <webElementGuid>6939cabd-9596-4998-a1d1-40436fbad277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LOG_REPORT_toolbar']/div</value>
      <webElementGuid>0f200f09-6ae7-4d54-abbc-4a68fbece89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Time'])[1]/following::div[8]</value>
      <webElementGuid>98d0f413-6111-4480-a890-83b28c7b7f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::div[12]</value>
      <webElementGuid>f6a40d9b-21f1-48c7-9997-183766e6b6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>5bdd04bb-e3f0-4539-b310-1e33e1c47ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'LOG_REPORT_toolbar_controls' and (text() = 'Go1. Primary Report2. Group by Application and ProgramActions' or . = 'Go1. Primary Report2. Group by Application and ProgramActions')]</value>
      <webElementGuid>8b3be0d3-dbdd-4441-a788-ebc3dc2f3071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
