<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Last Updated By</name>
   <tag></tag>
   <elementGuidId>ea998050-e3a4-4abc-a7df-a2ea742d57b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C176873556703839130 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='C176873556703839130']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2a3c245-df84-462c-b06b-73d8fe915554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>0c3e1fe7-5e38-4483-b0a9-50c943664e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>176873556703839130</value>
      <webElementGuid>17c3df95-150e-40ec-8afc-9ce4042335ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>be999508-9c65-4d23-ae7c-6b4325cce39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Updated By</value>
      <webElementGuid>5e269550-f787-4e56-b104-07605873daec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;176546485571519037&quot;)/tr[1]/th[@id=&quot;C176873556703839130&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>9067e43e-8707-4716-b2b8-599c552019d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MonitorPaaS_CloudERP/MonitorPaaS_Email_Detail/Page_Manage Approvals/iframe</value>
      <webElementGuid>abf2da29-ff12-44b4-bb5e-8d5f9097c656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C176873556703839130']/a</value>
      <webElementGuid>52f700d8-3a54-400f-b16e-f053df4ba499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Last Updated By')]</value>
      <webElementGuid>5c522a43-325d-4570-b99e-c327375c72d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/a</value>
      <webElementGuid>9979e376-f34f-4004-82ec-544aa92f5b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Last Updated By' or . = 'Last Updated By')]</value>
      <webElementGuid>08792ddd-78b2-4e3c-b59e-3313ee5a2c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
