<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_a-TreeView-toggle_1_2</name>
   <tag></tag>
   <elementGuidId>1af019fd-d6da-4e0a-8bbe-d8b5efe0cf5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Access Certification']//preceding::span[@class='a-TreeView-toggle'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_11 > span.a-TreeView-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14da0eee-ce18-4e81-bfe4-7907075c0436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>32ae33df-9060-4580-b6b9-2b4999cc834c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_11&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>91fc0dab-ea88-4cd0-9dc9-79504210605e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_11']/span</value>
      <webElementGuid>c0812eff-4baf-4bd5-887f-67c42bd2df40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/span</value>
      <webElementGuid>68ac96b3-4d40-4c01-a9ab-58d4c8780ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
