<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonR160866911876310713_expression_icon_link (1)</name>
   <tag></tag>
   <elementGuidId>5133c589-0c27-44e6-8ccc-b76b439d3074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R160866911876310713_expression_icon_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/span/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>afd979be-0479-4113-8cf3-20122ad21f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--menu a-IRR-button a-IRR-button--menu</value>
      <webElementGuid>aa8e82f1-33a2-4623-873c-4e399543ffcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>165cca37-0784-4b5a-88af-e4f22faf5061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Popup List of Values: Expression</value>
      <webElementGuid>a3fca170-d9dd-4fe6-8f41-6c3b4623fb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Popup List of Values: Expression</value>
      <webElementGuid>ca35fa22-4ee5-48f9-ad97-dbba9e228416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-picker-for</name>
      <type>Main</type>
      <value>R160866911876310713_expression</value>
      <webElementGuid>c7d25cae-1e41-482c-be3a-269caf979b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R160866911876310713_expression_icon_link</value>
      <webElementGuid>f04c7e92-0fec-43bf-8321-40e61b1b4ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R160866911876310713_expression_icon_link&quot;)</value>
      <webElementGuid>be443ad4-3add-4cbf-8f18-b641b5140c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R160866911876310713_expression_icon_link']</value>
      <webElementGuid>4f5b69d9-52c8-4640-9a03-19b13bc45008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R160866911876310713_expression_container']/div/div[2]/span/button</value>
      <webElementGuid>fc1ed860-8cc0-49e6-8063-15a1ec00db37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/button</value>
      <webElementGuid>561a1002-16d3-4adb-b7c9-d107c8e6e560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Popup List of Values: Expression' and @id = 'R160866911876310713_expression_icon_link']</value>
      <webElementGuid>bf2ef270-4ab9-4f60-b597-10386b1d7826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
