<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actions (1)</name>
   <tag></tag>
   <elementGuidId>7cef3fdf-4796-49c7-8997-cfe99eb48a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R160866911876310713_actions_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0eaee157-261b-4702-b6b0-201da911047b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R160866911876310713_actions_button</value>
      <webElementGuid>b25ed7d1-b7eb-4b01-9667-0c2c973844eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--actions js-menuButton</value>
      <webElementGuid>5c4a3a0a-899e-4ff6-b1fe-10748cf5a25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47124847-7eec-49ed-a7ff-81b7d1b3afc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>R160866911876310713_actions_menu</value>
      <webElementGuid>da0959c2-ecc6-4500-bf2c-b4fc6ec01ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>3d807850-24a5-4db2-9325-6058183d9404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>a2345394-e3e7-4bc1-87b8-89acf0515cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R160866911876310713_actions_button&quot;)</value>
      <webElementGuid>743c7864-c11d-4d8c-bddd-0c1fec52313e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R160866911876310713_actions_button']</value>
      <webElementGuid>85e23727-97e3-4c2b-b9cf-c70698e37b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R160866911876310713_toolbar_controls']/div[3]/div/button</value>
      <webElementGuid>4877c0f7-64c5-4ed9-b5aa-b97e17afb913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>ba839281-8ec9-4b7b-9982-d10f1f8731b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'R160866911876310713_actions_button' and @type = 'button' and (text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>c86d3996-4a8c-486e-8541-13bddc76d158</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
