<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_p_ignore_10</name>
   <tag></tag>
   <elementGuidId>160f53df-d63b-4976-b844-15a405c5173a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='R160866911876310713_expression']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R160866911876310713_expression</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98cebe70-41cc-4e7d-b08a-3fea0f12f8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-text</value>
      <webElementGuid>e55122c5-238c-4798-acae-5b4ebd4db6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R160866911876310713_expression</value>
      <webElementGuid>0eff42d5-1b57-4876-8ddc-afa8a22492de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49d38fd4-679c-4ec2-8f70-a0d596eaca35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>d5905612-a801-45bd-8082-359ad2292533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>d785f46a-e343-414c-9b37-d8d2b3c7b9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R160866911876310713_expression_label</value>
      <webElementGuid>4989f5ab-79f5-463b-8c84-a74cb76dfb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R160866911876310713_expression&quot;)</value>
      <webElementGuid>4e43813f-f3ac-47bb-a3a3-c3acaf8a0d80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='R160866911876310713_expression']</value>
      <webElementGuid>d0b99445-57ad-4f92-8932-95b650842c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R160866911876310713_expression_container']/div/div[2]/span/input</value>
      <webElementGuid>6ced55e4-f369-4bf1-8aff-0bd1258ed43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>beb7b8bf-dc81-4d99-b6e1-2bb54807ca6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'R160866911876310713_expression' and @type = 'text' and @name = 'p_ignore_10']</value>
      <webElementGuid>a64c0de7-6092-402d-9a83-e2f9d0c2662f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
