<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actions (1)</name>
   <tag></tag>
   <elementGuidId>a9302ffc-6402-4019-b3e1-9cfc61962913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R249123015355222332_actions_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R249123015355222332_actions_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14562efd-e90c-4187-9616-59c6257ce74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R249123015355222332_actions_button</value>
      <webElementGuid>5d63f1c7-201f-41c6-a4f6-d905ee221f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--actions js-menuButton</value>
      <webElementGuid>913d36ce-8a36-4c8b-9cae-afd7c21b9beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca165b6f-44e1-4f83-8a45-28ed84e51e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>R249123015355222332_actions_menu</value>
      <webElementGuid>1a611f97-e746-4058-84d1-3c6278d4ce46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>ace42d7b-c105-4034-b184-b126359a7d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>59827abf-29df-4063-a808-b17241989be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R249123015355222332_actions_button&quot;)</value>
      <webElementGuid>d9cf8ac0-c44e-4f9a-8ef2-58054c3ad3e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R249123015355222332_actions_button']</value>
      <webElementGuid>d81e0999-b8b4-4661-bd1e-88c887bb5a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R249123015355222332_toolbar_controls']/div[3]/div/button</value>
      <webElementGuid>7696ccb4-5f2c-4880-ad7b-df397f506c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>ca749c0b-3c9b-475d-961c-4fb5ce42af66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'R249123015355222332_actions_button' and @type = 'button' and (text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>0277ac09-080f-493d-a542-42e33a19623b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
