<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select an Environment -EBizApp_JDB_73a228</name>
   <tag></tag>
   <elementGuidId>a68475a0-f63d-49ea-b82e-b1c653d14272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name = 'P100_ENVIRONMENT' and (text() = '- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
' or . = '- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P100_ENVIRONMENT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f505329-695a-46fb-bc62-f5eec9210409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P100_ENVIRONMENT</value>
      <webElementGuid>2010e081-1dad-4481-ae32-5b8d1ce5c274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P100_ENVIRONMENT</value>
      <webElementGuid>8d99b7b2-aa76-499c-b932-7807de424976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>1d1febde-84d1-43b7-bb2c-e1458cc87074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a5f0608-36e4-456d-8e18-bf8371f81f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>55be8936-a613-4ebd-beae-10e97d00ca80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P100_ENVIRONMENT');</value>
      <webElementGuid>c9343dcc-e726-48bb-bc64-49834e5086be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
</value>
      <webElementGuid>15d24228-f8ed-4998-9a8d-48f624c3bc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P100_ENVIRONMENT&quot;)</value>
      <webElementGuid>f9587044-8795-4692-8093-fc3b56473297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'P100_ENVIRONMENT' and (text() = '- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
' or . = '- Select an Environment -
EBizApp_JDBC_Env
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
SailPoint_ENV2
SailPoint_Env
TEST_DEV1_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
')]</value>
      <webElementGuid>17f57085-6812-4b58-858c-58f9e5595ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P100_ENVIRONMENT']</value>
      <webElementGuid>b0bba9e5-561d-4c93-a483-536ae0e084f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P100_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>cd7acac5-f737-4dad-99c8-cebbcc71d0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>2b88c688-3414-4a7a-bbf7-ad23166d17aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>f5fbb710-e8d5-4a57-bbc2-714682f4c790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Type Version'])[1]/preceding::select[1]</value>
      <webElementGuid>cdaffc57-23ae-48fe-ae52-57c439dda045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oracle Cloud ERP 20x'])[1]/preceding::select[1]</value>
      <webElementGuid>a90844fb-4c4c-43ed-b903-a9bea41c5b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>cec2e9ce-ba84-468b-b1ea-2c53ab30f4dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
