<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter (1)</name>
   <tag></tag>
   <elementGuidId>e3de3d3b-fb94-453c-9730-4fcda91660a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R163105974055422926_actions_menu_2i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R163105974055422926_actions_menu_2i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61ab3bfb-4249-44c5-9ecd-0edae361c113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d605b1a-96ff-4f34-a3a0-1030c38491b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R163105974055422926_actions_menu_2i</value>
      <webElementGuid>922cf474-e791-4893-99fe-6230f7e4d3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>d260f9da-333c-47de-a932-64ef501e4fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>dcbb6559-6da7-4c45-a810-402f9614dfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>ffd45a39-84f8-41df-8931-1974e2371646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R163105974055422926_actions_menu_2i&quot;)</value>
      <webElementGuid>045fd6dd-6817-42b4-9946-12f6f3035b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R163105974055422926_actions_menu_2i']</value>
      <webElementGuid>b8f0e268-774a-4a43-b9e5-be92b3298407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='R163105974055422926_actions_menu_2']/div/span/button</value>
      <webElementGuid>2844db42-d5ed-4b37-b4aa-db0667e373eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/button</value>
      <webElementGuid>06f8c91f-7c1c-4884-8c9a-3078fd32943b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'R163105974055422926_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>3e57ac93-7965-4758-b706-74e6dea38a64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
