<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_P68_FILE_CONTENT</name>
   <tag></tag>
   <elementGuidId>a97238ce-ccca-40bb-afa6-ead877de5a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P68_FILE_CONTENT</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'file' and @id = 'P68_FILE_CONTENT' and @name = 'P68_FILE_CONTENT']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P68_FILE_CONTENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4a5fa58-a8f5-4cb2-80ed-409b8adacb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a01887a1-888d-430a-a174-e4483326e8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P68_FILE_CONTENT</value>
      <webElementGuid>cfd39e2c-da21-49e6-b2f3-46c1e7c156cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P68_FILE_CONTENT</value>
      <webElementGuid>5269a423-a574-4fb5-aae5-5825795404e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file apex-item-file apex-item-file--native</value>
      <webElementGuid>cbb64dd0-ab24-4156-8bf6-9e0853a5a459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-style</name>
      <type>Main</type>
      <value>NATIVE</value>
      <webElementGuid>a4ec4c31-73ef-40ef-81dc-f3014b992673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-caption</name>
      <type>Main</type>
      <value>Choose File</value>
      <webElementGuid>0769eafd-7e5e-48ce-b514-8c4c8372a299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.csv</value>
      <webElementGuid>9d6591b6-e83d-46fc-abf4-98940e4f936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>1ba26472-7e96-4cc0-80cf-50b8df81c016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P68_FILE_CONTENT&quot;)</value>
      <webElementGuid>0b675a08-0bf3-4b2d-b06b-443eb10eb010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P68_FILE_CONTENT']</value>
      <webElementGuid>3edc30cf-a666-445c-9767-42b190633409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P68_FILE_CONTENT_GROUP']/input</value>
      <webElementGuid>3fe2e9c8-e879-43e7-a1c4-9537e45d314e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>39e51334-76e1-47ee-b263-fd6cc08f2a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'P68_FILE_CONTENT' and @name = 'P68_FILE_CONTENT']</value>
      <webElementGuid>62d20117-b1ee-4f34-b8ab-9b009d3d622b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
