<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_P68_LOAD_NAME</name>
   <tag></tag>
   <elementGuidId>44bf52fd-39ab-4a92-8ad4-36f3fc9c893a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P68_LOAD_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P68_LOAD_NAME']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'P68_LOAD_NAME' and @name = 'P68_LOAD_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be8c99f6-9734-42ef-919b-81754b0f6a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f58a9482-9e0c-4dfe-8349-3e3ab1fc7e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P68_LOAD_NAME</value>
      <webElementGuid>3fccc456-854c-4bc2-aa3f-9533726c7459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P68_LOAD_NAME</value>
      <webElementGuid>d1106104-fa73-4088-88ee-6de7076d54e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>95965d6f-047d-442d-a58d-05fa6a649ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>d055b66d-e72f-4c54-8ffd-f9395b893311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>9c222752-2bd2-48c3-9c5d-ee87730d3b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>cf9bccd7-2bd2-4562-841b-30b27764f54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P68_LOAD_NAME&quot;)</value>
      <webElementGuid>5e93c3c1-c615-4f46-b309-5d356c25b3e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P68_LOAD_NAME']</value>
      <webElementGuid>140f0bb1-74a6-4cf2-8afb-95a9330793a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P68_LOAD_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>2dff8e10-ca39-419c-b095-875ece893c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>68dc58f4-232f-48b3-b22f-4dddbe9c2a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P68_LOAD_NAME' and @name = 'P68_LOAD_NAME']</value>
      <webElementGuid>f0ce5ffc-dd93-4719-b0bd-e23d38ac527b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
