<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NameDescriptionEnd Date ActionStatus_a82897</name>
   <tag></tag>
   <elementGuidId>527bc5ac-5b9a-4c52-bc84-86630f72e90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mngSnap_column_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mngSnap_column_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a841a9f0-8b99-478a-baa1-957cb733b7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mngSnap_column_name</value>
      <webElementGuid>c19f9171-b6e2-4a8b-8d31-827cd897721a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>01137275-c7bb-4b69-bb28-237eff2561e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>9f9b1f84-7040-4702-8e81-5d62d16ab5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e496a6e-6a2a-4bf5-ad58-12f7e76918aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>989c99dc-d643-492e-8f5b-c1dbbd84e418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NameDescriptionEnd Date ActionStatusStart DateEnd DateCreation DateLast Updated DatePOST/GET Process StatusCreated ByLast Updated ByUac id</value>
      <webElementGuid>ae2a6e2b-ccc7-41a2-b705-2398c0a2097c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mngSnap_column_name&quot;)</value>
      <webElementGuid>6627259d-99ac-40b3-868d-7d91e8a74455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mngSnap_column_name']</value>
      <webElementGuid>39088fe2-acbc-439c-854d-79ed5837616e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mngSnap_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>6385f3a1-8129-4b31-a7bb-db573b5e1ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>ed12d515-7f31-410f-ac33-19f9256cb0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mngSnap_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'NameDescriptionEnd Date ActionStatusStart DateEnd DateCreation DateLast Updated DatePOST/GET Process StatusCreated ByLast Updated ByUac id' or . = 'NameDescriptionEnd Date ActionStatusStart DateEnd DateCreation DateLast Updated DatePOST/GET Process StatusCreated ByLast Updated ByUac id')]</value>
      <webElementGuid>90963428-d466-4ffd-ba9c-aac8fde9321d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
