<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Secondary Owner is not empty</name>
   <tag></tag>
   <elementGuidId>3df5ab7d-b474-4714-8e97-9b4c9f21752b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a_Collapsible1_R409135957861231789_ig_report_settings_content']/ul/li[2]/span[3]/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#control_text272765426030059919</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e1574fc-1c39-4937-bb61-68bd4c2f43cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>control_text272765426030059919</value>
      <webElementGuid>0998980d-7d2c-41d0-8f2f-23eb0fff0708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secondary Owner is not empty</value>
      <webElementGuid>dbd7cc63-b4ac-4f03-9282-1da7748a409f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;control_text272765426030059919&quot;)</value>
      <webElementGuid>2ce3ad2d-3dac-4795-911c-de24ac067e26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='control_text272765426030059919']</value>
      <webElementGuid>d1b66703-3629-490a-956c-12fbd46fd945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a_Collapsible1_R409135957861231789_ig_report_settings_content']/ul/li[2]/span[3]/a/span[2]</value>
      <webElementGuid>47e4ce8d-d0a4-4629-a4a3-8296ba1db356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span[3]/a/span[2]</value>
      <webElementGuid>3e51b03a-0b89-461c-92c2-77633b81ac7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'control_text272765426030059919' and (text() = 'Secondary Owner is not empty' or . = 'Secondary Owner is not empty')]</value>
      <webElementGuid>33ebe7b6-addc-4a3e-b15c-2d8e018d0b4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
