<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter</name>
   <tag></tag>
   <elementGuidId>00c1524a-b0e5-4450-8a17-faaa97d15023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'R242004504603843036_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R242004504603843036_actions_menu_2i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R242004504603843036_actions_menu_2i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>881f1473-e38f-4610-a724-fa4cd263e0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ff776eb-1973-4bcd-8277-f2382f36ed94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R242004504603843036_actions_menu_2i</value>
      <webElementGuid>414aae1f-756d-4f6d-9eaf-985a89eabe4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>96b44d20-3fa6-4831-87da-8e71b1ff94a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>e4b3fa1b-57ce-4deb-8284-06e02404a7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>a125d00b-c334-4d58-b331-a0280f320eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R242004504603843036_actions_menu_2i&quot;)</value>
      <webElementGuid>9620d983-95b8-4252-b510-05915a8c2b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R242004504603843036_actions_menu_2i']</value>
      <webElementGuid>c8f2eae7-e511-496e-903b-759c070af53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='R242004504603843036_actions_menu_2']/div/span/button</value>
      <webElementGuid>11571d58-c4d6-4c4f-96dd-80fdb149ea95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/button</value>
      <webElementGuid>e3ee8279-8e30-4118-a809-7485c279300f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'R242004504603843036_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>2aea0687-1196-4e48-999e-19105057a2c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
