<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter</name>
   <tag></tag>
   <elementGuidId>b6de1253-bc1d-4c2e-95f4-6f536a49f537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search_actions_menu_2i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_actions_menu_2i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c613a34-3575-4118-a58f-08c908b2d8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0aa2c108-f802-4296-b52e-5e28412f143f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_actions_menu_2i</value>
      <webElementGuid>5eac5eb3-6f51-4566-abd3-2bc1957c1314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>5d467b62-122a-4532-b8ef-5e3e1709022a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>9205a2f9-786e-489f-af75-04a615ca246c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>579749dc-676f-4125-9059-511f19ecf327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_actions_menu_2i&quot;)</value>
      <webElementGuid>4e7492b2-7532-4a78-b884-28dc90575317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search_actions_menu_2i']</value>
      <webElementGuid>d5580b7d-0184-4021-a309-34dce8ab2a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='search_actions_menu_2']/div/span/button</value>
      <webElementGuid>838255c3-5cee-4742-8b39-61fa4e8d67ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/button</value>
      <webElementGuid>3009055f-11b4-434b-97a7-5fbed8b1e55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'search_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>e60f0721-7cbc-491d-bcda-a071025d4e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
