<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Receipt Accounting vs. Enter Accounts Re_bac9e1</name>
   <tag></tag>
   <elementGuidId>2ffc4723-659e-466a-a752-346b79fe587c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='247793320273899118']/tbody/tr[6]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c5db1e54-72e4-4784-86bc-a027fff6f779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-tL</value>
      <webElementGuid>35b778e3-2a02-4a10-a88a-1167ac383148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>DESCRIPTION</value>
      <webElementGuid>f31b9985-16d9-4f51-a35b-d9ee7c7228ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Receipt Accounting vs. Enter Accounts Receivables Invoice Rule</value>
      <webElementGuid>ec0b64b5-3de8-4028-b0be-feba97200a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;247793320273899118&quot;)/tbody[1]/tr[6]/td[@class=&quot;u-tL&quot;]</value>
      <webElementGuid>c3b39f02-032d-409b-be8f-d5c4174c2f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='247793320273899118']/tbody/tr[6]/td[2]</value>
      <webElementGuid>48748c75-176f-4b75-b17a-f19b4b334a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt Accounting vs. Enter Accounts Receivables Invoice Rule'])[1]/following::td[1]</value>
      <webElementGuid>50a468ca-15c6-418c-a3f0-f931a88fbae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[4]/following::td[2]</value>
      <webElementGuid>1ced3581-46a9-4f7f-ad7b-eb38b5e60820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIGH'])[3]/preceding::td[1]</value>
      <webElementGuid>58960d55-14c8-41c2-b009-f06eb5738946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incompatible Sets'])[5]/preceding::td[2]</value>
      <webElementGuid>e849c11d-a6ee-46c4-b135-e9db19745a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]</value>
      <webElementGuid>c5462191-86f3-4229-9902-30029fd4bf09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Receipt Accounting vs. Enter Accounts Receivables Invoice Rule' or . = 'Receipt Accounting vs. Enter Accounts Receivables Invoice Rule')]</value>
      <webElementGuid>448039ce-0754-42f6-a108-c1caf7a0d35f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
