<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Interval Days Between Reminders (1)</name>
   <tag></tag>
   <elementGuidId>11885e39-d6f8-4b7e-99b7-bf33eb3fcc47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R307838823214507554_ig_grid_vc_cur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'Interval Days Between Reminders' or . = 'Interval Days Between Reminders')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Row 3, Column 3.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a487e5b4-1b21-4ebd-94ab-21a7111197fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>4de13f14-898c-42f5-9391-da898a7f3100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63a1026e-d11b-46f9-b330-b7f0daebf98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tC is-readonly is-focused</value>
      <webElementGuid>584c8ce9-b9a1-4073-8b9b-610dac50f9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R307838823214507554_ig_grid_vc_ctx C153814212621916549_HDR R307838823214507554_ig_grid_vc_cur</value>
      <webElementGuid>5a6b7719-25b7-475d-b6e1-1ec4b1bcc255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R307838823214507554_ig_grid_vc_cur</value>
      <webElementGuid>d55b1f6f-5aab-4f26-96e8-9abb776bf90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interval Days Between Reminders</value>
      <webElementGuid>ddf3674c-ece8-4d6a-a689-73c6ec76c34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R307838823214507554_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>a8a3667b-31cd-49ce-b66b-e2d94ba8fadd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Interval Days Between Reminders' or . = 'Interval Days Between Reminders')]</value>
      <webElementGuid>d554b04e-8fcb-4abd-9e7b-159e1df04931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R307838823214507554_ig_grid_vc_cur']</value>
      <webElementGuid>e13ad5b5-3de6-48a9-980c-40b13f03c500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R307838823214507554_ig_grid_vc']/div[3]/div[4]/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>bc2c9d9a-b3c0-44b0-b00b-7dc44e5da950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Access Monitor'])[3]/following::td[2]</value>
      <webElementGuid>7debe3e3-6844-4e7c-9df2-bfa729b43fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This parameter defines how many days after the review creation, the first reminder will be sent'])[1]/following::td[3]</value>
      <webElementGuid>f345e2af-42fb-4dc0-997c-90c9824fc87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NUMBER'])[2]/preceding::td[2]</value>
      <webElementGuid>afb77cec-7f5a-41e3-8e09-4bc1523e759e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This parameter defines how many days will elapse between sending reminders'])[1]/preceding::td[3]</value>
      <webElementGuid>7061f589-ba95-40f4-9837-a7746e25f6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Interval Days Between Reminders']/parent::*</value>
      <webElementGuid>3a894fe6-b111-4a4c-9674-a7b79553eab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]</value>
      <webElementGuid>9f5e325c-8d5f-4cad-b3c3-4b4e417d56a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
