<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verified By (Role Owner) - 993</name>
   <tag></tag>
   <elementGuidId>55bc2fd8-6c07-42cd-8fad-513051c42647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C97176839460990422 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/div/div/div/div[2]/div[2]/div[6]/div[1]/div/div[1]/table/tr/th[21]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>761a75db-4dd7-4eb1-b3f9-54b09477c037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>97ad8c4b-3590-4e16-8ce7-a55ff6403e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>97176839460990422</value>
      <webElementGuid>5d20d75c-e3ff-4179-bd68-3e4b695bbf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>338fda07-5431-4371-8b3e-1f0c9172341e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verified By (Role Owner)</value>
      <webElementGuid>f513599b-72af-4ff8-8032-3f8320b3f398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;291211863100602603&quot;)/tr[1]/th[@id=&quot;C97176839460990422&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>4fa7e46e-50b4-49bb-b838-8ff6c221dd16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C97176839460990422']/a</value>
      <webElementGuid>e9a5c1db-ad7f-49d4-b1ba-08a459177ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verified By (Role Owner)')]</value>
      <webElementGuid>31b787fa-347c-4439-8adb-9ea202a12a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[21]/a</value>
      <webElementGuid>074fdbd0-bd5c-4d6d-8a2e-35ce02427f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Verified By (Role Owner)' or . = 'Verified By (Role Owner)')]</value>
      <webElementGuid>31bd779f-c393-45ff-bf77-a30db909b620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
