<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select a Value - EBizApp_JDBC_EnvK_76acc0</name>
   <tag></tag>
   <elementGuidId>ad0f8ba5-82c3-4b79-8032-ccdf48d22b8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P51_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'P51_ENVIRONMENT' and @name = 'P51_ENVIRONMENT' and (text() = '- Select a Value - 
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
' or . = '- Select a Value - 
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>984cc899-1f3f-4f4c-987c-be5c5cab6a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P51_ENVIRONMENT</value>
      <webElementGuid>256191a4-dd97-4db5-98ad-92a70d059759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P51_ENVIRONMENT</value>
      <webElementGuid>b14743bd-e7d2-4b0d-a899-43f7d36fb62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>9968d498-164b-49c8-9c1a-eeee3901df70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0473c06-1bd4-4b78-bfdc-31ea1fa4b6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0db70346-5626-4f0c-aec4-811bbd3e3a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select a Value - 
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
</value>
      <webElementGuid>0bc8f5ca-240e-428b-a95c-d5c20afa7073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P51_ENVIRONMENT&quot;)</value>
      <webElementGuid>470d59aa-ade1-467d-b5a7-3fab0a1eff83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P51_ENVIRONMENT' and @name = 'P51_ENVIRONMENT' and (text() = '- Select a Value - 
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
' or . = '- Select a Value - 
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
')]</value>
      <webElementGuid>9916f0f2-1b8d-41d9-80fb-94ff3c93f335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P51_ENVIRONMENT']</value>
      <webElementGuid>14f5e9b9-42b2-4885-b8b9-588dace948e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[2]/following::select[1]</value>
      <webElementGuid>12088ee9-e776-4009-8fca-78cac2fc79fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>c622cb9e-0e78-4f04-a809-e513b6107097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scoped/Descoped Attributes'])[2]/preceding::select[1]</value>
      <webElementGuid>d8a6558d-ae54-44bd-ac5a-b7e3cf372820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[1]</value>
      <webElementGuid>14f7d250-6845-487c-9346-dcb2be05fc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>efca21ef-f723-45be-a571-72224a402413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P51_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>b0fbfd6e-00c2-47be-b812-df5b08689980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
