<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_FSOD.FSOD_ENTRY_ATTRIBUTE_ALL</name>
   <tag></tag>
   <elementGuidId>8bbc71aa-f714-4dba-94e4-21c4023abdef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupLov_24_C146572706494766625_dlg']/div[2]/div/div[3]/ul/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d52cd597-6c00-4bba-804a-83b532c90eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>FSOD_ENTRY_ATTRIBUTE_ALL</value>
      <webElementGuid>6bed7454-37ff-4d5b-8279-5525a967f868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IconList-item</value>
      <webElementGuid>c22f9122-c6b9-4362-ae13-d70fa618f2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f697fac6-0616-4923-8d31-68b2b36b337b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5e07022f-738f-4462-a4ef-65dee9087bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FSOD.FSOD_ENTRY_ATTRIBUTE_ALL</value>
      <webElementGuid>3ae15702-a53e-4a48-8348-36fcdc508b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupLov_24_C146572706494766625_dlg&quot;)/div[@class=&quot;a-PopupLOV-results a-TMV&quot;]/div[@class=&quot;a-TMV-body&quot;]/div[@class=&quot;a-TMV-w-scroll&quot;]/ul[@class=&quot;a-IconList&quot;]/li[@class=&quot;a-IconList-item&quot;]</value>
      <webElementGuid>c1e71641-0b61-4a4e-802b-eab535bc8834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupLov_24_C146572706494766625_dlg']/div[2]/div/div[3]/ul/li[4]</value>
      <webElementGuid>343e8794-2c19-47ee-85af-b939142345ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSOD.FSOD_ENTRY_ALL'])[1]/following::li[1]</value>
      <webElementGuid>073e2921-3d99-4821-96db-3d904e4b0beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSOD.FSOD_ATTRIBUTE_TYPE_ALL'])[1]/following::li[2]</value>
      <webElementGuid>bd7bc2e6-fc8d-4b1b-bc46-0281767c2077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSOD.FSOD_ENTRY_HIERARCHY_ALL'])[1]/preceding::li[1]</value>
      <webElementGuid>e75a4db1-8c3f-4e53-8cfb-8462aa4f04c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FSOD.FSOD_ENTRY_HIERARCHY_ATTR_ALL'])[1]/preceding::li[2]</value>
      <webElementGuid>7596ef9f-b3f1-4b77-b339-bf8ca5f9233b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FSOD.FSOD_ENTRY_ATTRIBUTE_ALL']/parent::*</value>
      <webElementGuid>b5b4098a-257a-4f5e-bf39-77eaeb9d2661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[4]</value>
      <webElementGuid>940da016-004c-4d6a-93d7-72135f08e20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'FSOD.FSOD_ENTRY_ATTRIBUTE_ALL' or . = 'FSOD.FSOD_ENTRY_ATTRIBUTE_ALL')]</value>
      <webElementGuid>bfdc293e-42d0-4efc-8672-9147d1462482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
