<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_FSOD.FSOD_USER_ALL5 - Copy</name>
   <tag></tag>
   <elementGuidId>3c77228b-a2f2-4465-b9db-6ca2ecf2c39c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[1]/div[2]/div[2]/div[2]/div[3]/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/div[2]/div/div[4]/div[3]/div[1]/div[2]/div[4]/table/tbody/tr[5]/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#igSod_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8de8f54c-fd7e-4650-be6a-8b6dec43373c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f1222cc0-2594-42c5-beb0-fc666f3b0cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ffc0dea8-a9a8-48e5-94fc-26029f3faef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-focused</value>
      <webElementGuid>63359329-9607-408b-891a-eb63ce292db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>igSod_ig_grid_vc_ctx igSod_ig_grid_vc_cur</value>
      <webElementGuid>554b119b-d391-43ca-8732-4f705fdd4a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>igSod_ig_grid_vc_cur</value>
      <webElementGuid>350fd04f-86f2-4933-bcde-68ebb370319d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FSOD.FSOD_USER_ALL</value>
      <webElementGuid>018184af-c834-4dbe-b698-d943c62fba02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igSod_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>a0855ef9-bb85-4b87-9c6a-c3d184796e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='igSod_ig_grid_vc_cur']</value>
      <webElementGuid>864d6ce5-292b-49c0-be6b-152919d3b5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='igSod_ig_grid_vc']/div[3]/div[4]/table/tbody/tr[5]/td[5]</value>
      <webElementGuid>32260c70-f423-43f0-8d9c-3a1d5cf91a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA_DS:G_1:DISPLAY_NAME'])[1]/following::td[1]</value>
      <webElementGuid>2977f7f5-a231-44bb-8d84-24f1bead6d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISPLAY_NAME'])[3]/following::td[2]</value>
      <webElementGuid>389e5ddf-379d-4d64-a9b0-762848718b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISPLAY_NAME'])[4]/preceding::td[1]</value>
      <webElementGuid>285ac966-8f2c-47d5-a691-830e9f824231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VARCHAR2'])[5]/preceding::td[2]</value>
      <webElementGuid>06ea56f1-ceea-4bd9-a629-29c9106715e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/div/div[5]/div[3]/div/div[3]/div[4]/table/tbody/tr[5]/td[5]</value>
      <webElementGuid>2ca260ba-5a30-4930-9ea3-966c5169f311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'igSod_ig_grid_vc_cur' and (text() = 'FSOD.FSOD_USER_ALL' or . = 'FSOD.FSOD_USER_ALL')]</value>
      <webElementGuid>4105e026-5f5a-48a1-b594-7ef136c2d948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
