<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Allows management of purchase orders usi_5ee36a (1) (1)</name>
   <tag></tag>
   <elementGuidId>6708c9df-5ad9-44ac-97de-b60efd13dd3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='165934090082227139_orig']/tbody/tr[2]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f17397e9-f64f-4737-bb6b-50614658fe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-tL</value>
      <webElementGuid>4421df67-0a4b-4377-b2db-5d5d3f908af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>C165934215983227141</value>
      <webElementGuid>1ff24a3d-44be-4159-9831-bf7ae2ce4a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allows management of purchase orders using web service.</value>
      <webElementGuid>653e1241-bb43-4300-8fa9-7e238157264b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;165934090082227139_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]</value>
      <webElementGuid>ed833426-e3f1-4f46-964b-ab8b0d133cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/deba/Rough/Page_Activity Entries/iframe</value>
      <webElementGuid>bd5faaee-b921-482d-85c5-e600695bfbfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='165934090082227139_orig']/tbody/tr[2]/td[2]</value>
      <webElementGuid>35eeed67-560d-4c0d-9bb6-d244fe37f2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>92f0ddcf-b7ea-42a1-8f34-c4b225fe00eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Allows management of purchase orders using web service.' or . = 'Allows management of purchase orders using web service.')]</value>
      <webElementGuid>33a9513b-d7df-4af3-a41d-50ae1b057c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
