<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Role</name>
   <tag></tag>
   <elementGuidId>927a5df5-0813-4992-b6d8-a5ab83a57f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sodObjectsIg_ig_grid_vc_cur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'Role' or . = 'Role')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Role&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5a98eeda-03b2-4e96-b3e3-538fb2fb6e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>567cc66c-9a34-4578-881d-2c8314310a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fd58fe91-1366-4dae-858b-3cc0221782d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-readonly is-focused</value>
      <webElementGuid>18e009db-6d58-43c8-bf11-6cdaa9720952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>sodObjectsIg_ig_grid_vc_ctx C144929019790910947_HDR sodObjectsIg_ig_grid_vc_cur</value>
      <webElementGuid>0c3dd27c-4b81-41e6-8baa-ca7e97ef6b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sodObjectsIg_ig_grid_vc_cur</value>
      <webElementGuid>72d64d69-0a02-416e-bf35-88a2d7e03577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>e0f5be12-b5d8-4e4d-a0ba-29eb07458203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sodObjectsIg_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>462da743-42a4-41fe-8a75-46d28b46539b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Role' or . = 'Role')]</value>
      <webElementGuid>f9d88bf8-6a35-4818-ba93-29512fc45ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='sodObjectsIg_ig_grid_vc_cur']</value>
      <webElementGuid>64b4b4c5-1405-4e2d-b84b-d99212d0d0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sodObjectsIg_ig_grid_vc']/div[3]/div[4]/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>82f345a2-af63-4b74-9bbb-e2c2af71b05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN'])[2]/following::td[3]</value>
      <webElementGuid>1dbdf8c0-a2f8-4341-badb-dd53c3c20dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN'])[1]/following::td[5]</value>
      <webElementGuid>ff2c5550-8bff-4287-9525-bbb209016155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EBiz_Entry_LocalRoles_JDBC'])[2]/preceding::td[1]</value>
      <webElementGuid>1294f745-4c6b-49f6-8983-e74e98722517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTRY'])[1]/preceding::td[2]</value>
      <webElementGuid>9d6081eb-a604-4d9c-b4ae-526a43bfe6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Role']/parent::*</value>
      <webElementGuid>78c731cf-da0f-4022-b765-edbd554c3c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]</value>
      <webElementGuid>8e5c6270-187d-4456-9e97-48a39fbfa759</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
