<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select -MTP_24062025002338_20250624002343</name>
   <tag></tag>
   <elementGuidId>7982b5e6-d7de-4b8d-a46f-554323146c49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P61_ANALYTICS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P61_ANALYTICS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Result Sets&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>57736255-879d-4e9d-9897-e83e22337a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P61_ANALYTICS</value>
      <webElementGuid>0ce18c75-3600-4298-997f-f8d8692511eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P61_ANALYTICS</value>
      <webElementGuid>e660b004-10af-43a8-ad11-94447900de17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>951a38fc-1e6d-44e0-8ba9-23b1486dd78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>daa0c211-0923-4cc8-acf8-6df27691294b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ce8df7e0-337c-41d1-96af-b48e0c784659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P61_ANALYTICS');</value>
      <webElementGuid>65502b37-51d9-45d2-88a4-1369b075f569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select -
MTP_24062025002338_20250624002343
</value>
      <webElementGuid>c9240eaa-d6c9-4e3c-9d65-5d03d1ffdf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P61_ANALYTICS&quot;)</value>
      <webElementGuid>1c9100ce-5747-4294-a526-d286a4295eb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'P61_ANALYTICS' and (text() = '- Select -
MTP_24062025002338_20250624002343
' or . = '- Select -
MTP_24062025002338_20250624002343
')]</value>
      <webElementGuid>fac3e001-b7f5-4298-a6ad-3f2e0340ea7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P61_ANALYTICS']</value>
      <webElementGuid>ba805936-14c8-4ecf-91e2-69e5e6285883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P61_ANALYTICS_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>e297688a-e4d2-4b59-acae-90641a27599b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Result Sets'])[1]/following::select[1]</value>
      <webElementGuid>2b18b812-3a89-4cd1-80f2-14d4fd2ef674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EBS122'])[1]/following::select[1]</value>
      <webElementGuid>3a73185f-c325-42d0-b281-7d54d2270f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Download'])[1]/preceding::select[1]</value>
      <webElementGuid>ea878d42-f60e-4d24-827a-7212ecad6086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>a428d02e-8799-44b8-9db4-e6169f4639db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
