<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonR324291159469100091_expression_icon_link</name>
   <tag></tag>
   <elementGuidId>dc3b6e4e-5f2c-4656-84df-74ff6fbe2473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R324291159469100091_expression_icon_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R324291159469100091_expression_icon_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce21f830-ea6a-4968-83f2-eeb0851f1b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--menu a-IRR-button a-IRR-button--menu</value>
      <webElementGuid>cd03455e-dc9d-4856-a4fc-29ec081d9edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e2a8355-f699-4c4e-8c87-62b627157318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Popup List of Values: Expression</value>
      <webElementGuid>e2c83055-9abf-4965-8917-fdeb6c27f4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Popup List of Values: Expression</value>
      <webElementGuid>a1f239a7-89a8-4c6e-9be1-b32bdc6271b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-picker-for</name>
      <type>Main</type>
      <value>R324291159469100091_expression</value>
      <webElementGuid>7f53a6e2-883c-415a-a6d1-090d41bf3ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R324291159469100091_expression_icon_link</value>
      <webElementGuid>a589caa2-9e3a-47b5-bef4-8448a2a593c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R324291159469100091_expression_icon_link&quot;)</value>
      <webElementGuid>8df4833a-5def-4e67-bea5-a63d57b35dfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R324291159469100091_expression_icon_link']</value>
      <webElementGuid>ea4b7f7a-cead-4128-ba16-2ba22d0868f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R324291159469100091_expression_container']/div/div[2]/span/button</value>
      <webElementGuid>6e8ac57e-8ea0-4a49-8b4c-159aecdf8cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/button</value>
      <webElementGuid>3b744da3-a1a6-40f1-9297-9294e0119473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Popup List of Values: Expression' and @id = 'R324291159469100091_expression_icon_link']</value>
      <webElementGuid>d572bbc6-920c-44ec-9c53-79bac84cfeae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
