<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Object SetDescriptionStart DateEnd D_6bdece</name>
   <tag></tag>
   <elementGuidId>d711a167-75d4-4a37-a5e9-38e93493f828</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R137674426230792379_column_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='R137674426230792379_column_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5c12feb7-a7ff-40e7-9295-6087fafd5730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R137674426230792379_column_name</value>
      <webElementGuid>f31d0120-afbc-464d-bced-7abf52e1d0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>d4369aee-4dc9-48ed-b225-88820b8a0ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>cf894cff-81c8-4fb7-8748-308922100dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f19829b7-298e-4770-ade4-897317b8975b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>257ce921-8392-43a2-af7c-35f026d79898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Object SetDescriptionStart DateEnd DateApplication TypeCreation DateCreated ByLast Update DateLast Updated ByConfig File</value>
      <webElementGuid>3205e549-7d1d-4ba1-8240-59c612394055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R137674426230792379_column_name&quot;)</value>
      <webElementGuid>1b38dd41-8355-42b7-9065-8500a3481a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='R137674426230792379_column_name']</value>
      <webElementGuid>df7960be-9e02-4abf-9099-4b9ba8fc61cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R137674426230792379_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>b5b69321-5cb3-4307-918b-6fbb95ed5c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e7e00432-f5cf-479c-92de-2f5cf7b263f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'R137674426230792379_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'Object SetDescriptionStart DateEnd DateApplication TypeCreation DateCreated ByLast Update DateLast Updated ByConfig File' or . = 'Object SetDescriptionStart DateEnd DateApplication TypeCreation DateCreated ByLast Update DateLast Updated ByConfig File')]</value>
      <webElementGuid>054329f3-da3a-4976-86de-a8fb38a6f39d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
