<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_BusinessProcess2</name>
   <tag></tag>
   <elementGuidId>bec7669d-a475-4d0a-a903-b5e5aa297236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(9) > td.u-tL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='241380233888970047_orig']/tbody/tr[9]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;BusinessProcess2&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>baa8d225-cb04-437f-b970-775ef809e6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-tL</value>
      <webElementGuid>d5481308-abf0-454c-9955-3ca9a5f5a69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>C241380427103970049</value>
      <webElementGuid>445e006e-b1d3-4bd6-8f15-e7de59a9d6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BusinessProcess2</value>
      <webElementGuid>29096ae0-bc28-49b5-810e-6d18e961a61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;241380233888970047_orig&quot;)/tbody[1]/tr[9]/td[@class=&quot;u-tL&quot;]</value>
      <webElementGuid>caa85594-e988-4efa-a470-1a42d95abe2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='241380233888970047_orig']/tbody/tr[9]/td[2]</value>
      <webElementGuid>431cf5dd-c40a-4b4e-8189-c10ebd65a336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN'])[12]/following::td[2]</value>
      <webElementGuid>015ab045-db5f-4d81-b79b-79d10608a91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN'])[11]/following::td[4]</value>
      <webElementGuid>ef82f447-8172-415b-adfb-6374fc21b0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BusinessProcess2'])[2]/preceding::td[1]</value>
      <webElementGuid>e7f920e5-eedd-4da0-a41b-7f4f7b1149dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATALON_ADMIN'])[3]/preceding::td[3]</value>
      <webElementGuid>4d1f8347-d131-4980-a38b-ac13b3c06765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BusinessProcess2']/parent::*</value>
      <webElementGuid>3d09a895-27d4-4a1c-a3bd-694249989277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]</value>
      <webElementGuid>2992d07c-dc22-43be-99a8-ee97c3bf76fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'BusinessProcess2' or . = 'BusinessProcess2')]</value>
      <webElementGuid>80e5eb75-82c3-4d9b-9693-42e0efc49afe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
