<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go</name>
   <tag></tag>
   <elementGuidId>4740e02a-20d5-4420-8370-c86ffe24002c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P3_RESULT_ACTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P3_RESULT_ACTION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>447f3781-2f9c-459a-9e68-4547d3ba30d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'ResultAction',validate:true});</value>
      <webElementGuid>70f5fc66-8432-4b37-a6af-eee37dd6d4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button /i/go.gif</value>
      <webElementGuid>595aba48-5170-4320-a3c5-25c91adb1a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4e54139-3534-4b29-9432-4f134988998a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_RESULT_ACTION</value>
      <webElementGuid>c395ba77-35ab-415e-aa2d-08baec9e6fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>b6a48208-5293-4ccf-ae69-3242648a72d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_RESULT_ACTION&quot;)</value>
      <webElementGuid>7d5cb2cf-ffe2-48b0-ba50-d2c8036b3fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P3_RESULT_ACTION']</value>
      <webElementGuid>2860a688-bc6c-4cb2-b97a-5d01f45ff0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R25800045638773306']/div[2]/div[2]/div/div[2]/div[2]/button</value>
      <webElementGuid>d166340d-8feb-483b-a67b-4b3a33750db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>a465a14b-aa23-4306-8090-3d76d4c956d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'P3_RESULT_ACTION' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>4fa5ce35-6681-4128-9022-f5a8be54cd85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
