<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload Data_mngSnap_search_field (1)</name>
   <tag></tag>
   <elementGuidId>963992cc-cb53-4dac-bf70-c3f74775c272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mngSnap_search_field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@title = 'Search Report' and @type = 'search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=searchbox[name=&quot;Search Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa151d8a-f1d8-4c4b-8fcb-f534c9208fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-search-field</value>
      <webElementGuid>afed2001-4b6f-4b14-874f-3a3a501b2452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mngSnap_search_field</value>
      <webElementGuid>0859ded3-1d8d-4655-a3da-0f1110ac768c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search Report</value>
      <webElementGuid>688d4cf2-43aa-49df-8eda-78057c5b2c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ab2104f7-8cb2-4a77-9649-811381048cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>1fa832c8-c3c3-4380-a108-6e1246462a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>cf25e16b-a085-4253-a248-50c60f572df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mngSnap_search_field&quot;)</value>
      <webElementGuid>969fe07d-64e2-4c21-b603-ef3bc172adc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Search Report' and @type = 'search']</value>
      <webElementGuid>639e5761-67d8-4d5f-b84b-cf1baac780be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mngSnap_search_field']</value>
      <webElementGuid>04362a7b-937e-4440-baef-8d1911dd3a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mngSnap_toolbar_controls']/div/div/div[2]/input</value>
      <webElementGuid>5b3d07c3-dfdc-4685-894c-cb55d2b0c6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>aefca7d2-3db5-43e9-9810-176159c0ec35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
