<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Description (2)</name>
   <tag></tag>
   <elementGuidId>f572a426-d450-48c5-ac64-8b2a8883a1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P4_DESCRIPTION_LABEL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P4_DESCRIPTION_LABEL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3c233b71-a82a-4304-bbe7-9bf48cdb0281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P4_DESCRIPTION</value>
      <webElementGuid>b143292c-8094-4bae-b249-7a4d5033a1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P4_DESCRIPTION_LABEL</value>
      <webElementGuid>dca02fd7-160d-4591-9bcd-b754f7f408c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>ab1b1741-369f-4f13-a096-c05926f36270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>6954cbb8-b158-4c3c-8729-138652d7c9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P4_DESCRIPTION_LABEL&quot;)</value>
      <webElementGuid>c5f0dbb4-756a-42dc-aa45-5a2219454fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P4_DESCRIPTION_LABEL']</value>
      <webElementGuid>43c41685-e9e0-4d62-a5b0-bcbd8a18aed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P4_DESCRIPTION_CONTAINER']/div/label</value>
      <webElementGuid>87850b52-d0f5-4fd8-9e73-5ce4682c8b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label</value>
      <webElementGuid>b54a90b9-1145-4c6a-ae5f-56f0aff9627f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P4_DESCRIPTION_LABEL' and (text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>16ffc738-3eb4-4da4-85fd-9137e2d25177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
