<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_App Type Version (Value Required)</name>
   <tag></tag>
   <elementGuidId>d1f749ad-5a0d-4cf2-86f1-0d0afc969ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P13_APP_TYPE_VERSION_ID_LABEL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P13_APP_TYPE_VERSION_ID_LABEL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4239c496-ce09-4cbc-b2c2-21c06f84a2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P13_APP_TYPE_VERSION_ID</value>
      <webElementGuid>008d0b25-6c64-4780-95f8-f787bad56bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P13_APP_TYPE_VERSION_ID_LABEL</value>
      <webElementGuid>9fdaa46e-c1e6-4108-8ea0-486a38b0fe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>940da4b4-cc97-41f4-ad8f-fa57d0c4fc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>App Type Version (Value Required)</value>
      <webElementGuid>5203fd0a-9fec-4a82-99d0-cf78e9ad9619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P13_APP_TYPE_VERSION_ID_LABEL&quot;)</value>
      <webElementGuid>1b9df5e2-273d-4cc2-a31e-ff202d0a3e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P13_APP_TYPE_VERSION_ID_LABEL']</value>
      <webElementGuid>41c74303-0a8d-429d-8784-dae1816e55e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P13_APP_TYPE_VERSION_ID_CONTAINER']/div/label</value>
      <webElementGuid>c4b212d0-7e12-4dc7-88ff-dc9c124f2d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oracle Cloud ERP'])[1]/following::label[1]</value>
      <webElementGuid>b0d53706-3903-4a76-8b49-25717246506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[2]/following::label[1]</value>
      <webElementGuid>a48a977d-406d-4984-b4ce-39dee177e6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oracle Cloud ERP 20x'])[1]/preceding::label[1]</value>
      <webElementGuid>0b38fda8-73bf-45d1-923d-42eb274218d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='App Type Version']/parent::*</value>
      <webElementGuid>3e9db441-268b-44cf-abb8-365ccaf0bb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/label</value>
      <webElementGuid>98138387-cc47-4ee0-beea-e933cdfe5ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P13_APP_TYPE_VERSION_ID_LABEL' and (text() = 'App Type Version (Value Required)' or . = 'App Type Version (Value Required)')]</value>
      <webElementGuid>6d385bbe-4d1c-4dac-8b8d-902915ec476f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
