<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Canceled</name>
   <tag></tag>
   <elementGuidId>3c478406-608b-4e73-b36e-361e06163d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'Canceled' or . = 'Canceled')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6dc08c4e-1fa4-47fd-b5c2-33dd38beaf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-tL</value>
      <webElementGuid>263c46d3-dabd-456f-91bc-a19d556c08fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>statusCol</value>
      <webElementGuid>32df54e6-972c-4e15-9bfc-a227442490db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canceled</value>
      <webElementGuid>245484fb-79b5-4f6b-84d2-375c570d15a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;97388373399089016_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]</value>
      <webElementGuid>4f090a01-5588-4385-b9da-54e712ecd8b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Canceled' or . = 'Canceled')]</value>
      <webElementGuid>e9dd83d2-3f21-43d0-b884-b72422cadabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EIA - Access Request WF'])[1]/following::td[2]</value>
      <webElementGuid>1fd49a0e-26b0-4c81-8331-ac291e6792aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/following::td[4]</value>
      <webElementGuid>d4480c57-c12b-428b-8387-82b03f75e035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canceled at approval level: 2'])[1]/preceding::td[1]</value>
      <webElementGuid>6308340a-d4cf-45e8-a119-2e4f72da0907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FITADMIN'])[1]/preceding::td[3]</value>
      <webElementGuid>34c77381-4e33-4178-bcc2-c74505e60fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Canceled']/parent::*</value>
      <webElementGuid>26b71dee-87f6-42df-b647-5dd64332863d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>0a9270a6-f5ce-42bf-886d-9e7637ee887c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='97388373399089016_orig']/tbody/tr[2]/td[5]</value>
      <webElementGuid>57293f1c-d86b-4ee2-9d92-ee3b59eb9195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
