<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Actions</name>
   <tag></tag>
   <elementGuidId>2d81945f-afd2-4abc-a4e0-6e54cd93a540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='uRep_actions_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uRep_actions_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88af0dd6-7461-487d-9bcd-62ee96091b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uRep_actions_button</value>
      <webElementGuid>406f2418-f559-4a7a-a953-8b80136f39d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--actions js-menuButton</value>
      <webElementGuid>82a92553-b29f-445e-a56e-cccd0b06a5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a3e07ca-81f2-4098-b29a-9d6db17782a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu</name>
      <type>Main</type>
      <value>uRep_actions_menu</value>
      <webElementGuid>61864f81-97e7-4c4b-a7f0-a43295278bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>70b46715-e6c3-4e8c-b03d-33c6a8f913bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>c350fb65-8f5f-4b37-8d39-8eabb3c2f00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uRep_actions_button&quot;)</value>
      <webElementGuid>83ffc316-6eba-4f53-8412-4b01a5e1dafc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='uRep_actions_button']</value>
      <webElementGuid>504953ac-7519-47a2-82f8-03a1a8654ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uRep_toolbar_controls']/div[3]/div/button</value>
      <webElementGuid>4fc5d6f3-1ca3-47c2-8798-5b8158721571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div[3]/div/button</value>
      <webElementGuid>4b6b7087-180c-48a6-91ee-9d95b044ca9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'uRep_actions_button' and @type = 'button' and (text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>6fe2c69e-84f3-46af-8e94-71d9c24df1ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
