<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PrivilegeRole (1) (1)</name>
   <tag></tag>
   <elementGuidId>fa95e4ef-7946-4ec1-b2e1-23b81ead05f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P74_EXCEPTION_TYPE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P74_EXCEPTION_TYPE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72af5681-ed8e-4710-8815-37199dc5d445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P74_EXCEPTION_TYPE</value>
      <webElementGuid>d2835f4e-7e8a-4b42-b6a0-94ba7ea308b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P74_EXCEPTION_TYPE</value>
      <webElementGuid>84ba025d-db76-4086-8215-bcdcc66f99ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>6a792ee5-40e4-491c-a263-cdccee8da9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b2c6e801-4847-40b2-a326-f515564b9e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>27e3d061-d16e-45ac-b0ec-5206b3811d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>%
Privilege
Role
</value>
      <webElementGuid>02af4dbe-0474-4104-8635-e58a9e5dba06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P74_EXCEPTION_TYPE&quot;)</value>
      <webElementGuid>5b41daec-f104-4b38-a35b-5761671689e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P74_EXCEPTION_TYPE']</value>
      <webElementGuid>cabe6140-822f-4970-bebb-3d6af13bb852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P74_EXCEPTION_TYPE_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>64e6733d-89ee-47a5-95be-898e35d227a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/div/select</value>
      <webElementGuid>d35026cf-fac0-49af-8ffd-cf5b90403b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P74_EXCEPTION_TYPE' and @name = 'P74_EXCEPTION_TYPE' and (text() = '%
Privilege
Role
' or . = '%
Privilege
Role
')]</value>
      <webElementGuid>cedc3bc1-69ac-48c8-8496-2ae8724111f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
