<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Use File Headers</name>
   <tag></tag>
   <elementGuidId>4962e3f5-98dd-41de-9c66-a62436769cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P10_USE_HEADERS_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P10_USE_HEADERS_LABEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c7efef9f-f238-4a34-a334-32b2db8ed093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P10_USE_HEADERS</value>
      <webElementGuid>423ecd39-3f6c-44e9-841e-0d6212ca5cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_USE_HEADERS_LABEL</value>
      <webElementGuid>fe844097-f25c-4370-a914-7c575baa8ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>56d468a3-76ee-4315-b99b-8eb630e7eaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Use File Headers</value>
      <webElementGuid>c1248b13-a902-46b3-9f3f-8a65a7670920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_USE_HEADERS_LABEL&quot;)</value>
      <webElementGuid>95a98377-a4e2-4d8d-8207-0728a72e7bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P10_USE_HEADERS_LABEL']</value>
      <webElementGuid>20dcf241-d21d-475a-ad18-33374a21b54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_USE_HEADERS_CONTAINER']/div/label</value>
      <webElementGuid>49bc7fc7-3b61-42d0-907a-2f703e4035e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Triggers'])[1]/following::label[1]</value>
      <webElementGuid>8a71646d-ad40-42f8-ba13-48af69d197fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Tracker Type'])[1]/following::label[2]</value>
      <webElementGuid>52e56083-60b2-4484-ab4f-210ab1a66851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::label[1]</value>
      <webElementGuid>fd8c6457-c4bf-4252-b644-e35964826589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column Delimiter'])[1]/preceding::label[2]</value>
      <webElementGuid>b333b5e5-e4ed-4e22-b012-9aa620293ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Use File Headers']/parent::*</value>
      <webElementGuid>83dc1ced-657f-4ac7-9a65-41387bc9c8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/label</value>
      <webElementGuid>72ae7cf5-3323-4201-a281-ed449e58a2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P10_USE_HEADERS_LABEL' and (text() = 'Use File Headers' or . = 'Use File Headers')]</value>
      <webElementGuid>43b30123-a802-47b3-9806-435fa1f39995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
