<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Object Description</name>
   <tag></tag>
   <elementGuidId>b3c2c129-0d4d-4bf3-89fd-d3ea9cf26cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P10_OBJECT_DESCR_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Object Description' or . = 'Object Description')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>22ee9bcf-58f6-46b8-84de-c7f8604487e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P10_OBJECT_DESCR</value>
      <webElementGuid>6f479761-9b41-4ecf-ad62-90275b953042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_OBJECT_DESCR_LABEL</value>
      <webElementGuid>f5a91e4f-283e-43cb-b46e-ea01042361c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>5fa1695a-9054-49c6-9dac-27130ca47e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Object Description</value>
      <webElementGuid>a53e52c3-78fb-4391-9acf-8c22a904ec3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_OBJECT_DESCR_LABEL&quot;)</value>
      <webElementGuid>37e1503b-268b-4b0c-9303-c4996eadd81e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Object Description' or . = 'Object Description')]</value>
      <webElementGuid>909ee179-cad0-4de5-b7c1-c673380c0de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P10_OBJECT_DESCR_LABEL']</value>
      <webElementGuid>ac861807-8555-4cfb-b422-46c4e8e0633b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_OBJECT_DESCR_CONTAINER']/div/label</value>
      <webElementGuid>c966895d-2ed0-48d8-96fa-2a3b248bad67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[1]/following::label[1]</value>
      <webElementGuid>dfd5c97a-53aa-40d9-bee1-48b7f71d4a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[2]/preceding::label[1]</value>
      <webElementGuid>14fd8e12-1201-4920-a94d-6168d688c8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Object Description']/parent::*</value>
      <webElementGuid>61b059ed-643e-4759-bf46-717947bc6cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label</value>
      <webElementGuid>3af06fde-fbb1-454c-bccb-3abf95c09ad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
