<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Actions_apex-edit-page</name>
   <tag></tag>
   <elementGuidId>4e6265e3-3679-4562-ab7b-ff7fdb023eb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.apex-edit-page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='296130301834446615']/tbody/tr[2]/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;KTLN_ADMIN_EAM EAM Admin Role 01-FEB-23 - EAM&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02ef2fb1-8f3d-45c7-a64e-5fe0f0bf9f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/i/app_ui/img/icons/apex-edit-page.png</value>
      <webElementGuid>97d636ff-be0f-4e0a-955a-1364758bfc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-edit-page</value>
      <webElementGuid>11fe4c99-2883-4222-84ec-42362708f7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;296130301834446615&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tC&quot;]/a[1]/img[@class=&quot;apex-edit-page&quot;]</value>
      <webElementGuid>449890d0-00f2-4c47-8ad9-c7d5e72f578f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='296130301834446615']/tbody/tr[2]/td/a/img</value>
      <webElementGuid>0154304e-9c40-4020-9871-b13b27fd60f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>197aeea5-3445-4b6f-affd-a8aba4646255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/i/app_ui/img/icons/apex-edit-page.png']</value>
      <webElementGuid>d4fc2df6-b9ba-4b76-9dd3-3d851136cbe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
