<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ToggleRow text contains CE_CASH_MANAGER__473671</name>
   <tag></tag>
   <elementGuidId>79bfa7cc-dc0e-46ae-9805-f82776b73006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.a-IRR-controls-item.a-IRR-controls-item--search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = concat(&quot;ToggleRow text contains &quot; , &quot;'&quot; , &quot;CE_CASH_MANAGER_JOB_CUSTOM&quot; , &quot;'&quot;) or . = concat(&quot;ToggleRow text contains &quot; , &quot;'&quot; , &quot;CE_CASH_MANAGER_JOB_CUSTOM&quot; , &quot;'&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8f7b80ae-c720-484b-aa8a-b7a299fe0dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-controls-item a-IRR-controls-item--search</value>
      <webElementGuid>20620cea-1c5b-472f-b3de-878c4e82bfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>2c0083b7-46bf-4bbb-a7ed-93eb48431a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>control_text_422078530970563809</value>
      <webElementGuid>b2a5b8fc-8082-4f11-9ed6-30e3c94b573a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToggleRow text contains 'CE_CASH_MANAGER_JOB_CUSTOM'</value>
      <webElementGuid>d37077cf-aab8-40a5-a37c-363e658d5d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a_Collapsible1_scopeRoles_control_panel_content&quot;)/ul[@class=&quot;a-IRR-controls&quot;]/li[@class=&quot;a-IRR-controls-item a-IRR-controls-item--search&quot;]</value>
      <webElementGuid>0a16de16-6fc1-44aa-a372-6aeb0e7a6d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = concat(&quot;ToggleRow text contains &quot; , &quot;'&quot; , &quot;CE_CASH_MANAGER_JOB_CUSTOM&quot; , &quot;'&quot;) or . = concat(&quot;ToggleRow text contains &quot; , &quot;'&quot; , &quot;CE_CASH_MANAGER_JOB_CUSTOM&quot; , &quot;'&quot;))]</value>
      <webElementGuid>5040ce54-e297-4783-954d-8ff95625e98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a_Collapsible1_scopeRoles_control_panel_content']/ul/li</value>
      <webElementGuid>ad93a7f7-a7b4-4be2-b9d9-b0b02118c1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Settings'])[1]/following::li[1]</value>
      <webElementGuid>6aa1a80c-3064-4dd0-8e30-1a76a3de4938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[3]/following::li[1]</value>
      <webElementGuid>874c9b86-15f0-4210-9adf-44f03b744abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>2d1a8ddd-8639-4685-ad72-47e3b22fe443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
