<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_3</name>
   <tag></tag>
   <elementGuidId>9cf64c31-8a49-4e0e-9296-4e79c9bfda24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(5) > td.u-tL > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='247793320273899118']/tbody/tr[5]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SFTP_Rule3&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>985cda99-384f-4613-beec-82e8404310ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1180:9:14684135385907::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:26093,25246,7</value>
      <webElementGuid>506fcb3d-21fa-4e3d-a629-4e1613ed65b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SFTP_Rule3</value>
      <webElementGuid>32b798c6-9735-47af-8355-9ab7bb2fc698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;247793320273899118&quot;)/tbody[1]/tr[5]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>ac0b789c-4da7-4215-bca3-a29cd02093a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='247793320273899118']/tbody/tr[5]/td/a</value>
      <webElementGuid>b063b59f-d8df-477e-be4b-73347c87d46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SFTP_Rule3')]</value>
      <webElementGuid>51ef3fb0-a1c6-4951-b156-4c8ce5805ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SFTP'])[3]/following::a[1]</value>
      <webElementGuid>2304084c-3a30-4bcf-83f4-4811e4c71274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATADMIN - Kat Admin'])[6]/following::a[1]</value>
      <webElementGuid>d73ca238-761a-4f8d-9767-3e365dd11c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SFTP_Rule3'])[2]/preceding::a[1]</value>
      <webElementGuid>9a3f490c-aa04-4579-9656-1d45a6f5282b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOW'])[2]/preceding::a[1]</value>
      <webElementGuid>4b3e756c-1736-4003-be08-e9b0cb2e125c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SFTP_Rule3']/parent::*</value>
      <webElementGuid>2acca824-08a4-46f1-8bf8-992a7cc1f45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:9:14684135385907::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:26093,25246,7')]</value>
      <webElementGuid>2312db13-cd09-43f8-8c4d-18990105c34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/a</value>
      <webElementGuid>060e3c8e-5f4d-4ce4-a9b4-ada121558429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:9:14684135385907::::P9_RULE_REV_ID,P9_RULE_ID,P9_FROM:26093,25246,7' and (text() = 'SFTP_Rule3' or . = 'SFTP_Rule3')]</value>
      <webElementGuid>891798bc-96b0-4e64-842f-ff45400db265</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
