<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select any oneEBizApp_JDBC_EnvKTLNCl_cd37e2 (1)</name>
   <tag></tag>
   <elementGuidId>89e95d87-3928-451b-9005-698b9e8a78d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P0_ENVIRONMENT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ad39a1d-549e-4623-b79c-5d9e0363545b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>a39fcbf3-bf28-48a5-a083-9c9a8df6cf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>a761d1d4-cdf2-437a-a2ce-7b8cd1a2b33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>b149c128-59ca-4106-bae3-4a5763c43ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8748cd5f-a693-42f5-8e6d-145b4dfa4c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4449f651-f0dc-44e2-ba5f-9cb1234028eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P0_ENVIRONMENT');</value>
      <webElementGuid>a324e04e-d4a5-4d32-b285-bd86a09b2996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
</value>
      <webElementGuid>274c6661-3514-4bd3-991b-83ff7690ea53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT&quot;)</value>
      <webElementGuid>cd1f1816-b2f2-4c12-9f25-3083626f615e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P0_ENVIRONMENT' and @name = 'P0_ENVIRONMENT' and (text() = 'Select any one
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
' or . = 'Select any one
EBizApp_JDBC_Env
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NOVA_DEV1_ENV
SailPoint_Env
SailPoint_ENV2
TririgaDB_Env
Tririga_Env
WorkDay_Env
')]</value>
      <webElementGuid>55e61077-7ed5-4da7-8c46-e261a09915fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P0_ENVIRONMENT']</value>
      <webElementGuid>8cd5b716-a1a6-41be-b348-9fe459c20a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>ed305496-a66a-4178-a6f3-9df24dad0989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>e82cdebd-bbe1-4d3b-8030-341ebab2fdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scope Identity Groups'])[1]/preceding::select[1]</value>
      <webElementGuid>c6b0b919-93e0-466e-bb7b-14107a5cf5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Identity Group'])[1]/preceding::select[1]</value>
      <webElementGuid>edd4ca7d-0fec-47d5-b544-fb90e22b6b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>da0a799d-ed47-4d5e-9d76-b7508740d85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>f0a72344-268a-47f3-b9dc-66e7860c4b71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
