<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage Violation (2) (1) - Copy</name>
   <tag></tag>
   <elementGuidId>2316ae7c-3975-475f-8893-b1caf2856e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div[1]/div/ul/li/ul/li[2]/ul/li[4]/ul/li[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-TreeView-label.is-focused</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'f?p=1180:74:6814074204014:::74::' and (text() = 'Manage Violation' or . = 'Manage Violation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>455051c7-d227-4b34-adeb-f13019ca2b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1ed7a772-14b0-4330-954a-91080640812f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>c136f921-f703-4594-8728-3e4190309838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-label is-focused</value>
      <webElementGuid>078e8942-5f24-44e3-a626-4a2a80a5755f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1180:74:6814074204014:::74::</value>
      <webElementGuid>93f0d86b-eaa2-4efc-83b4-72024ab7ab4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6af2e3ef-4a17-4218-a09d-c7d5629fc6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ecb4da39-fca1-4bb4-9b4f-808c119b626c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Violation</value>
      <webElementGuid>e4b99957-c290-42c5-9d91-756065e9ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_12&quot;)/div[@class=&quot;a-TreeView-content is-hover&quot;]/a[@class=&quot;a-TreeView-label is-focused&quot;]</value>
      <webElementGuid>e4826f00-3b29-4c63-b085-81f9e6bd600a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_12']/div[2]/a</value>
      <webElementGuid>ea1b39f9-ceea-406b-b68f-5260e2bcb043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage Violation')]</value>
      <webElementGuid>c055874c-0014-44d4-97c0-19fbae8ff396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:74:6814074204014:::74::')]</value>
      <webElementGuid>7c99d2f0-2be8-4ec0-813c-21f0a229d73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/a</value>
      <webElementGuid>26213d5a-b433-4c76-abd2-ae9f3c5651f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:74:6814074204014:::74::' and (text() = 'Manage Violation' or . = 'Manage Violation')]</value>
      <webElementGuid>3862bbc9-34e0-469e-bf41-b1687559ef45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
