<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Rows Per Page (1) (1) (1) (1) (1)</name>
   <tag></tag>
   <elementGuidId>8142346f-7b15-4840-aa20-093677666e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uacReport_actions_menu_3i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='uacReport_actions_menu_3i']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee2aa50f-b3c3-4e6d-980e-458aeb921dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c28749d0-cb98-4464-90b6-b0cbf0deed0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uacReport_actions_menu_3i</value>
      <webElementGuid>7f3ff234-749c-4a06-98cd-409964fe5cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>40d7de7c-08b4-4cbf-83e9-8c751edd2d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>51589752-a2f3-43ff-b2ec-c259c8c84852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>fc048a61-ff2f-4c9f-9edb-6614a2f476f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8223ef50-4466-4b8d-a457-c1b5766ccf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rows Per Page</value>
      <webElementGuid>6de9d6df-8c9c-433c-b2d1-ef3c6c7cd55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uacReport_actions_menu_3i&quot;)</value>
      <webElementGuid>45cf5b46-c2e8-46ec-8b37-01c2b457b653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='uacReport_actions_menu_3i']</value>
      <webElementGuid>6090c887-2968-4291-bcc0-dcf2c98c2716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='uacReport_actions_menu_3']/div/span/button</value>
      <webElementGuid>86916b35-6a0d-4fa4-b255-da12e14cddc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span/button</value>
      <webElementGuid>dad935a4-87eb-40b0-85a3-d57eb1829b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'uacReport_actions_menu_3i' and (text() = 'Rows Per Page' or . = 'Rows Per Page')]</value>
      <webElementGuid>c6b6b2f0-c8b3-48fb-94cd-b94fa8993277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
