<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_File (Value Required)</name>
   <tag></tag>
   <elementGuidId>0b358cc2-6609-47a5-88c1-66df173c96e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P37_FILE_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P37_FILE_LABEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ab0b67d6-7ee6-4222-b09c-11fadab35546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P37_FILE</value>
      <webElementGuid>11173ba1-2a99-4ed2-b52f-1a6d0b148141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P37_FILE_LABEL</value>
      <webElementGuid>94bcfdc6-1303-45f4-aad4-4977e78a4f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>a63e7e96-d0f7-4743-8dc5-39b78a6d5aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>File (Value Required)</value>
      <webElementGuid>008f16aa-7e46-4604-882e-d7e21d47f8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P37_FILE_LABEL&quot;)</value>
      <webElementGuid>d4ac1380-3f89-4cf6-9a23-5bba7cfa84c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Upload Data/Page_Manage Snapshot/iframe</value>
      <webElementGuid>1936b30a-cada-4f5e-a9d8-aec5baf25617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P37_FILE_LABEL']</value>
      <webElementGuid>bc31aa5f-b6f5-400d-a4a0-5f2986e7d70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P37_FILE_CONTAINER']/div/label</value>
      <webElementGuid>57d38d79-3711-4c60-b628-b9ffbc075522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[3]/following::label[1]</value>
      <webElementGuid>f31d14a1-dfe1-4844-bfda-298cf7674398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::label[1]</value>
      <webElementGuid>fd42becd-a273-47b3-ad0b-39056eb81923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='File']/parent::*</value>
      <webElementGuid>2bf793e0-25dc-41b4-987f-e2bf23262ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/label</value>
      <webElementGuid>728e93f9-adf7-4d65-b9e7-33ca7cbda149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P37_FILE_LABEL' and (text() = 'File (Value Required)' or . = 'File (Value Required)')]</value>
      <webElementGuid>1db710d9-9d62-4729-b9ae-91795fbb508c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
