<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Column Name</name>
   <tag></tag>
   <elementGuidId>806d5b4d-6240-4e44-b653-9008640e506c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C173383534046224615_HDR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='C173383534046224615_HDR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3b85ddb-564d-43e0-a7ed-45edeed3d859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-headerLabel</value>
      <webElementGuid>fe238f35-5fa3-4da7-9d9b-d8e2e17a0914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C173383534046224615_HDR</value>
      <webElementGuid>88f76db0-f3e9-45b8-a7aa-81d90108717e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Column Name</value>
      <webElementGuid>34d5f19f-042d-4b07-a882-a26cbff75ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C173383534046224615_HDR&quot;)</value>
      <webElementGuid>73b8d1ac-a67c-4319-b099-3d3172d1eb83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='C173383534046224615_HDR']</value>
      <webElementGuid>6e34fc21-b1de-45c6-b855-61a071845f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='oItemsCloudSqlIg_ig_grid_vc_cur']/span</value>
      <webElementGuid>da0d6d71-77fe-42ee-af4a-f3e6a321bde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/span</value>
      <webElementGuid>df19477d-b6d8-4a74-ade4-2a719f9ad607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'C173383534046224615_HDR' and (text() = 'Column Name' or . = 'Column Name')]</value>
      <webElementGuid>7d440193-206a-4cc8-b91f-9b83dd2ce556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
