<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AU - ERP Cloud - AR Customer Maintenance_a3b41f</name>
   <tag></tag>
   <elementGuidId>0e94098b-471d-43aa-8b82-85540cea7e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report_scopeRoles']/div/div/table/tbody/tr[2]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>49acfe31-0c7f-4059-bfc8-cfedeb2d694d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Report-cell</value>
      <webElementGuid>b9a9984c-52eb-48e9-a38b-6bfbd02492d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>ROLE_NAME</value>
      <webElementGuid>4df2abaa-416c-4ad5-9967-741b25ed268d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AU - ERP Cloud - AR Customer Maintenance (Approval Required)</value>
      <webElementGuid>4d46f1eb-7e81-4204-80a2-4013bbe9a389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_scopeRoles&quot;)/div[@class=&quot;t-Report-wrap&quot;]/div[@class=&quot;t-Report-tableWrap&quot;]/table[@class=&quot;t-Report-report&quot;]/tbody[1]/tr[2]/td[@class=&quot;t-Report-cell&quot;]</value>
      <webElementGuid>5593ff73-64f7-4ba7-b8b2-9a13047de0b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_scopeRoles']/div/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>9bc7a78f-03dc-48cc-9980-ea3114f52869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1'])[2]/following::td[2]</value>
      <webElementGuid>02610cd1-31fd-447f-9529-ebefdf5b5ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1'])[1]/following::td[4]</value>
      <webElementGuid>d8740010-0576-4b8d-9132-c9b92b00cca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU - ERP Cloud - AR Customer Maintenance (Approval Required)'])[2]/preceding::td[1]</value>
      <webElementGuid>40a4294b-3fcf-4a4a-a30c-bb46de7277c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTLN_EACM_USER1'])[3]/preceding::td[4]</value>
      <webElementGuid>806dcf07-b708-406d-bfab-7fec2b6f1873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AU - ERP Cloud - AR Customer Maintenance (Approval Required)']/parent::*</value>
      <webElementGuid>6ca857b0-a8f3-456d-9d7a-f78f74ab9f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>f5f806e3-49ab-41cc-9c3b-6e5751226bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AU - ERP Cloud - AR Customer Maintenance (Approval Required)' or . = 'AU - ERP Cloud - AR Customer Maintenance (Approval Required)')]</value>
      <webElementGuid>3c51beef-f525-4c4f-8bf9-9306099df4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
