<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NZ - ERP Cloud - Procurement Catalog Adm_affa37 (2)</name>
   <tag></tag>
   <elementGuidId>bb3175f3-b961-4a0c-b569-2b2746c3743c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='R326052387980911517_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R326052387980911517_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7881cb70-0d3d-4702-9ead-d5f561678b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>22b1d2fd-0a27-4d49-ba86-99a01fea18a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d196459c-e7b0-489b-8933-bf190f2378cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tC is-focused</value>
      <webElementGuid>6329d33d-5938-4e7d-8324-3caf5d74fb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R326052387980911517_ig_grid_vc_ctx R326052387980911517_ig_grid_vc_cur</value>
      <webElementGuid>87747245-c847-4578-9a4c-be3138d41bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R326052387980911517_ig_grid_vc_cur</value>
      <webElementGuid>575b1136-66a7-4edc-884a-c1d5021cf4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NZ - ERP Cloud - Procurement Catalog Administrator (Approval Required)</value>
      <webElementGuid>d92be952-573c-4a87-8c54-fe24f873514c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R326052387980911517_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>a19fde30-6213-4e87-9bb2-b1c0446bee49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R326052387980911517_ig_grid_vc_cur']</value>
      <webElementGuid>03e0eb1c-291f-4651-8584-1d113732d721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R326052387980911517_ig_grid_vc']/div[3]/div[4]/table/tbody/tr[21]/td</value>
      <webElementGuid>43ca9994-9709-41c6-9132-bb8e762384e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[2]/following::td[1]</value>
      <webElementGuid>75c9fe10-7fbe-4579-9268-d2af2a281f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU - ERP Cloud - AP Financial Analyst'])[2]/following::td[2]</value>
      <webElementGuid>a920d9c7-0730-45fe-ab3c-ad12ef179504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NZ - ERP Cloud - Procurement Catalog Administrator (Approval Required)'])[2]/preceding::td[1]</value>
      <webElementGuid>32927538-d5d5-4513-89f3-1b05ead35b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[3]/preceding::td[2]</value>
      <webElementGuid>dcf9fe62-b3d5-4ffc-bb1d-edf2fa76ab34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NZ - ERP Cloud - Procurement Catalog Administrator (Approval Required)']/parent::*</value>
      <webElementGuid>462eac6a-f0b2-42bd-ba1c-40aa134cab6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td</value>
      <webElementGuid>f4460556-e77b-4cfd-bdc9-85ef6fcb835c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'R326052387980911517_ig_grid_vc_cur' and (text() = 'NZ - ERP Cloud - Procurement Catalog Administrator (Approval Required)' or . = 'NZ - ERP Cloud - Procurement Catalog Administrator (Approval Required)')]</value>
      <webElementGuid>bf96e550-18ae-4089-bf65-0c547c12799a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
