<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NZ - ERP Cloud - GL Close Coordinator (A_fe2504 (1)</name>
   <tag></tag>
   <elementGuidId>f92f031e-6071-4f91-8559-ed244aa8d5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='R325075769582901511_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R325075769582901511_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>011caf92-70b0-4afc-bbf9-d19922c747ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>4f71aceb-494b-41f4-8bf4-dab123766056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a479b17-d629-42f4-9bb9-8939b69c3a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tC is-focused</value>
      <webElementGuid>15f7b8e2-8060-42a5-bf21-e26a7783aaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R325075769582901511_ig_grid_vc_ctx C326040930152329086_HDR R325075769582901511_ig_grid_vc_cur</value>
      <webElementGuid>158f0152-a2f7-4746-8e0d-814bfb5d1412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R325075769582901511_ig_grid_vc_cur</value>
      <webElementGuid>a6797869-00a4-4f7b-a977-ec8ea7f884b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NZ - ERP Cloud - GL Close Coordinator (Approval Required)</value>
      <webElementGuid>4e4fc650-3e61-4576-b68e-abc3e4c4a45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R325075769582901511_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>834f8416-454e-4a65-9b3a-82bd643aa0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R325075769582901511_ig_grid_vc_cur']</value>
      <webElementGuid>646a81ff-f7b2-4b33-a397-5252d5bbf4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R325075769582901511_ig_grid_vc']/div[3]/div[4]/table/tbody/tr[11]/td</value>
      <webElementGuid>c2632f5c-c244-43bb-8b2a-43348152fd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU-OTHER'])[7]/following::td[1]</value>
      <webElementGuid>6e69287a-5d80-4b80-ac94-028ccb7950b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AU - ERP Cloud - Enterprise Contract Administrator (Approval Required)'])[2]/following::td[2]</value>
      <webElementGuid>b9c95120-d69c-4933-9ff8-93009fb20030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NZ - ERP Cloud - GL Close Coordinator (Approval Required)'])[2]/preceding::td[1]</value>
      <webElementGuid>e81ce384-c34f-4ec2-bf0f-c62815bbe5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NZ-TAX'])[2]/preceding::td[2]</value>
      <webElementGuid>1703024c-5f41-445e-ba93-35f6ab425523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NZ - ERP Cloud - GL Close Coordinator (Approval Required)']/parent::*</value>
      <webElementGuid>211f8ca0-b1ec-423c-93ab-237e407d9c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td</value>
      <webElementGuid>200f0703-16c4-4537-8b57-9f63b8fa22cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'R325075769582901511_ig_grid_vc_cur' and (text() = 'NZ - ERP Cloud - GL Close Coordinator (Approval Required)' or . = 'NZ - ERP Cloud - GL Close Coordinator (Approval Required)')]</value>
      <webElementGuid>5bfb02e3-a3cc-49cb-9613-ab1dd74e1f55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
