<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Current Progress_t-Icon a-Icon icon-check</name>
   <tag></tag>
   <elementGuidId>4ec6d060-1bee-498c-bc88-24c029b6c84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.t-Icon.a-Icon.icon-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4f665e7-f02d-4721-b934-a47522883d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Icon a-Icon icon-check</value>
      <webElementGuid>8b0cad6d-6f0b-487d-a17a-68ed05d64400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L158169670482136833&quot;)/div[@class=&quot;t-WizardSteps-wrap&quot;]/span[@class=&quot;t-WizardSteps-marker&quot;]/span[@class=&quot;t-Icon a-Icon icon-check&quot;]</value>
      <webElementGuid>a824b6e5-5ec4-4fc0-9b6f-7d601171db0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span</value>
      <webElementGuid>3e268cc2-a4ee-4cc7-b4b0-a4bf82115feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='L158169670482136833']/div/span/span</value>
      <webElementGuid>291add58-a356-4827-90ce-6985edf8de97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
