<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EBS R12.2_f01</name>
   <tag></tag>
   <elementGuidId>ff49a250-fcc5-4aca-a92b-04aa00fd2a00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td.u-tL > input[name=&quot;f01&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='f01'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;559_ObjectSet DPS_PR_PO_SameUser DPS_PR_PO_SameUser 05-FEB-2026 KATADMIN Active EBS R12.2&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddf02fdd-02b9-4994-a897-20dbdc4b1b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52e90636-ea95-4f54-a0b0-2c355d6c4394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f01</value>
      <webElementGuid>137e8f90-900c-4103-b19c-a1f9db5e5045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>365</value>
      <webElementGuid>59e7787e-1aa5-46b0-a525-15b74ef88dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>spCheckChange(this);</value>
      <webElementGuid>85e73d6e-4085-4bdb-80b2-f55de4d93e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;433726414293115959&quot;)/tbody[1]/tr[4]/td[@class=&quot;u-tL&quot;]/input[1]</value>
      <webElementGuid>d6ae8da3-6ac6-4e66-9fac-58eea4a913ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='f01'])[3]</value>
      <webElementGuid>baa269a8-1277-4847-99fb-568466c3e43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='433726414293115959']/tbody/tr[4]/td/input</value>
      <webElementGuid>f27aff3c-4ac0-4d9d-a82b-814c95b172bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>6313960c-bf2e-421a-96ac-b0105f2d99ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'f01']</value>
      <webElementGuid>e2c0b2bd-4d5a-43ec-99a0-a018e7bbcfd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
