<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mandatory required number of responses</name>
   <tag></tag>
   <elementGuidId>10464340-6a4a-4857-916c-d4f4506129ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P130_RESP_TO_CLOSE_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P130_RESP_TO_CLOSE_LABEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>34612b30-2514-44ee-ad79-34e3eb2b96a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P130_RESP_TO_CLOSE</value>
      <webElementGuid>88c8de28-9397-4c85-b261-ce10ba9d92e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P130_RESP_TO_CLOSE_LABEL</value>
      <webElementGuid>e3206ee6-4931-4b63-8bc3-4de1b56309c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>eda6684c-d52a-4344-b70a-6ed6c9ae754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mandatory required number of responses:</value>
      <webElementGuid>ff38bf9d-1da7-4ba5-b651-274ed8ebf78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P130_RESP_TO_CLOSE_LABEL&quot;)</value>
      <webElementGuid>78d1e914-540f-453b-832d-67787fad8871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P130_RESP_TO_CLOSE_LABEL']</value>
      <webElementGuid>f7ce9327-3784-45ff-b722-cd36cc5ddbd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P130_RESP_TO_CLOSE_CONTAINER']/div/label</value>
      <webElementGuid>5ebc85f5-7121-42e7-9e93-67d14df79d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>8458bac1-d8b7-4df3-9aac-239c04ab38b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P130_RESP_TO_CLOSE_LABEL' and (text() = 'Mandatory required number of responses:' or . = 'Mandatory required number of responses:')]</value>
      <webElementGuid>03d0928a-18fc-4b9a-bad9-3e4f7a2e264a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
