<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Approval Level_P23_APP_LEVEL_1</name>
   <tag></tag>
   <elementGuidId>81fc6f61-761d-4206-bf23-72d1ae0c8c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='P23_APP_LEVEL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P23_APP_LEVEL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2-Primary Owner&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e50c05d6-e981-42af-bcc6-bbb78d6fa95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_APP_LEVEL</value>
      <webElementGuid>5cffa748-1dd3-470b-b5db-6fca4a1f6572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display_only apex-item-display-only</value>
      <webElementGuid>550448f3-0afd-4b90-b0d5-b2cbb94dd50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-escape</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>50f04a3a-e69f-4601-8967-3f5b2f178863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2-Primary Owner</value>
      <webElementGuid>9676e0e5-3186-4948-8fd7-615bd14d7add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_APP_LEVEL&quot;)</value>
      <webElementGuid>fa672921-14e9-4919-8032-84b2f87e4343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='P23_APP_LEVEL']</value>
      <webElementGuid>450bf0b7-caac-45ae-84e5-776722f7213f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_APP_LEVEL_CONTAINER']/div[2]/div/span</value>
      <webElementGuid>d9d6f9cf-5cd5-475f-a4f2-171519bd307a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Level'])[1]/following::span[1]</value>
      <webElementGuid>44f2af1a-1304-4d76-bca6-a4c7afedf978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::span[2]</value>
      <webElementGuid>b311498a-63e8-4ea4-ac48-10cfce589cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level Type'])[1]/preceding::span[2]</value>
      <webElementGuid>ed2be0b2-4b3a-4649-a9da-bdc3267e502d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary'])[1]/preceding::span[2]</value>
      <webElementGuid>ef9c098e-4004-4291-9d40-0bbeb86f7966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2-Primary Owner']/parent::*</value>
      <webElementGuid>fea3e2bd-6e7d-44b3-a518-eadb21ac05a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/span</value>
      <webElementGuid>33d62368-3d96-43fd-8323-9817c533073b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'P23_APP_LEVEL' and (text() = '2-Primary Owner' or . = '2-Primary Owner')]</value>
      <webElementGuid>942c22f0-3317-4a0c-aebb-6bb4c7d3f5e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
