<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Level Type_P23_TYPE (2)</name>
   <tag></tag>
   <elementGuidId>d66c1e07-ebcb-40df-ad13-05dbe9c82ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='P23_TYPE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P23_TYPE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Primary&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d267c5e-e9da-4001-8367-b717f0a99fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_TYPE</value>
      <webElementGuid>56885515-479d-4690-8846-d5c3c6857d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display_only apex-item-display-only</value>
      <webElementGuid>1f2db8ab-e9c5-4eec-9e29-877fbd620661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-escape</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e26ce63c-db59-4f46-b449-22bd5dc82714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primary</value>
      <webElementGuid>68e83486-0e72-43b2-ae64-ea2d40c55925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_TYPE&quot;)</value>
      <webElementGuid>53b3d1df-7b51-48db-b8db-a8beb28c64f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='P23_TYPE']</value>
      <webElementGuid>70a0b6b7-2723-4eab-a291-3ff36251690d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_TYPE_CONTAINER']/div[2]/div/span</value>
      <webElementGuid>097a416e-9fae-4ee1-9a51-28b460727259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level Type'])[1]/following::span[1]</value>
      <webElementGuid>79c50aa3-3400-4df3-990b-ecf1d5eaaf56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Level'])[1]/following::span[3]</value>
      <webElementGuid>bf86dc22-4d0e-4b31-ba91-d42235aaac48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Type'])[1]/preceding::span[2]</value>
      <webElementGuid>008f0be2-bb41-4320-b500-e9afb9a60958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsibility'])[1]/preceding::span[2]</value>
      <webElementGuid>a9b7c8d6-47f1-43d1-a62f-957d6a1d63d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Primary']/parent::*</value>
      <webElementGuid>70ef1f6f-df95-49d2-b82e-7eba5550e37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/span</value>
      <webElementGuid>8344ad4f-1e98-4b86-88af-adfc8c9d6035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'P23_TYPE' and (text() = 'Primary' or . = 'Primary')]</value>
      <webElementGuid>43e9b482-2576-4649-838e-6e51bbd4dd3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
