<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SODTST_1912_V5</name>
   <tag></tag>
   <elementGuidId>4c73750d-b8f0-49c8-bc0a-7a056fd0044c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.u-tL > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='169645300712451664']/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SODTST_1912_V5&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99f9bc78-f12a-4e8f-a4f1-eb91cf57d6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1180:35:9121900953422::::P35_REQUEST_ID:12965</value>
      <webElementGuid>7c57cddb-2c6a-4b83-acab-886bce97123e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SODTST_1912_V5</value>
      <webElementGuid>41308d2d-23d8-4274-851b-a401cb7d0da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;169645300712451664&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>b12a41fa-975b-4e8b-8e4d-60e8c84415d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='169645300712451664']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>0d5a3239-012e-459d-8ccb-02b951687f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SODTST_1912_V5')]</value>
      <webElementGuid>1770242c-d755-4584-ba92-62a13c87df69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/following::a[12]</value>
      <webElementGuid>3e22e567-2d0a-41db-af59-b1172cfc0d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SODTST_1912_V5'])[1]/following::a[12]</value>
      <webElementGuid>68bd5961-4417-40f2-a397-032241618265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SODTST_1912_V5'])[3]/preceding::a[1]</value>
      <webElementGuid>dfaf83a9-2db0-4196-b3c9-cf3bdc71d0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOD Detective'])[1]/preceding::a[1]</value>
      <webElementGuid>347624b4-be05-4985-8721-6c8ae89e2002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1180:35:9121900953422::::P35_REQUEST_ID:12965')]</value>
      <webElementGuid>9f2b35fa-6f73-4e43-9979-ed4349e41fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>86b3f522-4d22-43fc-85d5-770a9bd91e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1180:35:9121900953422::::P35_REQUEST_ID:12965' and (text() = 'SODTST_1912_V5' or . = 'SODTST_1912_V5')]</value>
      <webElementGuid>13141f84-9bd4-4112-9eaf-988efb4630a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
