<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Manage SOD Test_B169646823131451684</name>
   <tag></tag>
   <elementGuidId>7f3d749a-0173-4843-9800-f41e115e71ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B169646823131451684</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B169646823131451684']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Create&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>092bc5a1-d476-491b-a2ca-ce46d327a89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.navigation.redirect('f?p=1001:30:6871350036934:::RP,30:P30_COMPONENT,P30_ENVIRONMENT,P30_REDIRECT_APP,P30_REDIRECT_PAGE:SOD_TEST,8848,1180,34');</value>
      <webElementGuid>dc4195b1-b184-4be7-997a-97be9b40268f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button </value>
      <webElementGuid>5dd94cf0-14a9-47f9-a05d-bc80723ef6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>006f2655-f4e6-4dfb-8501-11db21f8ed9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B169646823131451684</value>
      <webElementGuid>def09611-3f3b-4380-9e97-d9613f427bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>d661bce3-df2f-41b6-9af9-af236905ab8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B169646823131451684&quot;)</value>
      <webElementGuid>69437fba-55e3-4114-8f24-7fdc90d2ea85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B169646823131451684']</value>
      <webElementGuid>5cf30db9-d2a5-493b-b03d-ab01511e3762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R169645132708451655']/div/div[2]/button</value>
      <webElementGuid>e9cdfc6e-f462-4c95-a750-fbb228e803dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage SOD Test'])[4]/following::button[1]</value>
      <webElementGuid>b045a657-d1a5-40cf-bdf3-c93c811e4244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::button[1]</value>
      <webElementGuid>0056ad25-938b-4420-b5b1-229ce6c2d1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::button[2]</value>
      <webElementGuid>0422853c-7bd9-4d79-8b0d-15d99bad7ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>31437e52-b5cb-4f54-a33f-41a79d96dc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B169646823131451684' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>3b767e2c-9e63-4817-934e-e1de01346864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
