<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select any oneCoupa_Env1EBizApp_JDBC_e66b03</name>
   <tag></tag>
   <elementGuidId>44173591-4e3c-4a3f-b0e6-6c8f8d66f218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P0_ENVIRONMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Environment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bd7ad44d-7994-428c-bc9c-b743866a11a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>44511769-5633-4f9b-b2bb-a462e77d1eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>9ea8b647-e429-4ce8-8294-cd62a7cb60be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>161f406b-b035-487e-82b4-30fa9bfcdac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>839b9a31-4861-4d6a-a026-cd0510c6612a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f337a2b6-523d-488a-9959-d164b89d2018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P0_ENVIRONMENT');</value>
      <webElementGuid>b360b031-e975-4f4a-a08b-52d1e72b3f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
IDM_Coupa
JDE_Env
JDE_TEST
KTLNEBS_MonitorPaaS
KTLN_CloudERP
Kyriba_Env1
MAJUL_EBS
MXYZ
NEW_CLOUDERP
OS_IDM_Copy
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
Y_DEV_OS_ENV_Copy
Z_Azure
Z_EBSR12_2
Z_EBS_TestEnv.
Z_EBS_XRef1
Z_GRMCloud_XRef1
Z_Hybris_Env
Z_SUCCESSFACTORS_ENV
Z_ServiceNow
Z_SuccessFactor
</value>
      <webElementGuid>da8a8896-ca35-4099-b7c6-3478f891ccc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT&quot;)</value>
      <webElementGuid>222df07f-7efd-4594-a3fb-bc6d2e61b869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P0_ENVIRONMENT']</value>
      <webElementGuid>bd5d137d-df26-4abb-a69f-e5234c7db0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>7f9ac313-7d61-4331-ba18-4666dbe5179b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>b5f1bff7-d007-4c64-bce5-d42b29a39659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>4544d649-10a7-4b2d-a30a-60ea89b43a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage SOD Test'])[4]/preceding::select[1]</value>
      <webElementGuid>582909d1-32d0-4afe-b5e1-2362efe857af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::select[1]</value>
      <webElementGuid>e0c1e6e5-281e-49fa-a88c-a685e6fd3bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ca34ade5-e089-472f-b7b6-39e92baf410e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P0_ENVIRONMENT' and @name = 'P0_ENVIRONMENT' and (text() = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
IDM_Coupa
JDE_Env
JDE_TEST
KTLNEBS_MonitorPaaS
KTLN_CloudERP
Kyriba_Env1
MAJUL_EBS
MXYZ
NEW_CLOUDERP
OS_IDM_Copy
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
Y_DEV_OS_ENV_Copy
Z_Azure
Z_EBSR12_2
Z_EBS_TestEnv.
Z_EBS_XRef1
Z_GRMCloud_XRef1
Z_Hybris_Env
Z_SUCCESSFACTORS_ENV
Z_ServiceNow
Z_SuccessFactor
' or . = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
IDM_Coupa
JDE_Env
JDE_TEST
KTLNEBS_MonitorPaaS
KTLN_CloudERP
Kyriba_Env1
MAJUL_EBS
MXYZ
NEW_CLOUDERP
OS_IDM_Copy
SAP_DEMO
SAP_ECC
SAP_S4HANA
SFTP_Env2
SUCCESSFACTORS_ENV
SailPoint_ENV2
SailPoint_Env
ServiceCafe_Env
TEST_JDE92_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
Y_DEV_OS_ENV_Copy
Z_Azure
Z_EBSR12_2
Z_EBS_TestEnv.
Z_EBS_XRef1
Z_GRMCloud_XRef1
Z_Hybris_Env
Z_SUCCESSFACTORS_ENV
Z_ServiceNow
Z_SuccessFactor
')]</value>
      <webElementGuid>86d51e69-998a-4cbc-a1d7-c45b3e2425df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
