<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_FSOD.FSOD_NETWORK_USERS</name>
   <tag></tag>
   <elementGuidId>d9687617-0708-4259-b97e-a84ca2897f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oItemsSodIg_ig_grid_vc_cur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'FSOD.FSOD_NETWORK_USERS' or . = 'FSOD.FSOD_NETWORK_USERS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0dd5cb2d-942a-4061-bdd2-a888b3e557ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>b4e31b6f-10c2-41bd-a1d9-9a87892e73fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48d8515e-9359-4acb-9824-73d01ef0958b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-focused</value>
      <webElementGuid>cb0b4621-1f15-424c-a88d-f110356c3236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>oItemsSodIg_ig_grid_vc_ctx oItemsSodIg_ig_grid_vc_cur</value>
      <webElementGuid>6fcad7e3-bd36-416b-b0ad-907bd0653535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oItemsSodIg_ig_grid_vc_cur</value>
      <webElementGuid>2e76a230-2f40-4d23-950b-a80e8cee344f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FSOD.FSOD_NETWORK_USERS</value>
      <webElementGuid>cefdc695-f17f-42b9-918c-35f4f9b9d265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oItemsSodIg_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>98d171d2-2aad-4628-8598-84b64144f042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'FSOD.FSOD_NETWORK_USERS' or . = 'FSOD.FSOD_NETWORK_USERS')]</value>
      <webElementGuid>4a25ee46-87e5-461a-93cf-138d6b17ebc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='oItemsSodIg_ig_grid_vc_cur']</value>
      <webElementGuid>769c2788-77aa-46f1-a630-ddc2329235f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oItemsSodIg_ig_grid_vc']/div[2]/div[4]/table/tbody/tr[2]/td[4]</value>
      <webElementGuid>9bf369f1-d7c7-447a-9f94-0b444110f1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='employee id'])[1]/following::td[1]</value>
      <webElementGuid>2964080c-e6eb-4219-b4b2-d98b8012fd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::td[4]</value>
      <webElementGuid>a2e95c34-6a41-4d49-8e9b-c21e516d9e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDENTITY_ID'])[1]/preceding::td[1]</value>
      <webElementGuid>cdf117f7-772f-448b-8e1e-9fd83fb04437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VARCHAR2'])[2]/preceding::td[2]</value>
      <webElementGuid>d717cfb8-8399-416f-b025-fcfd062fe798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FSOD.FSOD_NETWORK_USERS']/parent::*</value>
      <webElementGuid>8838b072-dfba-4980-8d18-2a0de4b5bde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]</value>
      <webElementGuid>0f00caf2-469c-42bb-9dce-bac5484b48eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
