<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter</name>
   <tag></tag>
   <elementGuidId>8aed4156-db32-4757-a977-fddeac5b6541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R160504369387363436_actions_menu_2i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R160504369387363436_actions_menu_2i']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53009e33-f03d-4166-847a-859593f52e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a21f4174-c634-4b99-8264-a3ac68988a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R160504369387363436_actions_menu_2i</value>
      <webElementGuid>23fc438a-1450-4b9b-acd3-0b3c36fad99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>71a12ed5-4a87-4c8c-b6ce-7e6910283d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>3d624dfa-0712-4327-a7e2-f78443d1e312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>7967924f-e36f-425a-90c2-b98554e27b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R160504369387363436_actions_menu_2i&quot;)</value>
      <webElementGuid>2326e458-8ba1-4db8-a5e4-63b9799432e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R160504369387363436_actions_menu_2i']</value>
      <webElementGuid>fce17874-5f6e-469b-b609-3d9e561dbdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='R160504369387363436_actions_menu_2']/div/span/button</value>
      <webElementGuid>5dc9ff4e-de61-4de4-a7c1-aaef10785e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/button</value>
      <webElementGuid>15ba9910-f8ee-4154-8597-6bbb83bd6c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'R160504369387363436_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>41447bf0-2cc0-408c-aba5-819198c6397c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
