<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_a-TreeView-toggle_1</name>
   <tag></tag>
   <elementGuidId>0bf5f716-8658-479f-9385-53537dff67f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_2 > span.a-TreeView-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46684b4a-24a5-4fba-bef6-77ad32507ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>b109eeda-c12f-4969-b57d-3bf0b3889d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_2&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>5ea48c65-12b6-4d0c-84e2-a6acb3e8b479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_2']/span</value>
      <webElementGuid>07d89072-b16d-4d73-9052-1a81805c006c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>37077477-f936-4239-9f64-ad7d40ea29fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
