<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Company CodeCompany NameApplication _49b7ca</name>
   <tag></tag>
   <elementGuidId>bba5e5fd-b57e-4bdc-86c4-483468744bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R153811083771916517_column_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='R153811083771916517_column_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8ba9d286-c438-434a-9841-55c73fbd6b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R153811083771916517_column_name</value>
      <webElementGuid>b4122b92-3da7-48ee-a3bb-df55f72f4e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>298c1eaf-1d6c-4176-8880-19513a0a3586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>b36d6bf3-957c-42e7-9e39-b2d336e49118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>acba9c12-d6b2-4053-9aa1-f9363d234368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>12c2c0a1-ad87-4dcc-9c37-455d89d7daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company CodeCompany NameApplication NameUsernameUser Email Address</value>
      <webElementGuid>b22dd4bc-eb6e-415b-941a-96084cfffcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R153811083771916517_column_name&quot;)</value>
      <webElementGuid>222016b7-abc6-4ec2-ac73-9fe9eb2ab93e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='R153811083771916517_column_name']</value>
      <webElementGuid>aebf700f-ff14-49d4-ae7d-27fa28f7ae3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R153811083771916517_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>b81ebd96-d93b-4769-8788-05412f57ca51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>09f37618-4707-464f-a766-df69e3e5f920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'R153811083771916517_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'Company CodeCompany NameApplication NameUsernameUser Email Address' or . = 'Company CodeCompany NameApplication NameUsernameUser Email Address')]</value>
      <webElementGuid>bda6394f-c2c6-4eeb-a5bf-161d574c3030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
