<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_APPS.XXSP_USER_EBSAPPL_V</name>
   <tag></tag>
   <elementGuidId>76004b13-c46b-4246-977b-1c75707cccdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oItemsSodJdbcIg_ig_grid_vc_cur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'APPS.XXSP_USER_EBSAPPL_V' or . = 'APPS.XXSP_USER_EBSAPPL_V')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Column 4.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>73d60664-2eec-493c-8fda-a5773deb22cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>eacdb365-7b9b-456b-8ed0-de39a7435221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7505b9e-8f45-4d34-89b8-fe99d75202a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tE is-focused</value>
      <webElementGuid>254b3ce7-8120-42b6-b0bc-983262ca065d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>oItemsSodJdbcIg_ig_grid_vc_ctx SOD_JDBC_TAB_ID_HDR oItemsSodJdbcIg_ig_grid_vc_cur</value>
      <webElementGuid>1d012c9e-0f16-4020-b454-ac08c6248f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oItemsSodJdbcIg_ig_grid_vc_cur</value>
      <webElementGuid>c1273f61-06eb-4076-9032-917a4c30c58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPS.XXSP_USER_EBSAPPL_V</value>
      <webElementGuid>c5e3e5ef-3681-44a7-83fc-26525c1e649b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oItemsSodJdbcIg_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>be3a812f-65b0-4c67-b1d2-3197a9b80b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'APPS.XXSP_USER_EBSAPPL_V' or . = 'APPS.XXSP_USER_EBSAPPL_V')]</value>
      <webElementGuid>26a40842-1087-415e-b0ad-f89cf8dc6929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='oItemsSodJdbcIg_ig_grid_vc_cur']</value>
      <webElementGuid>ffc1180f-34d4-4f62-9fd4-32db774a378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oItemsSodJdbcIg_ig_grid_vc']/div[2]/div[4]/table/tbody/tr/td[3]</value>
      <webElementGuid>7e5b44b1-2995-4305-ab55-4cead4bc1666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Translation Function'])[2]/following::td[3]</value>
      <webElementGuid>28432e46-f512-4981-a777-1e61a5bb4555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination Column Name'])[2]/following::td[3]</value>
      <webElementGuid>9e75ddeb-c270-46ae-a86c-16faca6d85de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER_ORIG_ID'])[1]/preceding::td[1]</value>
      <webElementGuid>f62c38fd-9e77-4e1a-ac17-0ade2e4a8bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orig ID'])[1]/preceding::td[2]</value>
      <webElementGuid>49b67411-15cb-4098-9e34-4868d9f33c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPS.XXSP_USER_EBSAPPL_V']/parent::*</value>
      <webElementGuid>c3f0f53c-ee0b-468f-9669-b039e3bf8fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>92808194-b651-4bbe-b821-219ac05dce75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
