<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Seq</name>
   <tag></tag>
   <elementGuidId>dfcf8995-390c-44e9-b847-7e4aef947587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Seq' or . = 'Seq')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#C146571971917766617_HDR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b66a4645-66d3-4c1c-afe0-dc38a2d2133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-headerLabel</value>
      <webElementGuid>e71dded4-95dc-4eaf-a83a-ae8d19f986e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C146571971917766617_HDR</value>
      <webElementGuid>9880cb8c-20a2-483b-ac31-cf3f2ea32e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seq</value>
      <webElementGuid>df4cf013-edd7-426f-a102-cde8d4bcc9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C146571971917766617_HDR&quot;)</value>
      <webElementGuid>270d26b9-f340-4ec4-a493-7bc13181f8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Seq' or . = 'Seq')]</value>
      <webElementGuid>b302184d-2251-45ae-8729-3c88edcb8722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='C146571971917766617_HDR']</value>
      <webElementGuid>0a44a8a7-dc49-4d06-b580-e4b0a345f3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='oItemsSodIg_ig_grid_vc_cur']/span</value>
      <webElementGuid>b47913af-ab82-4b0b-bc69-167d930c42ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row header'])[1]/following::span[4]</value>
      <webElementGuid>030dc510-d77e-40ba-a6fa-0ff6e1bc150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interactive Grid. Report: Primary Report, View: Grid.'])[1]/following::span[5]</value>
      <webElementGuid>d7bc9826-16f9-4b62-8ced-1d07b787a36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sorted Ascending'])[1]/preceding::span[2]</value>
      <webElementGuid>339a2918-316f-4486-805e-dda7166451ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object Item Name'])[1]/preceding::span[6]</value>
      <webElementGuid>894b630a-0d82-4347-a877-896cc760b1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seq']/parent::*</value>
      <webElementGuid>9ef7eb26-3887-4138-a08a-61a248848f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span</value>
      <webElementGuid>8995e67d-d685-4b6b-a190-a6fb08d210fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
