<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Please select one -EBizApp_JDBC_En_9dc3ed</name>
   <tag></tag>
   <elementGuidId>12b8744b-bd37-485a-8ab0-0a174ffb95f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P37_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name = 'P37_ENVIRONMENT' and (text() = '- Please select one -
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
TEST_DEV1_ENV
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
' or . = '- Please select one -
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
TEST_DEV1_ENV
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Environment (Value Required)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d040e0b-04cb-4664-b9d4-58d73f2a7940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P37_ENVIRONMENT</value>
      <webElementGuid>c9dde039-b099-457c-916c-a69b5f2ffb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P37_ENVIRONMENT</value>
      <webElementGuid>33009130-5816-4363-a97d-c65427f3ae9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>1aa9d8d7-8ed2-4e56-af88-6396d8dfce28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b481dd9-a4d8-4bc2-929c-aaa543bd6026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f1a40c79-d454-4283-b1ac-590abbf6fbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Please select one -
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
TEST_DEV1_ENV
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
</value>
      <webElementGuid>cb0474a2-953b-4fa7-b323-b5ece3071b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P37_ENVIRONMENT&quot;)</value>
      <webElementGuid>de9419c2-5374-4588-b2ee-a1ddef69427c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'P37_ENVIRONMENT' and (text() = '- Please select one -
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
TEST_DEV1_ENV
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
' or . = '- Please select one -
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
McD_GRM_ENV
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
TEST_DEV1_ENV
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDay_Env
')]</value>
      <webElementGuid>eb77d1c1-81e1-4f94-9e2c-a72d936eff55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P37_ENVIRONMENT']</value>
      <webElementGuid>def79eb0-dc34-4c01-9992-d9210d999d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P37_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>d90a1b9d-bad7-4a4e-8eec-79c1ffa27ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[3]/following::select[1]</value>
      <webElementGuid>a070c75f-aa7b-463d-9bfd-d3a52bec24cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright 2017, SafePaaS, Inc. All rights reserved.'])[1]/preceding::select[1]</value>
      <webElementGuid>d7c38b6a-acaf-4655-8cab-aed1310982a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Screen Reader Mode On'])[1]/preceding::select[1]</value>
      <webElementGuid>495c9c5f-bde2-4197-b2a4-c7defadcc7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/select</value>
      <webElementGuid>ee14b406-7e6d-4a64-af01-9e871ecbb4cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
