<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cross Environments_P30_CROSS_ENVIRON_e9d7db</name>
   <tag></tag>
   <elementGuidId>26cdd30b-6b2c-464d-afa0-3182a9a54ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P30_CROSS_ENVIRONMENTS_MOVE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P30_CROSS_ENVIRONMENTS_MOVE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=group[name=&quot;Cross Environments&quot;i] >> internal:label=&quot;Move&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4743b7ab-8a45-4652-9386-32e0b46af29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P30_CROSS_ENVIRONMENTS_MOVE</value>
      <webElementGuid>5aeb6f44-8ba2-491f-8a7a-40219e8d63a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--noLabel a-Button--withIcon a-Button--small a-Button--noUI a-Button--shuttle</value>
      <webElementGuid>a520af15-000c-4238-90e5-47d3ea22c38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3f7db33-881a-40cf-ae20-2332091b16a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>59d17071-075c-464c-a7a7-6a8244ee6a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Move</value>
      <webElementGuid>22c541bf-e668-43fd-af26-788be19e0685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P30_CROSS_ENVIRONMENTS_MOVE&quot;)</value>
      <webElementGuid>8030749f-8a97-40ad-8d89-91dcd3af195f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P30_CROSS_ENVIRONMENTS_MOVE']</value>
      <webElementGuid>3a0d5714-cfb9-4e4b-8c13-b6b1b528f711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P30_CROSS_ENVIRONMENTS']/table/tbody/tr/td[2]/button[3]</value>
      <webElementGuid>f3363f56-83d7-49a9-9ac0-13b7e3954c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Environments'])[1]/following::button[3]</value>
      <webElementGuid>2b1225b1-4c7e-409e-ace8-f88a9eee5ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule Tags'])[1]/following::button[8]</value>
      <webElementGuid>945ad910-5624-4c57-8284-a156fb91a248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exclude Mitigated Violations'])[1]/preceding::button[3]</value>
      <webElementGuid>07501987-9a0b-4b58-a0a3-4c99a48ea77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Objects'])[1]/preceding::button[3]</value>
      <webElementGuid>35bb195a-533f-4be2-ab71-5dad0607643e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/table/tbody/tr/td[2]/button[3]</value>
      <webElementGuid>98f9fee8-0226-498e-af22-8938fd20d3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'P30_CROSS_ENVIRONMENTS_MOVE' and @type = 'button' and @title = 'Move']</value>
      <webElementGuid>3adb3060-d408-413b-96e7-55e5b18b44a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
