<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments_P30_SCHEDULER_JOB_COMMENTS (9)</name>
   <tag></tag>
   <elementGuidId>26c050ee-feab-4844-8d6a-68e827dd1510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P30_SCHEDULER_JOB_COMMENTS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='P30_SCHEDULER_JOB_COMMENTS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Comments&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ae7eab82-f1f3-42d2-b027-d542cf526543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P30_SCHEDULER_JOB_COMMENTS</value>
      <webElementGuid>d55c34b0-675d-464b-b963-78bbe71b06e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0fc277d4-02bc-4b0f-851e-eded65b9b811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P30_SCHEDULER_JOB_COMMENTS</value>
      <webElementGuid>dcdfbcf2-d27e-4081-9750-86ed78f4f56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea</value>
      <webElementGuid>d538e593-a461-4490-8082-d7b832d75ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0845bbf6-7bee-4a21-a699-546242d09839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P30_SCHEDULER_JOB_COMMENTS&quot;)</value>
      <webElementGuid>61c00685-dc92-4155-813d-a105965ce532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='P30_SCHEDULER_JOB_COMMENTS']</value>
      <webElementGuid>7b2f02c8-9984-4ccd-a765-42309c2a2022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P30_SCHEDULER_JOB_COMMENTS_CONTAINER']/div[2]/div/div/textarea</value>
      <webElementGuid>e02723ca-2598-4afb-acf4-d37d1e75b078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1989aef2-771b-4225-801a-9f1368979b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'P30_SCHEDULER_JOB_COMMENTS' and @id = 'P30_SCHEDULER_JOB_COMMENTS']</value>
      <webElementGuid>15341064-2990-4958-8bd1-f9095ef0fdee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
