<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments_P30_SCHEDULER_JOB_COMMENTS (1)</name>
   <tag></tag>
   <elementGuidId>3c857d9e-4744-4d19-971f-0680ab82a745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P30_SCHEDULER_JOB_COMMENTS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='P30_SCHEDULER_JOB_COMMENTS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Comments&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>71e447c3-df28-4974-95a1-af415a9a4998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P30_SCHEDULER_JOB_COMMENTS</value>
      <webElementGuid>c79095d8-6e1b-45da-a531-4a620dcf22cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>76d1d10a-3d8a-4281-a294-02157b25e09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P30_SCHEDULER_JOB_COMMENTS</value>
      <webElementGuid>8db0819f-cecf-48a2-a6cb-fd90c13fe6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea</value>
      <webElementGuid>3e0cfca8-67d5-4144-b14f-f79fd0c809b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ec3869e-5eab-4f5f-9d47-23d36bac7081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P30_SCHEDULER_JOB_COMMENTS&quot;)</value>
      <webElementGuid>013969cb-f77c-4c98-b405-f8ea57bca6dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='P30_SCHEDULER_JOB_COMMENTS']</value>
      <webElementGuid>51a1c0f0-b7cf-47fd-b44a-bab2d8fbbd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P30_SCHEDULER_JOB_COMMENTS_CONTAINER']/div[2]/div/div/textarea</value>
      <webElementGuid>7c5c3e44-01d4-4d81-b94b-c6a08f401a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9e658012-ca80-4a85-a0bd-4a931b3f8518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'P30_SCHEDULER_JOB_COMMENTS' and @id = 'P30_SCHEDULER_JOB_COMMENTS']</value>
      <webElementGuid>0bfb13de-d8a8-4535-ba46-edc37168c160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
