<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AccountsPayable</name>
   <tag></tag>
   <elementGuidId>dda01998-3605-4a05-98ff-c1473fb81c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.popup-lov-highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupLov_1_P1_DTP_OBJECT_SET_dlg']/div[3]/div/div[3]/ul/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AccountsPayable&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35366fdf-a9b1-461d-b192-a29e84cdf6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-lov-highlight</value>
      <webElementGuid>b2a0b236-e15b-4b65-8dbf-a0ebe104307a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AccountsPayable</value>
      <webElementGuid>8a182db5-ff86-4f4b-a6bb-7b1864e263ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupLov_1_P1_DTP_OBJECT_SET_dlg&quot;)/div[@class=&quot;a-PopupLOV-results a-TMV js-no-select&quot;]/div[@class=&quot;a-TMV-body&quot;]/div[@class=&quot;a-TMV-w-scroll&quot;]/ul[@class=&quot;a-IconList&quot;]/li[@class=&quot;a-IconList-item&quot;]/span[@class=&quot;popup-lov-highlight&quot;]</value>
      <webElementGuid>7558c862-be07-4b80-b205-9751158b591c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupLov_1_P1_DTP_OBJECT_SET_dlg']/div[3]/div/div[3]/ul/li/span</value>
      <webElementGuid>669c1f85-55f6-47be-888c-03239b872da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Presented in 1 rows'])[1]/following::span[1]</value>
      <webElementGuid>a7a162a8-1389-4de4-93cb-4fab9587bfa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/following::span[4]</value>
      <webElementGuid>b2efd59f-83c8-4476-8394-8d23908ec3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/preceding::span[1]</value>
      <webElementGuid>36c0e73e-d0b8-4054-b7da-aa91633e9f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AccountsPayable']/parent::*</value>
      <webElementGuid>126f9d0c-660c-4833-be4e-12ab30721602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/span</value>
      <webElementGuid>a35f1922-39a8-4283-9fc0-511cec4106a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AccountsPayable' or . = 'AccountsPayable')]</value>
      <webElementGuid>c941d09b-f354-4d1f-b2ba-92d52997c6b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
