<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_The Configuration and Transaction has bee_ee9afa</name>
   <tag></tag>
   <elementGuidId>06e67e99-104c-47cb-9754-4897bc48febd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='163106069659422927']/tbody/tr[2]/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6b81c10-ee2c-47fb-ae99-515b56f0e811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>f?p=1000:3:3877785239171:::3:P3_NID:77418</value>
      <webElementGuid>6525ca73-e53c-442c-83d7-df889fa8ecdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Configuration and Transaction has been sent for your approval - Owner</value>
      <webElementGuid>416a7854-4cd1-4039-b54d-23fe9db0bfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;163106069659422927&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]/a[1]</value>
      <webElementGuid>4d6675cc-58d3-4636-9c16-e1067ecabcce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='163106069659422927']/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>ea3f6044-e757-4314-8fd8-1be1ef2d1aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'The Configuration and Transaction has been sent for your approval - Owner')]</value>
      <webElementGuid>19890cd6-9592-48a2-af5f-95d59a77f14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'f?p=1000:3:3877785239171:::3:P3_NID:77418')]</value>
      <webElementGuid>7ae043ba-b04f-4b3e-8100-05934650c542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>e4be746c-0110-4e00-b304-5afb756008de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'f?p=1000:3:3877785239171:::3:P3_NID:77418' and (text() = 'The Configuration and Transaction has been sent for your approval - Owner' or . = 'The Configuration and Transaction has been sent for your approval - Owner')]</value>
      <webElementGuid>244046e2-b927-4c27-a9e7-c1ce7f2f1128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
