<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Manage Roles - Able to create and upd_055ebe</name>
   <tag></tag>
   <elementGuidId>a3121eba-c2ac-45a7-9d18-f62ca0d80e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P43_FUNCTION_WRITE_ACCESS']/div[5]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ce2ad256-a01f-4b5d-8ebc-7aabf23f2ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-checkbox</value>
      <webElementGuid>862cec68-c0b3-4be4-8cc6-1c519f64cbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P43_FUNCTION_WRITE_ACCESS_4</value>
      <webElementGuid>e412578d-f5f4-4526-a476-c346300a8e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Roles - Able to create and update Roles</value>
      <webElementGuid>de2d836a-b331-4ec7-aca4-dcb357faf982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P43_FUNCTION_WRITE_ACCESS&quot;)/div[@class=&quot;apex-item-option&quot;]/label[@class=&quot;u-checkbox&quot;]</value>
      <webElementGuid>e1d9793a-ec20-4792-862e-b0906c078b2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P43_FUNCTION_WRITE_ACCESS']/div[5]/label</value>
      <webElementGuid>3f7f329e-804b-4f82-8829-c0a749a26423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Object Set - Able to create and update Object Set'])[1]/following::label[1]</value>
      <webElementGuid>7494cc3a-ec8c-439a-9176-efbe079f863b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Object - Able to create and update Object'])[1]/following::label[2]</value>
      <webElementGuid>888b7957-3be7-4ec4-8e15-13f05078c853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Roles - Able to assign Roles to User'])[1]/preceding::label[1]</value>
      <webElementGuid>bac9ec49-8977-4acb-bfa4-04832975d261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright 2017, SafePaaS, Inc. All rights reserved.'])[1]/preceding::label[2]</value>
      <webElementGuid>a618be1e-dfb1-4eaf-ad16-72ccb3931d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Roles - Able to create and update Roles']/parent::*</value>
      <webElementGuid>8fbd81b1-eee6-4abd-8860-8526f1c90eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/div/div/div[5]/label</value>
      <webElementGuid>7066f906-9a99-42ce-aa2f-6d13a44fd8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Manage Roles - Able to create and update Roles' or . = 'Manage Roles - Able to create and update Roles')]</value>
      <webElementGuid>00182388-8b72-46a0-b838-d0c44ea7c3de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
