<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_All</name>
   <tag></tag>
   <elementGuidId>152fe6bd-0661-4508-913d-a68d9d9f7c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='All']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;All&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>47dc10b3-cca0-48ca-98d7-85843f978645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>3e3ed5c6-b699-4ab6-b02f-6f3a52c413df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>f4cee036-f6bf-4174-9bb9-de194e9937bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P35_RULE_TAGS_LEFT&quot;)/option[2]</value>
      <webElementGuid>a80327b6-9d3b-4547-b4ac-8e8994940350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='All']</value>
      <webElementGuid>b1499d02-ddd0-4d1d-9639-2b928b87d2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='P35_RULE_TAGS_LEFT']/option[2]</value>
      <webElementGuid>89987984-0631-4932-8176-33e5d9a03973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule Tags'])[1]/following::option[2]</value>
      <webElementGuid>d399c00a-8e88-42da-ae39-fce372cf4691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Type :'])[1]/following::option[6]</value>
      <webElementGuid>77ce3e8d-8b21-4bdd-b907-a63530bf378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright 2017, SafePaaS, Inc. All rights reserved.'])[1]/preceding::option[4]</value>
      <webElementGuid>5a3d5b85-a08d-4f87-a059-040dacc834af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release 2.0'])[1]/preceding::option[4]</value>
      <webElementGuid>f743e7d6-7bf6-4d94-b5e5-9a3d799724c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>5137a427-7201-4069-8050-7158476f9fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/select/option[2]</value>
      <webElementGuid>0cfc353e-d10d-4a4a-8a8c-289f405fa65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'All' or . = 'All')]</value>
      <webElementGuid>b21e7165-8337-4b69-b049-c2712a9d4e26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
