<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select any oneCoupa_Env1EBizApp_JDBC_98ef84</name>
   <tag></tag>
   <elementGuidId>68177a7e-a020-48cf-95ee-d9c3cbb69e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P74_ENVIRONMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P74_ENVIRONMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Environment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>00ddbc17-f8a5-49e8-9a25-5e5aae0754bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P74_ENVIRONMENT</value>
      <webElementGuid>a6338ab9-09bb-4fa9-93dc-a04fc2189c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P74_ENVIRONMENT</value>
      <webElementGuid>2703e88c-234e-482e-9da2-58d7c8832766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>a3532e84-c112-485b-af04-f686b7a00f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d2c7e41-b7dc-486b-8d25-c5436858551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e98a6bae-3da3-4ad4-9fce-b2f6b8523287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBizApp_New
EBiz_SFTP
OS_IDM_Copy
SAP_S4HANA
SFTP_Env2
Test_Environment3_Hybris
WorkDayEnv_1
Y_DEV_OS_ENV_Copy
Y_Endur
Z_AutoKAT
Z_Azure
Z_EBS_XRef1
Z_Hybris_Env
</value>
      <webElementGuid>468a4fe8-4c9a-4001-a4f5-94a78e142f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P74_ENVIRONMENT&quot;)</value>
      <webElementGuid>16dd674f-55a6-4333-9272-db2765fb559e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P74_ENVIRONMENT']</value>
      <webElementGuid>2ed9f73d-1e28-4930-b708-9f5bd60d85b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P74_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>bde7cdae-fc13-48b2-97fb-a71d6c03c5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>168a9104-9af8-446a-8e9d-4d56afbc0f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Name'])[1]/following::select[1]</value>
      <webElementGuid>657f2ea4-20b5-4937-86c5-ff3fa71e5191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Name'])[1]/preceding::select[1]</value>
      <webElementGuid>cc5d2daa-b03b-48cd-a01e-eb15c149f742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Violation'])[4]/preceding::select[1]</value>
      <webElementGuid>f978d044-d37c-48c2-9f02-bd043bd90943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9b8c634f-08ed-4775-b73f-f4d7c1a35292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P74_ENVIRONMENT' and @name = 'P74_ENVIRONMENT' and (text() = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBizApp_New
EBiz_SFTP
OS_IDM_Copy
SAP_S4HANA
SFTP_Env2
Test_Environment3_Hybris
WorkDayEnv_1
Y_DEV_OS_ENV_Copy
Y_Endur
Z_AutoKAT
Z_Azure
Z_EBS_XRef1
Z_Hybris_Env
' or . = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBizApp_New
EBiz_SFTP
OS_IDM_Copy
SAP_S4HANA
SFTP_Env2
Test_Environment3_Hybris
WorkDayEnv_1
Y_DEV_OS_ENV_Copy
Y_Endur
Z_AutoKAT
Z_Azure
Z_EBS_XRef1
Z_Hybris_Env
')]</value>
      <webElementGuid>7ca1ea6e-f529-44c5-b519-5ff2d3bc50b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
