<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Path (Value Required)</name>
   <tag></tag>
   <elementGuidId>88631add-01df-4173-aac5-32cd206ca5d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Path (Value Required)' or . = 'Path (Value Required)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P10_PATH_LABEL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7ebda777-e6bc-4976-a9ba-c5779298c255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P10_PATH</value>
      <webElementGuid>70080e6b-0a34-4735-ba75-098a68a4e724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_PATH_LABEL</value>
      <webElementGuid>e151ffdc-f88b-4354-bac8-77220cb99d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>241f0fc8-639d-4fbb-abf8-1d4d58a5a800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Path (Value Required)</value>
      <webElementGuid>0eb27bba-20d8-4552-8a45-3c0aa897d1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_PATH_LABEL&quot;)</value>
      <webElementGuid>b12fbbc7-6802-4dc8-bc1f-662bcc436c86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Path (Value Required)' or . = 'Path (Value Required)')]</value>
      <webElementGuid>62c00850-e019-4bb0-b28c-2c183ab0f1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P10_PATH_LABEL']</value>
      <webElementGuid>02a1cdca-5848-4760-b000-2aa1fdda2340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_PATH_CONTAINER']/div/label</value>
      <webElementGuid>5d2453b8-dd04-405c-9ec0-a30228c8c6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source File'])[1]/following::label[1]</value>
      <webElementGuid>ecf2ac4c-9587-4113-9a33-13e7448ea90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object Join Condition'])[2]/following::label[1]</value>
      <webElementGuid>331f3456-bf25-485b-b382-64dc73b4c051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='release 1.0'])[1]/preceding::label[1]</value>
      <webElementGuid>b76ca33e-fa7e-41a1-908f-2c9582a8132b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Path']/parent::*</value>
      <webElementGuid>c567c85a-3fcc-4cd6-a0ef-1f8fa07c9cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/div[2]/div/div/div/div/div/label</value>
      <webElementGuid>66d84c9b-a719-47f1-9556-4753830c8790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
