<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Excluded Mitigated Violations_a-TreeVi_6be8a6</name>
   <tag></tag>
   <elementGuidId>5ac99a5b-6eed-4c66-8833-ad74c777f376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_129 > span.a-TreeView-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_129']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#t_TreeNav_129 span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8467b80e-5d31-4cec-9f2c-ffbd9271b3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>0cca31dd-60f0-4222-975a-391570b5cc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_129&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>a9f508b4-71a3-4330-9b1d-9bc6cd930e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_129']/span</value>
      <webElementGuid>9e503803-0449-4b91-99a7-0f3f25cb10f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/ul/li[2]/span</value>
      <webElementGuid>90685b16-b882-4f6c-ae88-b39e9c1d765f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
