<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_User NameStart EntryStart Entry Name_0786d6 - 42</name>
   <tag></tag>
   <elementGuidId>03fa7c9e-2f52-461f-b262-46355e2b10be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uacReport_column_name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uacReport_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'User NameStart EntryStart Entry NameRule NameRule TypeRule Activity GroupActivityViolation EntryViolation Entry NameViolation Entry DescriptionViolation Path DescriptionViolation StatusException NameException Type CodeException StatusException ScopeRemediation Status of Role Owner VerifiedVerified On (Role Owner)Verified By (Role Owner)Justification of Role OwnerRemediation Status of Rule OwnerVerified By (Rule Owner)Verified On (Rule Owner)Justification of Rule OwnerRole GroupParent Entry Id' or . = 'User NameStart EntryStart Entry NameRule NameRule TypeRule Activity GroupActivityViolation EntryViolation Entry NameViolation Entry DescriptionViolation Path DescriptionViolation StatusException NameException Type CodeException StatusException ScopeRemediation Status of Role Owner VerifiedVerified On (Role Owner)Verified By (Role Owner)Justification of Role OwnerRemediation Status of Rule OwnerVerified By (Rule Owner)Verified On (Rule Owner)Justification of Rule OwnerRole GroupParent Entry Id')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[9]/div[2]/div/div[3]/div[1]/div/div[1]/div/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9bbdd84-51a9-4dc4-9197-08e420acfd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uacReport_column_name</value>
      <webElementGuid>c9b07700-20ba-4119-be3b-3ea848ee76f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Column</value>
      <webElementGuid>9c99cec6-54cb-4a0c-abc1-c65df5b63d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>4ea03f06-0098-4bba-a527-793b00b8b3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ea5e2516-0774-47e6-b1fb-0e7ddb332e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select</value>
      <webElementGuid>71964b5d-6f27-487c-9614-7726f3e827b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User NameStart EntryStart Entry NameRule NameRule TypeRule Activity GroupActivityViolation EntryViolation Entry NameViolation Entry DescriptionViolation Path DescriptionViolation StatusException NameException Type CodeException StatusException ScopeRemediation Status of Role Owner VerifiedVerified On (Role Owner)Verified By (Role Owner)Justification of Role OwnerRemediation Status of Rule OwnerVerified By (Rule Owner)Verified On (Rule Owner)Justification of Rule OwnerRole GroupParent Entry Id</value>
      <webElementGuid>b9744647-4c4c-44da-a619-95e7b0c77fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uacReport_column_name&quot;)</value>
      <webElementGuid>c53fdd4f-1f51-4aa4-95fe-41075d73f138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='uacReport_column_name']</value>
      <webElementGuid>3bec120d-d5b3-46b8-b33d-997fd0a146d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uacReport_column_filter']/div/div/div/div[2]/select</value>
      <webElementGuid>b4929758-1e6b-485d-8cc3-2ab5514cd213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>aec99223-c87e-4774-96df-8ecaef3705e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'uacReport_column_name' and @title = 'Column' and @name = 'p_ignore_10' and (text() = 'User NameStart EntryStart Entry NameRule NameRule TypeRule Activity GroupActivityViolation EntryViolation Entry NameViolation Entry DescriptionViolation Path DescriptionViolation StatusException NameException Type CodeException StatusException ScopeRemediation Status of Role Owner VerifiedVerified On (Role Owner)Verified By (Role Owner)Justification of Role OwnerRemediation Status of Rule OwnerVerified By (Rule Owner)Verified On (Rule Owner)Justification of Rule OwnerRole GroupParent Entry Id' or . = 'User NameStart EntryStart Entry NameRule NameRule TypeRule Activity GroupActivityViolation EntryViolation Entry NameViolation Entry DescriptionViolation Path DescriptionViolation StatusException NameException Type CodeException StatusException ScopeRemediation Status of Role Owner VerifiedVerified On (Role Owner)Verified By (Role Owner)Justification of Role OwnerRemediation Status of Rule OwnerVerified By (Rule Owner)Verified On (Rule Owner)Justification of Rule OwnerRole GroupParent Entry Id')]</value>
      <webElementGuid>ed3b482f-059d-4775-9784-57d7fc0fe02e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
