<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_is nullis not nulllikenot likeinnot _ 43</name>
   <tag></tag>
   <elementGuidId>10f82d80-16b3-40d6-b0c5-6621a80b45b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uacReport_STRING_OPT</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uacReport_STRING_OPT' and @name = 'p_ignore_10' and (text() = '=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression' or . = '=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[9]/div[2]/div/div[3]/div[1]/div/div[2]/div[1]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fed29c50-8f3c-472f-a49f-ddd3b974db45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uacReport_STRING_OPT</value>
      <webElementGuid>612861a9-95e3-4ef7-9a95-5cc261142de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-select a-IRR-operator</value>
      <webElementGuid>df0d1d74-b752-4a1d-987d-c1b045b245d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-type</name>
      <type>Main</type>
      <value>STRING</value>
      <webElementGuid>335f938f-eb65-4e18-a8e0-e4c542e25d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p_ignore_10</value>
      <webElementGuid>dd05b45c-7a8b-427b-b950-1683447acdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c125477a-5230-4d3c-8e9b-4655aae52407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression</value>
      <webElementGuid>1edc0083-909d-48de-816a-07b1a47abc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uacReport_STRING_OPT&quot;)</value>
      <webElementGuid>9c5c72f9-5ab1-4d10-b535-830c2704db50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='uacReport_STRING_OPT']</value>
      <webElementGuid>e3081a2a-2396-41b8-95df-869ff8db7daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uacReport_column_filter']/div/div[2]/div/div[2]/select</value>
      <webElementGuid>394b496d-0f66-45cc-b1d0-17b39333531f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/select</value>
      <webElementGuid>4bd16f6e-95c2-4c49-9edb-2a9d6eb665a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'uacReport_STRING_OPT' and @name = 'p_ignore_10' and (text() = '=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression' or . = '=!=is nullis not nulllikenot likeinnot incontainsdoes not containmatches regular expression')]</value>
      <webElementGuid>bd4c5942-3284-4fc1-bc57-f44abeeb9ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
