<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P4_DS_HOSTNAME</name>
   <tag></tag>
   <elementGuidId>c413abf2-c2a2-48bc-a8a4-b880fd04193e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P4_DS_HOSTNAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P4_DS_HOSTNAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a62c76e-c1cd-4e71-a1a3-c2c76c73f6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d048e9df-891c-4190-8eae-3d73f4f8dadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P4_DS_HOSTNAME</value>
      <webElementGuid>29799a37-2b8f-4a31-ab77-aa6f905aebeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P4_DS_HOSTNAME</value>
      <webElementGuid>eaf7ff04-e3ae-4e54-ae50-043759f773d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>de57c086-2f03-45ff-b39b-83f073963f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://fa-emzk-dev22-saasfaprod1.fa.ocs.oraclecloud.com</value>
      <webElementGuid>828fa4d2-9398-4705-87f6-d8225f52b337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>1cca4f7c-7651-4b44-be4c-1b1c754ba801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>48680f69-4498-4ef8-ae6f-231729f62a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P4_DS_HOSTNAME&quot;)</value>
      <webElementGuid>eb6373a4-8a63-446c-b6a4-11b739021e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P4_DS_HOSTNAME']</value>
      <webElementGuid>92f8186a-53e3-4706-8f49-4bce46e593c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P4_DS_HOSTNAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>c00a5c50-0373-4d80-b078-5cf71bd791c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/input</value>
      <webElementGuid>dd8baeb1-846e-4264-8648-b5748ca71a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P4_DS_HOSTNAME' and @name = 'P4_DS_HOSTNAME']</value>
      <webElementGuid>6dc15c78-0c15-4a86-b166-feb671e0620b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
