<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_FSOD.FSOD_ENTRY_ALL</name>
   <tag></tag>
   <elementGuidId>2de53419-bea4-4654-8e55-448b0f0258b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oItemsSodIg_ig_grid_vc_cur</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'FSOD.FSOD_ENTRY_ALL' or . = 'FSOD.FSOD_ENTRY_ALL')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a1ddc468-c514-4114-ac1c-05cb4eb9cc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>0048a2ca-a0d8-4ea5-b1a5-1c92989beb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d6f091d-3450-46bf-9a98-102670277f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-focused</value>
      <webElementGuid>b6940ddc-2ba6-4d34-88f6-bd744e6b0263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>oItemsSodIg_ig_grid_vc_ctx oItemsSodIg_ig_grid_vc_cur</value>
      <webElementGuid>54fb8d98-f833-402d-8302-0e6f2798ca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oItemsSodIg_ig_grid_vc_cur</value>
      <webElementGuid>d8bfe056-c06e-4d61-8d82-8d477cf89958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FSOD.FSOD_ENTRY_ALL</value>
      <webElementGuid>d4627a33-6181-406a-918a-d5fdab92d3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oItemsSodIg_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>da16fb93-2ada-4b69-9f5a-7e9d7b3745f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'FSOD.FSOD_ENTRY_ALL' or . = 'FSOD.FSOD_ENTRY_ALL')]</value>
      <webElementGuid>1e8ad2c1-5bb7-4ebd-92b8-65c16c544e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='oItemsSodIg_ig_grid_vc_cur']</value>
      <webElementGuid>850e68fe-c57e-4da6-b539-a4661605f915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oItemsSodIg_ig_grid_vc']/div[2]/div[4]/table/tbody/tr/td[5]</value>
      <webElementGuid>c62ce864-eb85-41f7-9268-b98b2d933ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA_DS:G_1:CODE'])[1]/following::td[1]</value>
      <webElementGuid>bc7a53ed-d6e8-4441-9f47-1a27669dce15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::td[2]</value>
      <webElementGuid>0bcc6539-01e4-4a77-a5de-96f67ff5eee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAME'])[1]/preceding::td[1]</value>
      <webElementGuid>b8b04775-e082-451b-ad40-8867ea0c651f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VARCHAR2'])[1]/preceding::td[2]</value>
      <webElementGuid>c30634c8-37ca-4ca2-93b3-5a675b7c73fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FSOD.FSOD_ENTRY_ALL']/parent::*</value>
      <webElementGuid>985da8d9-4d29-4649-83b1-18ba142385dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>1688b6f8-9381-4260-88b7-6a6de35b7f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
