<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Actions</name>
   <tag></tag>
   <elementGuidId>336945b6-e883-42f3-a142-059024afa4cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#97390712237089040 > tr > #actionsCol > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[(text() = 'Actions' or . = 'Actions')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2dad665c-d313-4965-a040-12ae7aa9f221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>b081c51f-6cf2-49e3-bae0-edd636f04328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>97421978931260306</value>
      <webElementGuid>6feb72a5-4c08-4fd7-bd29-3a8a8e6dab74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1adbe38f-cd35-421e-b754-74a79793212a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>e180a1d7-3c02-4efe-859a-abdbcb9e089f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;97390712237089040&quot;)/tr[1]/th[@id=&quot;actionsCol&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>36dbc6c9-a178-4507-a440-a1d66cf8df53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//th[@id='actionsCol']/a)[3]</value>
      <webElementGuid>aad1cdc4-7810-4ee1-8a12-cfff0b148f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Actions')])[6]</value>
      <webElementGuid>7f670d8c-7779-4c0a-974c-13276c092bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/table/tr/th[2]/a</value>
      <webElementGuid>f52db538-68be-4d8b-95e6-2f81fef7e4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>8bfdd02c-dd5b-4399-bb46-8def8e1cc049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
