<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter (1)</name>
   <tag></tag>
   <elementGuidId>6c872c2e-e6e2-4cb0-8f34-f1fd9aa51468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wfReport_actions_menu_2i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='wfReport_actions_menu_2i']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71a541a8-76ca-4437-884e-b1ecf0888721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14488b6b-65c1-42e7-bffa-b53283ee7fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wfReport_actions_menu_2i</value>
      <webElementGuid>069ed421-1405-48d4-baeb-fa00d1ee778e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>ba3b6f2b-745c-4ca4-812a-388b72cf690e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>2da4dfa9-5105-4636-a92d-d0d4ce8184b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>3b83f776-8413-4bbe-a29a-12c38ec6c105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wfReport_actions_menu_2i&quot;)</value>
      <webElementGuid>7eca88e1-c2f1-472d-99d4-43fb7104d47b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='wfReport_actions_menu_2i']</value>
      <webElementGuid>0bdc0c68-48a9-4430-810f-6ed2d43d87b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wfReport_actions_menu_2']/div/span/button</value>
      <webElementGuid>c5329d54-a9e3-4917-8303-c72975b8621c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/button</value>
      <webElementGuid>595a6005-7b24-4932-87b3-6e6827d44298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'wfReport_actions_menu_2i' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>fe8ff474-0040-4dc1-81c5-37ce5aa5bd55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
