<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go</name>
   <tag></tag>
   <elementGuidId>c902e23e-453c-4d6e-a23e-79cbed86a21d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#R247793226539899118_search_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='R247793226539899118_search_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15ad47fb-d11d-45de-87ac-4e9806010be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R247793226539899118_search_button</value>
      <webElementGuid>bb92c564-bf77-4f1c-a50c-31d2dce0f50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-IRR-button--search</value>
      <webElementGuid>6636059b-d08d-4073-9dfb-50ddae997139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dab367ea-e57c-487e-9d44-edb5fbb1091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>d2a784ce-1788-44e6-b03a-76194b2daf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R247793226539899118_search_button&quot;)</value>
      <webElementGuid>83605a20-56af-492a-8180-8200454a641a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='R247793226539899118_search_button']</value>
      <webElementGuid>e8617771-75dc-4812-9d12-1e24fb757205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R247793226539899118_toolbar_controls']/div/div/div[3]/button</value>
      <webElementGuid>44a082e1-8b80-469e-a364-96c8f5ee3a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Rules'])[1]/following::button[2]</value>
      <webElementGuid>7dd2c0f7-e232-4850-b89b-97fdac283b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Rules'])[1]/following::button[3]</value>
      <webElementGuid>b1e56fbd-02f7-469b-8a96-1af4f1a5a4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::button[1]</value>
      <webElementGuid>1da0f355-05b2-4d44-9069-def170d3218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>21725a84-540d-417b-b9f8-10da242ddbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'R247793226539899118_search_button' and @type = 'button' and (text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>f1607dc4-e437-42ea-ad36-0f5e2ae06d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
