<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Environment</name>
   <tag></tag>
   <elementGuidId>452b2579-f0d4-4351-9bae-c47ac4dde287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='P0_ENVIRONMENT_LABEL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7fb8139e-af77-4551-8798-66c264b36436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>2f8b9c55-56a3-4e74-8c16-e68c34d5d321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT_LABEL</value>
      <webElementGuid>fad96c96-993a-45a1-a242-190c800f0793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>a5e33f0e-8708-4724-a106-30352aec9632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Environment</value>
      <webElementGuid>e786bb16-42e0-4d3b-9596-016f86bbfc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT_LABEL&quot;)</value>
      <webElementGuid>c8ea6afc-f7d0-4ecb-82ec-2a958039303a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P0_ENVIRONMENT_LABEL']</value>
      <webElementGuid>7dd1928a-adce-4e41-95b5-49eafe0f8170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div/label</value>
      <webElementGuid>28395b10-0d39-4ed8-87e4-b1b26c926e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::label[1]</value>
      <webElementGuid>c7e8250c-dfb5-455c-9a4e-2ad701b50fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Rules'])[3]/following::label[1]</value>
      <webElementGuid>854f9966-b936-4c6b-87d9-f4636c32f386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Rules'])[4]/preceding::label[1]</value>
      <webElementGuid>f7290f3a-1f4a-4fdb-b9ae-6df8dc3667ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Rule'])[1]/preceding::label[1]</value>
      <webElementGuid>3d0fb79e-5466-463b-9f39-0a8761a938f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Environment']/parent::*</value>
      <webElementGuid>31538f7a-d5fa-4075-aacd-c4d53d3aee68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>4121f959-969e-4bc5-a14c-3021fa07e230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'P0_ENVIRONMENT_LABEL' and (text() = 'Environment' or . = 'Environment')]</value>
      <webElementGuid>21c2d086-adf1-42c5-ace2-55fb7934e92e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
