<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_concat(Role Group  , , RoleGroup_Oth_201781</name>
   <tag></tag>
   <elementGuidId>23d84403-6cef-4df1-b064-57a6b7bd7d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.a-Button.a-IRR-button.a-Button--noUI.a-IRR-button--remove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@title = 'Remove Filter' and @type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e312af80-6f16-40eb-b8e9-414d607e3810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-IRR-button a-Button--noUI a-IRR-button--remove</value>
      <webElementGuid>42ba1202-94b4-49fb-98e3-450f40e000da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove Filter</value>
      <webElementGuid>b8572ee7-cd47-4226-94fa-a1db8f5eec96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove Filter</value>
      <webElementGuid>67d6b2b1-8604-4fff-a5ae-c6896972669f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ab113e5e-ec38-4d63-9b84-f48fc3080bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-setting</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>20624a59-68ba-43b6-89ac-10ee73f0a93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filter-id</name>
      <type>Main</type>
      <value>372284446593233452</value>
      <webElementGuid>770eb8be-7dee-481c-9e77-3ccec3a87a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a_Collapsible1_R485447514490922889_control_panel_content&quot;)/ul[@class=&quot;a-IRR-controls&quot;]/li[@class=&quot;a-IRR-controls-item a-IRR-controls-item--filter&quot;]/span[@class=&quot;a-IRR-controls-cell a-IRR-controls-cell--remove&quot;]/button[@class=&quot;a-Button a-IRR-button a-Button--noUI a-IRR-button--remove&quot;]</value>
      <webElementGuid>8ebd4514-fb23-4cdd-b71f-e189fb6467ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Remove Filter' and @type = 'button']</value>
      <webElementGuid>1be10b1a-f43d-4221-b527-74c845b3eb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[44]</value>
      <webElementGuid>db0c8716-723d-4a21-bcb6-102ac7f59368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Role Group = ', &quot;'&quot;, 'RoleGroup_Other', &quot;'&quot;, '')])[1]/following::button[1]</value>
      <webElementGuid>d29f427e-792e-4622-a8fc-6db18243fe94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[3]/following::button[1]</value>
      <webElementGuid>69e06904-7373-4f26-8b6b-d11b8735e107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle'])[2]/preceding::button[1]</value>
      <webElementGuid>a4b55dd5-9854-45d3-ae2b-d671cd38158d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[4]/preceding::button[1]</value>
      <webElementGuid>159d70e8-d8cf-42c4-adb6-66f2a38348a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/button</value>
      <webElementGuid>3102294e-cad7-4a3c-9ce2-59b0f0c24b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a_Collapsible1_R485447514490922889_control_panel_content']/ul/li/span[4]/button</value>
      <webElementGuid>e0313f5b-0ad5-4b89-bee8-43f42859e46c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
