<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_End date_grid_ig_grid_vc_cur</name>
   <tag></tag>
   <elementGuidId>c1290233-db7b-4813-ac21-7265a00f3baa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='grid_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grid_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Row 1, Column 1.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a070247d-e1fa-4dc4-be15-5a37859b110d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>107d424e-c86a-488c-9ac0-16b2513f480c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ee21df3-0fb7-4f6b-b3a4-22ed96b07155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tC is-readonly is-focused</value>
      <webElementGuid>e8bc8f21-698f-415d-8995-006f4ef7f073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>QAAutomation_CreateUser - QAAutomation CreateUser</value>
      <webElementGuid>853a8729-36b5-46bf-84aa-4f9f8fa018dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>grid_ig_grid_vc_ctx grid_ig_grid_vc_cur</value>
      <webElementGuid>140e735e-628b-4f08-848e-dc2c7b72a91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid_ig_grid_vc_cur</value>
      <webElementGuid>c3be20dc-82d8-49db-b073-a124036e5e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QAAutomation_CreateUser - QAAutomation CreateUser</value>
      <webElementGuid>5d340cd7-7c03-4bfc-a977-104845cba66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>7e971665-5ce9-4273-890c-8240dce73546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='grid_ig_grid_vc_cur']</value>
      <webElementGuid>b9fea9f9-b704-4f3f-bacf-7eaa8c68e5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid_ig_grid_vc']/div[3]/div[4]/table/tbody/tr/td</value>
      <webElementGuid>9259d282-a866-4eb2-9f5f-d9972f96eb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[2]/following::td[1]</value>
      <webElementGuid>efd6f3cb-96c5-4e69-98d3-84c0103f2524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date'])[2]/following::td[1]</value>
      <webElementGuid>c3282055-9671-4d35-8194-79ff75528170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QAAutomation CreateUser'])[1]/preceding::td[1]</value>
      <webElementGuid>f48bda3a-8030-4aa1-bae6-2fb557c66b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GL_RUSSIA_TAX'])[1]/preceding::td[2]</value>
      <webElementGuid>7ee8387a-ff33-48cd-8a51-29763ef13fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QAAutomation_CreateUser - QAAutomation CreateUser']/parent::*</value>
      <webElementGuid>c17f32d3-7ab0-46e3-8723-6e7120c85fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>9e3889cc-c84e-4632-8807-6ad2ae3b9e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'QAAutomation_CreateUser - QAAutomation CreateUser' and @id = 'grid_ig_grid_vc_cur' and (text() = 'QAAutomation_CreateUser - QAAutomation CreateUser' or . = 'QAAutomation_CreateUser - QAAutomation CreateUser')]</value>
      <webElementGuid>bc4b7de8-93fb-49fd-894e-7d8c5603b9cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
