<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PERMISSION_apex-edit-view</name>
   <tag></tag>
   <elementGuidId>232cd338-28fe-4407-b9ca-d3a49afdf62b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.apex-edit-view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='172136552679540725_orig']/tbody/tr[2]/td[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;View AP Reports PERMISSION 29-MAY-25 KATADMIN 29-MAY-25 KATADMIN&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ded8b7b3-2c05-47f7-8fbe-8f5bc4b4a432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/i/app_ui/img/icons/apex-edit-view.png</value>
      <webElementGuid>03819019-473e-4d30-a4e3-7fb081844886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-edit-view</value>
      <webElementGuid>1cc75d80-6836-4de2-8ec4-71ff6900ba87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;172136552679540725_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tC&quot;]/a[1]/img[@class=&quot;apex-edit-view&quot;]</value>
      <webElementGuid>4304cab1-06a2-4400-bbcb-78dbce623eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/i/app_ui/img/icons/apex-edit-view.png']</value>
      <webElementGuid>e47c581c-3c34-491f-a133-6f898925e9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='172136552679540725_orig']/tbody/tr[2]/td[4]/a/img</value>
      <webElementGuid>2f0fde8b-14dd-49ea-b85d-01c66829278f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>bc08d0f8-4c3b-4af2-a76e-4069921d05e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
