<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Description (1)</name>
   <tag></tag>
   <elementGuidId>fe703126-14a6-4aeb-a699-b5e8a2aabb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C170162459981012359 > a.a-IRR-headerLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='C170162459981012359']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e7948c8-63a2-43aa-b3ad-7a8070cbec55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IRR-headerLink</value>
      <webElementGuid>a78087d6-c1f5-4325-a881-4e053f80537f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>170162459981012359</value>
      <webElementGuid>f0df3f3b-6f61-4eff-a993-d5e07338d0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fht-column-idx</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e30ca590-b06a-451a-aac2-e8acb0b26c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>070cfef7-c8e9-4b4f-a1e8-0e8245d2d770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;327963199889660485&quot;)/tr[1]/th[@id=&quot;C170162459981012359&quot;]/a[@class=&quot;a-IRR-headerLink&quot;]</value>
      <webElementGuid>88a24b84-0827-47a8-9633-e24d7467bc38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='C170162459981012359']/a</value>
      <webElementGuid>8945ef0a-98c5-4815-9b40-9a567c5c9e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Description')]</value>
      <webElementGuid>66dd2f2c-25b5-46de-9af9-874e43620751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/a</value>
      <webElementGuid>d392c256-c64b-4f4f-b820-8ed6cdeb6a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>44931836-02d3-4aef-8d76-8b183010104e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
