<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Object Description</name>
   <tag></tag>
   <elementGuidId>0b0c3141-aa5b-4e31-a143-f6ac9c820f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P10_OBJECT_DESCR_LABEL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Object Description' or . = 'Object Description')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>abf67356-198a-4899-8eea-2c62559cd5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P10_OBJECT_DESCR</value>
      <webElementGuid>358ef454-9b61-4184-b9c7-f88c846f402e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P10_OBJECT_DESCR_LABEL</value>
      <webElementGuid>9a7d3fd6-fbf5-475e-be2e-b2d072c1590f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-label</value>
      <webElementGuid>c79cf53c-2103-48a2-9b8c-e8b0f53dd17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Object Description</value>
      <webElementGuid>a30ba31b-1b7c-4516-9d4f-868e4e51990d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_OBJECT_DESCR_LABEL&quot;)</value>
      <webElementGuid>0f22de4b-4ffe-4db1-8084-9466faf373e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Object Description' or . = 'Object Description')]</value>
      <webElementGuid>ff27e47a-6ab5-457c-be42-6feab2e5d537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='P10_OBJECT_DESCR_LABEL']</value>
      <webElementGuid>7bdca3e8-9f68-4c87-80e7-8bbfdedff9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P10_OBJECT_DESCR_CONTAINER']/div/label</value>
      <webElementGuid>0be25f19-50af-4e1b-80c6-a98ac185a3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[1]/following::label[1]</value>
      <webElementGuid>5c6be570-20b0-49e3-999e-eaeeca543a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[2]/preceding::label[1]</value>
      <webElementGuid>7a7a4dd3-1319-4f30-a83a-1f55d1333a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Object Description']/parent::*</value>
      <webElementGuid>a07078a9-f668-4d5b-92f9-dc40268d3a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label</value>
      <webElementGuid>f24e9c0f-aa22-48ae-b620-61cbf7b8e629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
