<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Environment_P0_ENVIRONMENT</name>
   <tag></tag>
   <elementGuidId>466f0ebf-6024-4a3e-ba2c-1bc62d6ebb91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P0_ENVIRONMENT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P0_ENVIRONMENT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Environment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87d725d2-957d-46c0-af93-b15d3a0e92bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>f17de99a-78b4-420a-bc75-d75ff90b5b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P0_ENVIRONMENT</value>
      <webElementGuid>94a62e1e-1339-4ffd-9f57-e80d21d5b978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>19947161-fdf8-4808-9609-ff7a0d6d6b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84bec142-f502-4ffb-a8ba-bc1a921457dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3be80fd2-6fa1-401a-beae-39f7f6be6f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>apex.submit('P0_ENVIRONMENT');</value>
      <webElementGuid>9e207aad-041d-4ffd-b87d-44643bbc5f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
MXYZ
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
SAP_DEMO
SAP_ECC
SAP_S4HANA
ServiceCafe_Env
SFTP_Env2
SUCCESSFACTORS_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
</value>
      <webElementGuid>4892d8d7-4017-4220-bbe8-0ec1c305fd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P0_ENVIRONMENT&quot;)</value>
      <webElementGuid>97bd7082-f98f-44b8-8fbf-b6d14e75a671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P0_ENVIRONMENT']</value>
      <webElementGuid>71a23e01-8a94-410a-a985-31f7f3f65d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P0_ENVIRONMENT_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>4846d4af-3a7a-42f2-88de-fbd181b26969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Environment'])[1]/following::select[1]</value>
      <webElementGuid>8c01a0c1-5317-4cd5-be96-01968fa6bfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breadcrumb'])[1]/following::select[1]</value>
      <webElementGuid>77040a8e-c38e-4c55-a216-05dca54dd3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Approval Hierarchy'])[1]/preceding::select[1]</value>
      <webElementGuid>0cbb78cb-5ee4-4f4b-bd03-1a740b474001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found for the current environment'])[1]/preceding::select[1]</value>
      <webElementGuid>3ae8dca1-7fa7-488b-8f42-5172bfafc597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b9516e7e-44a6-4215-9c17-bdd9b3bb4fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P0_ENVIRONMENT' and @name = 'P0_ENVIRONMENT' and (text() = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
MXYZ
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
SAP_DEMO
SAP_ECC
SAP_S4HANA
ServiceCafe_Env
SFTP_Env2
SUCCESSFACTORS_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
' or . = 'Select any one
Coupa_Env1
EBizApp_JDBC_Env
EBiz_SFTP
GRM_CERP_ENV2_Cloud
GRM_CERP_ENV2_GRM
IDM_Coupa
JDE_Env
JDE_TEST
KTLNCloud_MonitorPaaS
KTLNEBS_MonitorPaaS
KTLN_CloudERP
KTLN_CloudERP_EACM
KTLN_DEV22
Kyriba_Env1
MAJUL_EBS
MXYZ
NEW_CLOUDERP
SailPoint_Env
SailPoint_ENV2
SAP_DEMO
SAP_ECC
SAP_S4HANA
ServiceCafe_Env
SFTP_Env2
SUCCESSFACTORS_ENV
Test_Environment
Test_Environment2
Test_Environment3_Hybris
Test_Environment4_CloudERP
Test_IDM
TEST_JDE92_ENV
TririgaDB_Env
Tririga_Env
Tririga_OS
WorkDayEnv_1
WorkDayEnv_3
WorkDay_Env
WorkDay_Env2
')]</value>
      <webElementGuid>584945b2-f553-429b-a7b6-5c9245f1a0e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
