<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Analytics_a-TreeView-toggle</name>
   <tag></tag>
   <elementGuidId>e216128d-d9a9-4848-a83b-c55f150a69dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_6 > span.a-TreeView-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7162e42-e25c-4acc-84e7-f91d53ff2ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>1736dcc1-7e16-4b0f-89a3-7dd94caeee08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_6&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>1e93673e-d09d-4a87-a32b-2ff6ff2a45b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>6debbf47-4f7f-4802-90f1-2999b22bdc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_6']/span</value>
      <webElementGuid>27f841a1-e739-4d25-8897-4f9158306820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
