<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_a-TreeView-toggle_1</name>
   <tag></tag>
   <elementGuidId>404afb99-5ccc-4da9-994d-4dd71fcf39ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_TreeNav_176 > span.a-TreeView-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Administration']//following::span[@class='a-TreeView-toggle'][3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;t_TreeNav_176&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>03af0913-9cf0-439e-954b-faa75b469380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-toggle</value>
      <webElementGuid>eee8726d-462d-4810-8a6a-359c90769e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_176&quot;)/span[@class=&quot;a-TreeView-toggle&quot;]</value>
      <webElementGuid>4a16978b-486a-472b-a4e2-c2837fb73ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_176']/span</value>
      <webElementGuid>c87f2ba7-e9dd-4c35-b49a-d295b175c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/span</value>
      <webElementGuid>2fbb199d-d5eb-4897-a3c8-c23dd98e53a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
