<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SODTest_CrossApp_Jul2_v1</name>
   <tag></tag>
   <elementGuidId>e965e199-7aca-4b19-8d5e-f74f3813fa6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[(text() = 'SODTest_CrossApp_Jul2_v1' or . = 'SODTest_CrossApp_Jul2_v1')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>46ad60c0-981f-40a4-9561-261368216e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-tL</value>
      <webElementGuid>7646a632-a8b6-4d04-a9fa-6dab061ed44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headers</name>
      <type>Main</type>
      <value>REQUEST_NAME</value>
      <webElementGuid>a2cb5a07-a24f-4326-a9a3-59734b7430ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SODTest_CrossApp_Jul2_v1</value>
      <webElementGuid>4579726b-cbe3-4466-aa32-c145892e7662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;169645300712451664&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tL&quot;]</value>
      <webElementGuid>384029d4-a2ee-4d45-b527-9fa1c7f96aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'SODTest_CrossApp_Jul2_v1' or . = 'SODTest_CrossApp_Jul2_v1')]</value>
      <webElementGuid>ad45ecb6-3007-4798-8947-9b0fda8ce62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/following::td[2]</value>
      <webElementGuid>215af599-7f62-4e69-87b0-af62a1f7768f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[2]/following::td[2]</value>
      <webElementGuid>eb01d51f-229b-4685-bd36-5a2de1da4129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SODTest_CrossApp_Jul2_v1'])[2]/preceding::td[1]</value>
      <webElementGuid>f8d5b63e-2f6d-4823-9a38-8eabbf582cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>1276f358-b35f-4700-884d-869d8e9f327f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='169645300712451664']/tbody/tr[2]/td[2]</value>
      <webElementGuid>06772228-355f-459d-ba6f-cd55a2095748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
